// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: aggregation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAggregationPolicy = `-- name: GetAggregationPolicy :one
SELECT id, assessment_id, method_version_ids, combiner, fault_tolerance, flag_triggers, set_official, updated_by, updated_at FROM aggregation_policies WHERE assessment_id = $1
`

func (q *Queries) GetAggregationPolicy(ctx context.Context, assessmentID int64) (AggregationPolicy, error) {
	row := q.db.QueryRow(ctx, getAggregationPolicy, assessmentID)
	var i AggregationPolicy
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.MethodVersionIds,
		&i.Combiner,
		&i.FaultTolerance,
		&i.FlagTriggers,
		&i.SetOfficial,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAggregateRecord = `-- name: InsertAggregateRecord :one
INSERT INTO grading_records (
    answer_id, source, rubric_version_id, criterion_scores, total, comment,
    adjustments, raw_output, created_by
)
VALUES ($1, 'aggregate', $2, $3, $4, $5, '[]'::jsonb, $6, $7)
RETURNING id, answer_id, run_id, source, provider, model_id, method_version_id, rubric_version_id, reference_solution_version_id, prompt_template_version_id, graded_image_shas, criterion_scores, total, comment, transcription, confidence, adjustments, raw_output, input_tokens, output_tokens, cost_usd, temperature, created_by, created_at, policy
`

type InsertAggregateRecordParams struct {
	AnswerID        int64          `json:"answer_id"`
	RubricVersionID int64          `json:"rubric_version_id"`
	CriterionScores []byte         `json:"criterion_scores"`
	Total           pgtype.Numeric `json:"total"`
	Comment         string         `json:"comment"`
	RawOutput       []byte         `json:"raw_output"`
	CreatedBy       pgtype.Int8    `json:"created_by"`
}

func (q *Queries) InsertAggregateRecord(ctx context.Context, arg InsertAggregateRecordParams) (GradingRecord, error) {
	row := q.db.QueryRow(ctx, insertAggregateRecord,
		arg.AnswerID,
		arg.RubricVersionID,
		arg.CriterionScores,
		arg.Total,
		arg.Comment,
		arg.RawOutput,
		arg.CreatedBy,
	)
	var i GradingRecord
	err := row.Scan(
		&i.ID,
		&i.AnswerID,
		&i.RunID,
		&i.Source,
		&i.Provider,
		&i.ModelID,
		&i.MethodVersionID,
		&i.RubricVersionID,
		&i.ReferenceSolutionVersionID,
		&i.PromptTemplateVersionID,
		&i.GradedImageShas,
		&i.CriterionScores,
		&i.Total,
		&i.Comment,
		&i.Transcription,
		&i.Confidence,
		&i.Adjustments,
		&i.RawOutput,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CostUsd,
		&i.Temperature,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Policy,
	)
	return i, err
}

const panelRecordsForAssessment = `-- name: PanelRecordsForAssessment :many
SELECT DISTINCT ON (a.id, gr.method_version_id)
    a.id AS answer_id,
    gr.id AS record_id,
    gr.method_version_id,
    gr.criterion_scores,
    gr.total,
    gr.confidence,
    gr.rubric_version_id,
    rv.score_increment
FROM answers a
JOIN grading_records gr ON gr.answer_id = a.id
JOIN rubric_versions rv ON rv.id = gr.rubric_version_id
WHERE a.assessment_id = $1
  AND gr.source = 'model'
  AND gr.total IS NOT NULL
  AND gr.method_version_id = ANY ($2::bigint [])
  AND gr.rubric_version_id = (
      SELECT rv2.id FROM rubric_versions rv2
      WHERE rv2.problem_id = a.problem_id
      ORDER BY rv2.version DESC LIMIT 1)
ORDER BY a.id, gr.method_version_id, gr.id DESC
`

type PanelRecordsForAssessmentParams struct {
	AssessmentID     int64   `json:"assessment_id"`
	MethodVersionIds []int64 `json:"method_version_ids"`
}

type PanelRecordsForAssessmentRow struct {
	AnswerID        int64          `json:"answer_id"`
	RecordID        int64          `json:"record_id"`
	MethodVersionID pgtype.Int8    `json:"method_version_id"`
	CriterionScores []byte         `json:"criterion_scores"`
	Total           pgtype.Numeric `json:"total"`
	Confidence      pgtype.Text    `json:"confidence"`
	RubricVersionID int64          `json:"rubric_version_id"`
	ScoreIncrement  pgtype.Numeric `json:"score_increment"`
}

// Latest usable model record per (answer, panel method version) across the
// assessment: non-NULL total, and rubric_version = the problem's current latest
// (D17/B-H20). Ordered for easy per-answer grouping in Go.
func (q *Queries) PanelRecordsForAssessment(ctx context.Context, arg PanelRecordsForAssessmentParams) ([]PanelRecordsForAssessmentRow, error) {
	rows, err := q.db.Query(ctx, panelRecordsForAssessment, arg.AssessmentID, arg.MethodVersionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PanelRecordsForAssessmentRow
	for rows.Next() {
		var i PanelRecordsForAssessmentRow
		if err := rows.Scan(
			&i.AnswerID,
			&i.RecordID,
			&i.MethodVersionID,
			&i.CriterionScores,
			&i.Total,
			&i.Confidence,
			&i.RubricVersionID,
			&i.ScoreIncrement,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAggregationPolicy = `-- name: UpsertAggregationPolicy :one
INSERT INTO aggregation_policies (assessment_id, method_version_ids, combiner, fault_tolerance, flag_triggers, set_official, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (assessment_id) DO UPDATE SET
    method_version_ids = EXCLUDED.method_version_ids,
    combiner = EXCLUDED.combiner,
    fault_tolerance = EXCLUDED.fault_tolerance,
    flag_triggers = EXCLUDED.flag_triggers,
    set_official = EXCLUDED.set_official,
    updated_by = EXCLUDED.updated_by,
    updated_at = now()
RETURNING id, assessment_id, method_version_ids, combiner, fault_tolerance, flag_triggers, set_official, updated_by, updated_at
`

type UpsertAggregationPolicyParams struct {
	AssessmentID     int64       `json:"assessment_id"`
	MethodVersionIds []int64     `json:"method_version_ids"`
	Combiner         string      `json:"combiner"`
	FaultTolerance   int32       `json:"fault_tolerance"`
	FlagTriggers     []string    `json:"flag_triggers"`
	SetOfficial      bool        `json:"set_official"`
	UpdatedBy        pgtype.Int8 `json:"updated_by"`
}

func (q *Queries) UpsertAggregationPolicy(ctx context.Context, arg UpsertAggregationPolicyParams) (AggregationPolicy, error) {
	row := q.db.QueryRow(ctx, upsertAggregationPolicy,
		arg.AssessmentID,
		arg.MethodVersionIds,
		arg.Combiner,
		arg.FaultTolerance,
		arg.FlagTriggers,
		arg.SetOfficial,
		arg.UpdatedBy,
	)
	var i AggregationPolicy
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.MethodVersionIds,
		&i.Combiner,
		&i.FaultTolerance,
		&i.FlagTriggers,
		&i.SetOfficial,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
