// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assessments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAssessmentRecords = `-- name: CountAssessmentRecords :one
SELECT count(*)
FROM grading_records gr
JOIN answers a ON a.id = gr.answer_id
WHERE a.assessment_id = $1
`

func (q *Queries) CountAssessmentRecords(ctx context.Context, assessmentID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAssessmentRecords, assessmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAssessmentSubmissions = `-- name: CountAssessmentSubmissions :one
SELECT count(*) FROM submissions WHERE assessment_id = $1
`

func (q *Queries) CountAssessmentSubmissions(ctx context.Context, assessmentID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAssessmentSubmissions, assessmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAssessment = `-- name: CreateAssessment :one
INSERT INTO assessments (kind, name, created_by)
VALUES ($1, $2, $3)
RETURNING id, kind, name, archived_at, created_by, created_at, updated_at, final_source_kind, final_method_id, regrade_deadline, final_run_id
`

type CreateAssessmentParams struct {
	Kind      string      `json:"kind"`
	Name      string      `json:"name"`
	CreatedBy pgtype.Int8 `json:"created_by"`
}

func (q *Queries) CreateAssessment(ctx context.Context, arg CreateAssessmentParams) (Assessment, error) {
	row := q.db.QueryRow(ctx, createAssessment, arg.Kind, arg.Name, arg.CreatedBy)
	var i Assessment
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.ArchivedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalSourceKind,
		&i.FinalMethodID,
		&i.RegradeDeadline,
		&i.FinalRunID,
	)
	return i, err
}

const deleteAssessment = `-- name: DeleteAssessment :exec
DELETE FROM assessments WHERE id = $1
`

func (q *Queries) DeleteAssessment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAssessment, id)
	return err
}

const getAssessment = `-- name: GetAssessment :one
SELECT id, kind, name, archived_at, created_by, created_at, updated_at, final_source_kind, final_method_id, regrade_deadline, final_run_id FROM assessments WHERE id = $1
`

func (q *Queries) GetAssessment(ctx context.Context, id int64) (Assessment, error) {
	row := q.db.QueryRow(ctx, getAssessment, id)
	var i Assessment
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.ArchivedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalSourceKind,
		&i.FinalMethodID,
		&i.RegradeDeadline,
		&i.FinalRunID,
	)
	return i, err
}

const getAssessmentForUpdate = `-- name: GetAssessmentForUpdate :one
SELECT id, kind, name, archived_at, created_by, created_at, updated_at, final_source_kind, final_method_id, regrade_deadline, final_run_id FROM assessments WHERE id = $1 FOR UPDATE
`

// Serializes final-source, publish, and retry transitions for one assessment.
// Every state-changing caller takes the assessment lock before any run lock.
func (q *Queries) GetAssessmentForUpdate(ctx context.Context, id int64) (Assessment, error) {
	row := q.db.QueryRow(ctx, getAssessmentForUpdate, id)
	var i Assessment
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.ArchivedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalSourceKind,
		&i.FinalMethodID,
		&i.RegradeDeadline,
		&i.FinalRunID,
	)
	return i, err
}

const listAssessments = `-- name: ListAssessments :many
SELECT a.id, a.kind, a.name, a.archived_at, a.created_by, a.created_at, a.updated_at, a.final_source_kind, a.final_method_id, a.regrade_deadline, a.final_run_id,
    (SELECT count(*) FROM problems p WHERE p.assessment_id = a.id) AS problem_count
FROM assessments a
WHERE ($1::bool OR a.archived_at IS NULL)
ORDER BY a.created_at DESC
`

type ListAssessmentsRow struct {
	ID              int64              `json:"id"`
	Kind            string             `json:"kind"`
	Name            string             `json:"name"`
	ArchivedAt      pgtype.Timestamptz `json:"archived_at"`
	CreatedBy       pgtype.Int8        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	FinalSourceKind pgtype.Text        `json:"final_source_kind"`
	FinalMethodID   pgtype.Int8        `json:"final_method_id"`
	RegradeDeadline pgtype.Timestamptz `json:"regrade_deadline"`
	FinalRunID      pgtype.Int8        `json:"final_run_id"`
	ProblemCount    int64              `json:"problem_count"`
}

func (q *Queries) ListAssessments(ctx context.Context, includeArchived bool) ([]ListAssessmentsRow, error) {
	rows, err := q.db.Query(ctx, listAssessments, includeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssessmentsRow
	for rows.Next() {
		var i ListAssessmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.ArchivedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinalSourceKind,
			&i.FinalMethodID,
			&i.RegradeDeadline,
			&i.FinalRunID,
			&i.ProblemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameAssessment = `-- name: RenameAssessment :one
UPDATE assessments SET name = $2, updated_at = now() WHERE id = $1 RETURNING id, kind, name, archived_at, created_by, created_at, updated_at, final_source_kind, final_method_id, regrade_deadline, final_run_id
`

type RenameAssessmentParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) RenameAssessment(ctx context.Context, arg RenameAssessmentParams) (Assessment, error) {
	row := q.db.QueryRow(ctx, renameAssessment, arg.ID, arg.Name)
	var i Assessment
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.ArchivedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalSourceKind,
		&i.FinalMethodID,
		&i.RegradeDeadline,
		&i.FinalRunID,
	)
	return i, err
}

const setAssessmentArchived = `-- name: SetAssessmentArchived :one
UPDATE assessments
SET archived_at = CASE WHEN $2::bool THEN now() ELSE NULL END,
    updated_at = now()
WHERE id = $1
RETURNING id, kind, name, archived_at, created_by, created_at, updated_at, final_source_kind, final_method_id, regrade_deadline, final_run_id
`

type SetAssessmentArchivedParams struct {
	ID       int64 `json:"id"`
	Archived bool  `json:"archived"`
}

func (q *Queries) SetAssessmentArchived(ctx context.Context, arg SetAssessmentArchivedParams) (Assessment, error) {
	row := q.db.QueryRow(ctx, setAssessmentArchived, arg.ID, arg.Archived)
	var i Assessment
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.ArchivedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalSourceKind,
		&i.FinalMethodID,
		&i.RegradeDeadline,
		&i.FinalRunID,
	)
	return i, err
}

const setAssessmentFinalSource = `-- name: SetAssessmentFinalSource :one
UPDATE assessments
SET final_source_kind = $2,
    final_method_id = $3,
    final_run_id = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, kind, name, archived_at, created_by, created_at, updated_at, final_source_kind, final_method_id, regrade_deadline, final_run_id
`

type SetAssessmentFinalSourceParams struct {
	ID       int64       `json:"id"`
	Kind     pgtype.Text `json:"kind"`
	MethodID pgtype.Int8 `json:"method_id"`
	RunID    pgtype.Int8 `json:"run_id"`
}

// SetAssessmentFinalSource records the exam-wide grading source (round-based
// grading, 0027/0035): kind 'method' carries an exact run plus its derived
// method id; 'consensus'/NULL carry neither (DB CHECK enforces).
func (q *Queries) SetAssessmentFinalSource(ctx context.Context, arg SetAssessmentFinalSourceParams) (Assessment, error) {
	row := q.db.QueryRow(ctx, setAssessmentFinalSource,
		arg.ID,
		arg.Kind,
		arg.MethodID,
		arg.RunID,
	)
	var i Assessment
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.ArchivedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalSourceKind,
		&i.FinalMethodID,
		&i.RegradeDeadline,
		&i.FinalRunID,
	)
	return i, err
}

const setAssessmentRegradeDeadline = `-- name: SetAssessmentRegradeDeadline :one
UPDATE assessments
SET regrade_deadline = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, kind, name, archived_at, created_by, created_at, updated_at, final_source_kind, final_method_id, regrade_deadline, final_run_id
`

type SetAssessmentRegradeDeadlineParams struct {
	ID       int64              `json:"id"`
	Deadline pgtype.Timestamptz `json:"deadline"`
}

func (q *Queries) SetAssessmentRegradeDeadline(ctx context.Context, arg SetAssessmentRegradeDeadlineParams) (Assessment, error) {
	row := q.db.QueryRow(ctx, setAssessmentRegradeDeadline, arg.ID, arg.Deadline)
	var i Assessment
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.ArchivedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalSourceKind,
		&i.FinalMethodID,
		&i.RegradeDeadline,
		&i.FinalRunID,
	)
	return i, err
}
