// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAudit = `-- name: CountAudit :one
SELECT count(*)
FROM audit_log al
WHERE ($1::text IS NULL OR al.target_kind = $1)
  AND ($2::text IS NULL OR al.target_id = $2)
  AND ($3::text IS NULL OR al.action = $3)
  AND ($4::bigint IS NULL OR al.actor_user_id = $4)
`

type CountAuditParams struct {
	TargetKind  pgtype.Text `json:"target_kind"`
	TargetID    pgtype.Text `json:"target_id"`
	Action      pgtype.Text `json:"action"`
	ActorUserID pgtype.Int8 `json:"actor_user_id"`
}

func (q *Queries) CountAudit(ctx context.Context, arg CountAuditParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAudit,
		arg.TargetKind,
		arg.TargetID,
		arg.Action,
		arg.ActorUserID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit_log (actor_user_id, action, target_kind, target_id, detail)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAuditParams struct {
	ActorUserID pgtype.Int8 `json:"actor_user_id"`
	Action      string      `json:"action"`
	TargetKind  string      `json:"target_kind"`
	TargetID    string      `json:"target_id"`
	Detail      []byte      `json:"detail"`
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.ActorUserID,
		arg.Action,
		arg.TargetKind,
		arg.TargetID,
		arg.Detail,
	)
	return err
}

const listAudit = `-- name: ListAudit :many
SELECT al.id, al.actor_user_id, al.action, al.target_kind, al.target_id, al.detail, al.created_at, u.email AS actor_email
FROM audit_log al
LEFT JOIN users u ON u.id = al.actor_user_id
WHERE ($1::text IS NULL OR al.target_kind = $1)
  AND ($2::text IS NULL OR al.target_id = $2)
  AND ($3::text IS NULL OR al.action = $3)
  AND ($4::bigint IS NULL OR al.actor_user_id = $4)
ORDER BY al.id DESC
LIMIT $6 OFFSET $5
`

type ListAuditParams struct {
	TargetKind  pgtype.Text `json:"target_kind"`
	TargetID    pgtype.Text `json:"target_id"`
	Action      pgtype.Text `json:"action"`
	ActorUserID pgtype.Int8 `json:"actor_user_id"`
	RowOffset   int32       `json:"row_offset"`
	RowLimit    int32       `json:"row_limit"`
}

type ListAuditRow struct {
	ID          int64              `json:"id"`
	ActorUserID pgtype.Int8        `json:"actor_user_id"`
	Action      string             `json:"action"`
	TargetKind  string             `json:"target_kind"`
	TargetID    string             `json:"target_id"`
	Detail      []byte             `json:"detail"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ActorEmail  pgtype.Text        `json:"actor_email"`
}

// ListAudit is the admin audit-log read path (trust spec §6, D39): all filters
// optional, newest-first, paginated. actor_email joins users for display since
// actor_user_id alone isn't human-readable in the UI.
func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]ListAuditRow, error) {
	rows, err := q.db.Query(ctx, listAudit,
		arg.TargetKind,
		arg.TargetID,
		arg.Action,
		arg.ActorUserID,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditRow
	for rows.Next() {
		var i ListAuditRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.Action,
			&i.TargetKind,
			&i.TargetID,
			&i.Detail,
			&i.CreatedAt,
			&i.ActorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditForTarget = `-- name: ListAuditForTarget :many
SELECT id, actor_user_id, action, target_kind, target_id, detail, created_at FROM audit_log WHERE target_kind = $1 AND target_id = $2 ORDER BY id DESC LIMIT $3
`

type ListAuditForTargetParams struct {
	TargetKind string `json:"target_kind"`
	TargetID   string `json:"target_id"`
	Limit      int32  `json:"limit"`
}

func (q *Queries) ListAuditForTarget(ctx context.Context, arg ListAuditForTargetParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditForTarget, arg.TargetKind, arg.TargetID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.Action,
			&i.TargetKind,
			&i.TargetID,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
