// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grading.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearUnpublishedOfficials = `-- name: ClearUnpublishedOfficials :execrows
UPDATE answers
SET official_record_id = NULL,
    official_set_by = NULL,
    official_set_at = NULL,
    updated_at = now()
WHERE assessment_id = $1
  AND published_at IS NULL
  AND official_record_id IS NOT NULL
`

// ClearUnpublishedOfficials is RecomputeOfficials' "no source chosen" arm:
// before an exam picks its final source, nothing is official.
func (q *Queries) ClearUnpublishedOfficials(ctx context.Context, assessmentID int64) (int64, error) {
	result, err := q.db.Exec(ctx, clearUnpublishedOfficials, assessmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertHumanRecord = `-- name: InsertHumanRecord :one
INSERT INTO grading_records (answer_id, source, rubric_version_id, graded_image_shas, criterion_scores, total, comment, adjustments, created_by)
VALUES ($1, 'human', $2, $3, $4, $5, $6, $7, $8)
RETURNING id, answer_id, run_id, source, provider, model_id, method_version_id, rubric_version_id, reference_solution_version_id, prompt_template_version_id, graded_image_shas, criterion_scores, total, comment, transcription, confidence, adjustments, raw_output, input_tokens, output_tokens, cost_usd, temperature, created_by, created_at, policy
`

type InsertHumanRecordParams struct {
	AnswerID        int64          `json:"answer_id"`
	RubricVersionID int64          `json:"rubric_version_id"`
	GradedImageShas []string       `json:"graded_image_shas"`
	CriterionScores []byte         `json:"criterion_scores"`
	Total           pgtype.Numeric `json:"total"`
	Comment         string         `json:"comment"`
	Adjustments     []byte         `json:"adjustments"`
	CreatedBy       pgtype.Int8    `json:"created_by"`
}

func (q *Queries) InsertHumanRecord(ctx context.Context, arg InsertHumanRecordParams) (GradingRecord, error) {
	row := q.db.QueryRow(ctx, insertHumanRecord,
		arg.AnswerID,
		arg.RubricVersionID,
		arg.GradedImageShas,
		arg.CriterionScores,
		arg.Total,
		arg.Comment,
		arg.Adjustments,
		arg.CreatedBy,
	)
	var i GradingRecord
	err := row.Scan(
		&i.ID,
		&i.AnswerID,
		&i.RunID,
		&i.Source,
		&i.Provider,
		&i.ModelID,
		&i.MethodVersionID,
		&i.RubricVersionID,
		&i.ReferenceSolutionVersionID,
		&i.PromptTemplateVersionID,
		&i.GradedImageShas,
		&i.CriterionScores,
		&i.Total,
		&i.Comment,
		&i.Transcription,
		&i.Confidence,
		&i.Adjustments,
		&i.RawOutput,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CostUsd,
		&i.Temperature,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Policy,
	)
	return i, err
}

const recomputeOfficials = `-- name: RecomputeOfficials :execrows

UPDATE answers a
SET official_record_id = pick.rec_id,
    official_set_by = NULL,
    official_set_at = CASE WHEN pick.rec_id IS NULL THEN NULL ELSE now() END,
    updated_at = now()
FROM (
    SELECT ans.id AS answer_id,
        COALESCE(CASE WHEN cardinality(ans.flags) = 0 THEN src.id END, hum.id) AS rec_id
    FROM answers ans
    LEFT JOIN LATERAL (
        SELECT gr.id
        FROM grading_records gr
        WHERE gr.answer_id = ans.id
          AND gr.total IS NOT NULL
          AND gr.rubric_version_id = (
              SELECT rv.id FROM rubric_versions rv
              WHERE rv.problem_id = ans.problem_id
              ORDER BY rv.version DESC
              LIMIT 1)
          AND (($2::bigint IS NOT NULL
                  AND gr.source = 'model'
                  AND gr.run_id = $2)
              OR ($2::bigint IS NULL
                  AND gr.source = 'aggregate'))
        ORDER BY gr.id DESC
        LIMIT 1
    ) src ON true
    LEFT JOIN LATERAL (
        SELECT gr.id
        FROM grading_records gr
        WHERE gr.answer_id = ans.id
          AND gr.source = 'human'
          AND gr.total IS NOT NULL
          AND gr.rubric_version_id = (
              SELECT rv.id FROM rubric_versions rv
              WHERE rv.problem_id = ans.problem_id
              ORDER BY rv.version DESC
              LIMIT 1)
        ORDER BY gr.id DESC
        LIMIT 1
    ) hum ON true
    WHERE ans.assessment_id = $1 AND ans.published_at IS NULL
) pick
WHERE a.id = pick.answer_id
  AND a.official_record_id IS DISTINCT FROM pick.rec_id
`

type RecomputeOfficialsParams struct {
	AssessmentID int64       `json:"assessment_id"`
	FinalRunID   pgtype.Int8 `json:"final_run_id"`
}

// The official pointer is DERIVED (round-based grading, migration 0027): the
// assessment's chosen final source decides every answer; a human record applies
// ONLY where the source is silent. Nothing else may write official_record_id.
//
// Rule per unpublished answer:
//
//	source record = latest record on the problem's CURRENT rubric version with a
//	  total, from the chosen source (kind='method': source='model' from the exact
//	  pinned run; kind='consensus': source='aggregate') — but only when the
//	  answer carries NO flags (any flag, agg_* or manual, blocks the AI source
//	  and demands human eyes);
//	fallback      = latest human record on the current rubric;
//	official      = source record if present, else fallback, else NULL (a hole —
//	  surfaced red on the publish preview until a human grades it).
//
// Published answers are never touched (spec §2 lock).
func (q *Queries) RecomputeOfficials(ctx context.Context, arg RecomputeOfficialsParams) (int64, error) {
	result, err := q.db.Exec(ctx, recomputeOfficials, arg.AssessmentID, arg.FinalRunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
