// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingestion.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAnswerFlag = `-- name: AddAnswerFlag :exec
UPDATE answers SET flags = array_append(flags, $2::text), updated_at = now()
WHERE id = $1 AND NOT ($2::text = ANY (flags))
`

type AddAnswerFlagParams struct {
	ID   int64  `json:"id"`
	Flag string `json:"flag"`
}

func (q *Queries) AddAnswerFlag(ctx context.Context, arg AddAnswerFlagParams) error {
	_, err := q.db.Exec(ctx, addAnswerFlag, arg.ID, arg.Flag)
	return err
}

const addFlagForStudentAssessment = `-- name: AddFlagForStudentAssessment :exec
UPDATE answers SET flags = array_append(flags, $3::text), updated_at = now()
WHERE assessment_id = $1 AND student_id = $2 AND NOT ($3::text = ANY (flags))
`

type AddFlagForStudentAssessmentParams struct {
	AssessmentID int64  `json:"assessment_id"`
	StudentID    int64  `json:"student_id"`
	Flag         string `json:"flag"`
}

func (q *Queries) AddFlagForStudentAssessment(ctx context.Context, arg AddFlagForStudentAssessmentParams) error {
	_, err := q.db.Exec(ctx, addFlagForStudentAssessment, arg.AssessmentID, arg.StudentID, arg.Flag)
	return err
}

const addFlagForStudentProblem = `-- name: AddFlagForStudentProblem :exec
UPDATE answers SET flags = array_append(flags, $4::text), updated_at = now()
WHERE assessment_id = $1 AND student_id = $2 AND problem_id = $3 AND NOT ($4::text = ANY (flags))
`

type AddFlagForStudentProblemParams struct {
	AssessmentID int64  `json:"assessment_id"`
	StudentID    int64  `json:"student_id"`
	ProblemID    int64  `json:"problem_id"`
	Flag         string `json:"flag"`
}

func (q *Queries) AddFlagForStudentProblem(ctx context.Context, arg AddFlagForStudentProblemParams) error {
	_, err := q.db.Exec(ctx, addFlagForStudentProblem,
		arg.AssessmentID,
		arg.StudentID,
		arg.ProblemID,
		arg.Flag,
	)
	return err
}

const countAnswersForAssessment = `-- name: CountAnswersForAssessment :one
SELECT count(*) FROM answers WHERE assessment_id = $1
`

// CountAnswersForAssessment backs the materialize-answers action's
// `{"created": n}` response (roster-lifecycle plan 2026-07-10):
// MaterializeAnswers is :exec (its ingest caller ignores the row count), so
// the handler counts before/after inside the same transaction instead.
func (q *Queries) CountAnswersForAssessment(ctx context.Context, assessmentID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAnswersForAssessment, assessmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedForStudentAssessment = `-- name: CountPublishedForStudentAssessment :one
SELECT count(*) FROM answers
WHERE assessment_id = $1 AND student_id = $2 AND published_at IS NOT NULL
`

type CountPublishedForStudentAssessmentParams struct {
	AssessmentID int64 `json:"assessment_id"`
	StudentID    int64 `json:"student_id"`
}

func (q *Queries) CountPublishedForStudentAssessment(ctx context.Context, arg CountPublishedForStudentAssessmentParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedForStudentAssessment, arg.AssessmentID, arg.StudentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedForStudentProblem = `-- name: CountPublishedForStudentProblem :one
SELECT count(*) FROM answers
WHERE assessment_id = $1 AND student_id = $2 AND problem_id = $3 AND published_at IS NOT NULL
`

type CountPublishedForStudentProblemParams struct {
	AssessmentID int64 `json:"assessment_id"`
	StudentID    int64 `json:"student_id"`
	ProblemID    int64 `json:"problem_id"`
}

func (q *Queries) CountPublishedForStudentProblem(ctx context.Context, arg CountPublishedForStudentProblemParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedForStudentProblem, arg.AssessmentID, arg.StudentID, arg.ProblemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecordsForStudentAssessment = `-- name: CountRecordsForStudentAssessment :one
SELECT count(*)
FROM grading_records gr
JOIN answers a ON a.id = gr.answer_id
WHERE a.assessment_id = $1 AND a.student_id = $2
`

type CountRecordsForStudentAssessmentParams struct {
	AssessmentID int64 `json:"assessment_id"`
	StudentID    int64 `json:"student_id"`
}

func (q *Queries) CountRecordsForStudentAssessment(ctx context.Context, arg CountRecordsForStudentAssessmentParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecordsForStudentAssessment, arg.AssessmentID, arg.StudentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecordsForStudentProblem = `-- name: CountRecordsForStudentProblem :one
SELECT count(*)
FROM grading_records gr
JOIN answers a ON a.id = gr.answer_id
WHERE a.assessment_id = $1 AND a.student_id = $2 AND a.problem_id = $3
`

type CountRecordsForStudentProblemParams struct {
	AssessmentID int64 `json:"assessment_id"`
	StudentID    int64 `json:"student_id"`
	ProblemID    int64 `json:"problem_id"`
}

func (q *Queries) CountRecordsForStudentProblem(ctx context.Context, arg CountRecordsForStudentProblemParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecordsForStudentProblem, arg.AssessmentID, arg.StudentID, arg.ProblemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAnswerPage = `-- name: CreateAnswerPage :one
INSERT INTO answer_pages (answer_id, page_index, submission_id, pdf_page_index, image_ref, image_sha256, image_width, image_height, text_loss_runs)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, answer_id, page_index, submission_id, pdf_page_index, image_ref, image_sha256, image_width, image_height, masked_image_ref, masked_at, mask_review_status, mask_reviewed_by, mask_reviewed_at, created_at, mask_input_sha, mask_error, text_loss_runs
`

type CreateAnswerPageParams struct {
	AnswerID     int64  `json:"answer_id"`
	PageIndex    int32  `json:"page_index"`
	SubmissionID int64  `json:"submission_id"`
	PdfPageIndex int32  `json:"pdf_page_index"`
	ImageRef     string `json:"image_ref"`
	ImageSha256  string `json:"image_sha256"`
	ImageWidth   int32  `json:"image_width"`
	ImageHeight  int32  `json:"image_height"`
	TextLossRuns int32  `json:"text_loss_runs"`
}

func (q *Queries) CreateAnswerPage(ctx context.Context, arg CreateAnswerPageParams) (AnswerPage, error) {
	row := q.db.QueryRow(ctx, createAnswerPage,
		arg.AnswerID,
		arg.PageIndex,
		arg.SubmissionID,
		arg.PdfPageIndex,
		arg.ImageRef,
		arg.ImageSha256,
		arg.ImageWidth,
		arg.ImageHeight,
		arg.TextLossRuns,
	)
	var i AnswerPage
	err := row.Scan(
		&i.ID,
		&i.AnswerID,
		&i.PageIndex,
		&i.SubmissionID,
		&i.PdfPageIndex,
		&i.ImageRef,
		&i.ImageSha256,
		&i.ImageWidth,
		&i.ImageHeight,
		&i.MaskedImageRef,
		&i.MaskedAt,
		&i.MaskReviewStatus,
		&i.MaskReviewedBy,
		&i.MaskReviewedAt,
		&i.CreatedAt,
		&i.MaskInputSha,
		&i.MaskError,
		&i.TextLossRuns,
	)
	return i, err
}

const createQuarantine = `-- name: CreateQuarantine :one
INSERT INTO upload_quarantine (assessment_id, original_filename, pdf_ref, pdf_sha256, reason, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, assessment_id, original_filename, pdf_ref, pdf_sha256, reason, uploaded_by, uploaded_at, resolved_at, resolved_student_id
`

type CreateQuarantineParams struct {
	AssessmentID     int64       `json:"assessment_id"`
	OriginalFilename string      `json:"original_filename"`
	PdfRef           string      `json:"pdf_ref"`
	PdfSha256        string      `json:"pdf_sha256"`
	Reason           string      `json:"reason"`
	UploadedBy       pgtype.Int8 `json:"uploaded_by"`
}

func (q *Queries) CreateQuarantine(ctx context.Context, arg CreateQuarantineParams) (UploadQuarantine, error) {
	row := q.db.QueryRow(ctx, createQuarantine,
		arg.AssessmentID,
		arg.OriginalFilename,
		arg.PdfRef,
		arg.PdfSha256,
		arg.Reason,
		arg.UploadedBy,
	)
	var i UploadQuarantine
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.OriginalFilename,
		&i.PdfRef,
		&i.PdfSha256,
		&i.Reason,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.ResolvedAt,
		&i.ResolvedStudentID,
	)
	return i, err
}

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (assessment_id, student_id, original_filename, source_ref, source_sha256, source_kind, page_count, uploaded_by, problem_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, assessment_id, student_id, original_filename, source_ref, source_sha256, page_count, uploaded_by, uploaded_at, superseded_by, source_kind, problem_id, retracted_at
`

type CreateSubmissionParams struct {
	AssessmentID     int64       `json:"assessment_id"`
	StudentID        int64       `json:"student_id"`
	OriginalFilename string      `json:"original_filename"`
	SourceRef        string      `json:"source_ref"`
	SourceSha256     string      `json:"source_sha256"`
	SourceKind       string      `json:"source_kind"`
	PageCount        int32       `json:"page_count"`
	UploadedBy       pgtype.Int8 `json:"uploaded_by"`
	ProblemID        pgtype.Int8 `json:"problem_id"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, createSubmission,
		arg.AssessmentID,
		arg.StudentID,
		arg.OriginalFilename,
		arg.SourceRef,
		arg.SourceSha256,
		arg.SourceKind,
		arg.PageCount,
		arg.UploadedBy,
		arg.ProblemID,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.StudentID,
		&i.OriginalFilename,
		&i.SourceRef,
		&i.SourceSha256,
		&i.PageCount,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.SupersededBy,
		&i.SourceKind,
		&i.ProblemID,
		&i.RetractedAt,
	)
	return i, err
}

const deletePagesBySubmission = `-- name: DeletePagesBySubmission :exec
DELETE FROM answer_pages WHERE submission_id = $1
`

func (q *Queries) DeletePagesBySubmission(ctx context.Context, submissionID int64) error {
	_, err := q.db.Exec(ctx, deletePagesBySubmission, submissionID)
	return err
}

const deletePagesForAnswer = `-- name: DeletePagesForAnswer :exec
DELETE FROM answer_pages WHERE answer_id = $1
`

// Clears one answer's pages regardless of which submission owns them, so a
// per-problem promotion can supersede only that problem's coverage even when the
// pages were positionally mapped by a still-live whole-assessment submission (§8).
func (q *Queries) DeletePagesForAnswer(ctx context.Context, answerID int64) error {
	_, err := q.db.Exec(ctx, deletePagesForAnswer, answerID)
	return err
}

const deletePagesForStudentAssessment = `-- name: DeletePagesForStudentAssessment :exec
DELETE FROM answer_pages
WHERE answer_id IN (SELECT id FROM answers WHERE assessment_id = $1 AND student_id = $2)
`

type DeletePagesForStudentAssessmentParams struct {
	AssessmentID int64 `json:"assessment_id"`
	StudentID    int64 `json:"student_id"`
}

func (q *Queries) DeletePagesForStudentAssessment(ctx context.Context, arg DeletePagesForStudentAssessmentParams) error {
	_, err := q.db.Exec(ctx, deletePagesForStudentAssessment, arg.AssessmentID, arg.StudentID)
	return err
}

const dismissQuarantine = `-- name: DismissQuarantine :execrows
UPDATE upload_quarantine
SET resolved_at = now(), resolved_student_id = NULL
WHERE id = $1 AND resolved_at IS NULL
`

func (q *Queries) DismissQuarantine(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, dismissQuarantine, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureAnswer = `-- name: EnsureAnswer :one
INSERT INTO answers (assessment_id, student_id, problem_id)
VALUES ($1, $2, $3)
ON CONFLICT (assessment_id, student_id, problem_id) DO UPDATE SET updated_at = answers.updated_at
RETURNING id, assessment_id, student_id, problem_id, official_record_id, official_set_by, official_set_at, published_at, flags, created_at, updated_at
`

type EnsureAnswerParams struct {
	AssessmentID int64 `json:"assessment_id"`
	StudentID    int64 `json:"student_id"`
	ProblemID    int64 `json:"problem_id"`
}

func (q *Queries) EnsureAnswer(ctx context.Context, arg EnsureAnswerParams) (Answer, error) {
	row := q.db.QueryRow(ctx, ensureAnswer, arg.AssessmentID, arg.StudentID, arg.ProblemID)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.StudentID,
		&i.ProblemID,
		&i.OfficialRecordID,
		&i.OfficialSetBy,
		&i.OfficialSetAt,
		&i.PublishedAt,
		&i.Flags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveSubmission = `-- name: GetActiveSubmission :one
SELECT id, assessment_id, student_id, original_filename, source_ref, source_sha256, page_count, uploaded_by, uploaded_at, superseded_by, source_kind, problem_id, retracted_at FROM submissions
WHERE assessment_id = $1 AND student_id = $2 AND superseded_by IS NULL AND retracted_at IS NULL AND problem_id IS NULL
`

type GetActiveSubmissionParams struct {
	AssessmentID int64 `json:"assessment_id"`
	StudentID    int64 `json:"student_id"`
}

func (q *Queries) GetActiveSubmission(ctx context.Context, arg GetActiveSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, getActiveSubmission, arg.AssessmentID, arg.StudentID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.StudentID,
		&i.OriginalFilename,
		&i.SourceRef,
		&i.SourceSha256,
		&i.PageCount,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.SupersededBy,
		&i.SourceKind,
		&i.ProblemID,
		&i.RetractedAt,
	)
	return i, err
}

const getActiveSubmissionForProblem = `-- name: GetActiveSubmissionForProblem :one
SELECT id, assessment_id, student_id, original_filename, source_ref, source_sha256, page_count, uploaded_by, uploaded_at, superseded_by, source_kind, problem_id, retracted_at FROM submissions
WHERE assessment_id = $1 AND student_id = $2 AND problem_id = $3 AND superseded_by IS NULL AND retracted_at IS NULL
`

type GetActiveSubmissionForProblemParams struct {
	AssessmentID int64       `json:"assessment_id"`
	StudentID    int64       `json:"student_id"`
	ProblemID    pgtype.Int8 `json:"problem_id"`
}

func (q *Queries) GetActiveSubmissionForProblem(ctx context.Context, arg GetActiveSubmissionForProblemParams) (Submission, error) {
	row := q.db.QueryRow(ctx, getActiveSubmissionForProblem, arg.AssessmentID, arg.StudentID, arg.ProblemID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.StudentID,
		&i.OriginalFilename,
		&i.SourceRef,
		&i.SourceSha256,
		&i.PageCount,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.SupersededBy,
		&i.SourceKind,
		&i.ProblemID,
		&i.RetractedAt,
	)
	return i, err
}

const getAnswer = `-- name: GetAnswer :one
SELECT id, assessment_id, student_id, problem_id, official_record_id, official_set_by, official_set_at, published_at, flags, created_at, updated_at FROM answers WHERE id = $1
`

func (q *Queries) GetAnswer(ctx context.Context, id int64) (Answer, error) {
	row := q.db.QueryRow(ctx, getAnswer, id)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.StudentID,
		&i.ProblemID,
		&i.OfficialRecordID,
		&i.OfficialSetBy,
		&i.OfficialSetAt,
		&i.PublishedAt,
		&i.Flags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAnswerByKey = `-- name: GetAnswerByKey :one
SELECT id, assessment_id, student_id, problem_id, official_record_id, official_set_by, official_set_at, published_at, flags, created_at, updated_at FROM answers WHERE assessment_id = $1 AND student_id = $2 AND problem_id = $3
`

type GetAnswerByKeyParams struct {
	AssessmentID int64 `json:"assessment_id"`
	StudentID    int64 `json:"student_id"`
	ProblemID    int64 `json:"problem_id"`
}

func (q *Queries) GetAnswerByKey(ctx context.Context, arg GetAnswerByKeyParams) (Answer, error) {
	row := q.db.QueryRow(ctx, getAnswerByKey, arg.AssessmentID, arg.StudentID, arg.ProblemID)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.StudentID,
		&i.ProblemID,
		&i.OfficialRecordID,
		&i.OfficialSetBy,
		&i.OfficialSetAt,
		&i.PublishedAt,
		&i.Flags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAnswerPage = `-- name: GetAnswerPage :one
SELECT id, answer_id, page_index, submission_id, pdf_page_index, image_ref, image_sha256, image_width, image_height, masked_image_ref, masked_at, mask_review_status, mask_reviewed_by, mask_reviewed_at, created_at, mask_input_sha, mask_error, text_loss_runs FROM answer_pages WHERE id = $1
`

func (q *Queries) GetAnswerPage(ctx context.Context, id int64) (AnswerPage, error) {
	row := q.db.QueryRow(ctx, getAnswerPage, id)
	var i AnswerPage
	err := row.Scan(
		&i.ID,
		&i.AnswerID,
		&i.PageIndex,
		&i.SubmissionID,
		&i.PdfPageIndex,
		&i.ImageRef,
		&i.ImageSha256,
		&i.ImageWidth,
		&i.ImageHeight,
		&i.MaskedImageRef,
		&i.MaskedAt,
		&i.MaskReviewStatus,
		&i.MaskReviewedBy,
		&i.MaskReviewedAt,
		&i.CreatedAt,
		&i.MaskInputSha,
		&i.MaskError,
		&i.TextLossRuns,
	)
	return i, err
}

const getQuarantine = `-- name: GetQuarantine :one
SELECT id, assessment_id, original_filename, pdf_ref, pdf_sha256, reason, uploaded_by, uploaded_at, resolved_at, resolved_student_id FROM upload_quarantine WHERE id = $1
`

func (q *Queries) GetQuarantine(ctx context.Context, id int64) (UploadQuarantine, error) {
	row := q.db.QueryRow(ctx, getQuarantine, id)
	var i UploadQuarantine
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.OriginalFilename,
		&i.PdfRef,
		&i.PdfSha256,
		&i.Reason,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.ResolvedAt,
		&i.ResolvedStudentID,
	)
	return i, err
}

const getSubmission = `-- name: GetSubmission :one
SELECT id, assessment_id, student_id, original_filename, source_ref, source_sha256, page_count, uploaded_by, uploaded_at, superseded_by, source_kind, problem_id, retracted_at FROM submissions WHERE id = $1
`

func (q *Queries) GetSubmission(ctx context.Context, id int64) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmission, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.StudentID,
		&i.OriginalFilename,
		&i.SourceRef,
		&i.SourceSha256,
		&i.PageCount,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.SupersededBy,
		&i.SourceKind,
		&i.ProblemID,
		&i.RetractedAt,
	)
	return i, err
}

const ingestReportRows = `-- name: IngestReportRows :many
SELECT st.id AS student_db_id,
    st.student_id,
    st.name,
    s.id AS submission_id,
    s.page_count,
    s.original_filename,
    (SELECT count(*) FROM answer_pages ap
        JOIN answers a ON a.id = ap.answer_id
        WHERE a.assessment_id = $1 AND a.student_id = st.id) AS mapped_pages
FROM students st
LEFT JOIN submissions s
    ON s.assessment_id = $1 AND s.student_id = st.id AND s.superseded_by IS NULL AND s.retracted_at IS NULL AND s.problem_id IS NULL
WHERE st.withdrawn_at IS NULL
ORDER BY st.student_id
`

type IngestReportRowsRow struct {
	StudentDbID      int64       `json:"student_db_id"`
	StudentID        string      `json:"student_id"`
	Name             string      `json:"name"`
	SubmissionID     pgtype.Int8 `json:"submission_id"`
	PageCount        pgtype.Int4 `json:"page_count"`
	OriginalFilename pgtype.Text `json:"original_filename"`
	MappedPages      int64       `json:"mapped_pages"`
}

func (q *Queries) IngestReportRows(ctx context.Context, assessmentID int64) ([]IngestReportRowsRow, error) {
	rows, err := q.db.Query(ctx, ingestReportRows, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngestReportRowsRow
	for rows.Next() {
		var i IngestReportRowsRow
		if err := rows.Scan(
			&i.StudentDbID,
			&i.StudentID,
			&i.Name,
			&i.SubmissionID,
			&i.PageCount,
			&i.OriginalFilename,
			&i.MappedPages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSubmissions = `-- name: ListActiveSubmissions :many
SELECT s.id, s.assessment_id, s.student_id, s.original_filename, s.source_ref, s.source_sha256, s.page_count, s.uploaded_by, s.uploaded_at, s.superseded_by, s.source_kind, s.problem_id, s.retracted_at, st.student_id AS student_external_id, st.name AS student_name
FROM submissions s
JOIN students st ON st.id = s.student_id
WHERE s.assessment_id = $1 AND s.superseded_by IS NULL
ORDER BY st.student_id
`

type ListActiveSubmissionsRow struct {
	ID                int64              `json:"id"`
	AssessmentID      int64              `json:"assessment_id"`
	StudentID         int64              `json:"student_id"`
	OriginalFilename  string             `json:"original_filename"`
	SourceRef         string             `json:"source_ref"`
	SourceSha256      string             `json:"source_sha256"`
	PageCount         int32              `json:"page_count"`
	UploadedBy        pgtype.Int8        `json:"uploaded_by"`
	UploadedAt        pgtype.Timestamptz `json:"uploaded_at"`
	SupersededBy      pgtype.Int8        `json:"superseded_by"`
	SourceKind        string             `json:"source_kind"`
	ProblemID         pgtype.Int8        `json:"problem_id"`
	RetractedAt       pgtype.Timestamptz `json:"retracted_at"`
	StudentExternalID string             `json:"student_external_id"`
	StudentName       string             `json:"student_name"`
}

func (q *Queries) ListActiveSubmissions(ctx context.Context, assessmentID int64) ([]ListActiveSubmissionsRow, error) {
	rows, err := q.db.Query(ctx, listActiveSubmissions, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveSubmissionsRow
	for rows.Next() {
		var i ListActiveSubmissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.StudentID,
			&i.OriginalFilename,
			&i.SourceRef,
			&i.SourceSha256,
			&i.PageCount,
			&i.UploadedBy,
			&i.UploadedAt,
			&i.SupersededBy,
			&i.SourceKind,
			&i.ProblemID,
			&i.RetractedAt,
			&i.StudentExternalID,
			&i.StudentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnswerPages = `-- name: ListAnswerPages :many
SELECT id, answer_id, page_index, submission_id, pdf_page_index, image_ref, image_sha256, image_width, image_height, masked_image_ref, masked_at, mask_review_status, mask_reviewed_by, mask_reviewed_at, created_at, mask_input_sha, mask_error, text_loss_runs FROM answer_pages WHERE answer_id = $1 ORDER BY page_index
`

func (q *Queries) ListAnswerPages(ctx context.Context, answerID int64) ([]AnswerPage, error) {
	rows, err := q.db.Query(ctx, listAnswerPages, answerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnswerPage
	for rows.Next() {
		var i AnswerPage
		if err := rows.Scan(
			&i.ID,
			&i.AnswerID,
			&i.PageIndex,
			&i.SubmissionID,
			&i.PdfPageIndex,
			&i.ImageRef,
			&i.ImageSha256,
			&i.ImageWidth,
			&i.ImageHeight,
			&i.MaskedImageRef,
			&i.MaskedAt,
			&i.MaskReviewStatus,
			&i.MaskReviewedBy,
			&i.MaskReviewedAt,
			&i.CreatedAt,
			&i.MaskInputSha,
			&i.MaskError,
			&i.TextLossRuns,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnswersForAssessment = `-- name: ListAnswersForAssessment :many
SELECT id, assessment_id, student_id, problem_id, official_record_id, official_set_by, official_set_at, published_at, flags, created_at, updated_at FROM answers WHERE assessment_id = $1 ORDER BY student_id, problem_id
`

func (q *Queries) ListAnswersForAssessment(ctx context.Context, assessmentID int64) ([]Answer, error) {
	rows, err := q.db.Query(ctx, listAnswersForAssessment, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Answer
	for rows.Next() {
		var i Answer
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.StudentID,
			&i.ProblemID,
			&i.OfficialRecordID,
			&i.OfficialSetBy,
			&i.OfficialSetAt,
			&i.PublishedAt,
			&i.Flags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveSubmissionsForStudent = `-- name: ListLiveSubmissionsForStudent :many
SELECT id, assessment_id, student_id, original_filename, source_ref, source_sha256, page_count, uploaded_by, uploaded_at, superseded_by, source_kind, problem_id, retracted_at FROM submissions
WHERE assessment_id = $1 AND student_id = $2 AND superseded_by IS NULL AND retracted_at IS NULL
ORDER BY id
`

type ListLiveSubmissionsForStudentParams struct {
	AssessmentID int64 `json:"assessment_id"`
	StudentID    int64 `json:"student_id"`
}

// Every live submission for (assessment, student) — whole-assessment (problem_id
// IS NULL) AND per-problem rows alike. Used when a whole-assessment upload must
// supersede all coexisting submissions (spec §8).
func (q *Queries) ListLiveSubmissionsForStudent(ctx context.Context, arg ListLiveSubmissionsForStudentParams) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listLiveSubmissionsForStudent, arg.AssessmentID, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.StudentID,
			&i.OriginalFilename,
			&i.SourceRef,
			&i.SourceSha256,
			&i.PageCount,
			&i.UploadedBy,
			&i.UploadedAt,
			&i.SupersededBy,
			&i.SourceKind,
			&i.ProblemID,
			&i.RetractedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenQuarantine = `-- name: ListOpenQuarantine :many
SELECT id, assessment_id, original_filename, pdf_ref, pdf_sha256, reason, uploaded_by, uploaded_at, resolved_at, resolved_student_id FROM upload_quarantine WHERE assessment_id = $1 AND resolved_at IS NULL ORDER BY id
`

func (q *Queries) ListOpenQuarantine(ctx context.Context, assessmentID int64) ([]UploadQuarantine, error) {
	rows, err := q.db.Query(ctx, listOpenQuarantine, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadQuarantine
	for rows.Next() {
		var i UploadQuarantine
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.OriginalFilename,
			&i.PdfRef,
			&i.PdfSha256,
			&i.Reason,
			&i.UploadedBy,
			&i.UploadedAt,
			&i.ResolvedAt,
			&i.ResolvedStudentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const materializeAnswers = `-- name: MaterializeAnswers :exec
INSERT INTO answers (assessment_id, student_id, problem_id)
SELECT $1, st.id, p.id
FROM students st
CROSS JOIN problems p
WHERE p.assessment_id = $1 AND st.withdrawn_at IS NULL
ON CONFLICT DO NOTHING
`

func (q *Queries) MaterializeAnswers(ctx context.Context, assessmentID int64) error {
	_, err := q.db.Exec(ctx, materializeAnswers, assessmentID)
	return err
}

const moveAnswerPage = `-- name: MoveAnswerPage :one
UPDATE answer_pages SET answer_id = $2, page_index = $3 WHERE id = $1 RETURNING id, answer_id, page_index, submission_id, pdf_page_index, image_ref, image_sha256, image_width, image_height, masked_image_ref, masked_at, mask_review_status, mask_reviewed_by, mask_reviewed_at, created_at, mask_input_sha, mask_error, text_loss_runs
`

type MoveAnswerPageParams struct {
	ID        int64 `json:"id"`
	AnswerID  int64 `json:"answer_id"`
	PageIndex int32 `json:"page_index"`
}

func (q *Queries) MoveAnswerPage(ctx context.Context, arg MoveAnswerPageParams) (AnswerPage, error) {
	row := q.db.QueryRow(ctx, moveAnswerPage, arg.ID, arg.AnswerID, arg.PageIndex)
	var i AnswerPage
	err := row.Scan(
		&i.ID,
		&i.AnswerID,
		&i.PageIndex,
		&i.SubmissionID,
		&i.PdfPageIndex,
		&i.ImageRef,
		&i.ImageSha256,
		&i.ImageWidth,
		&i.ImageHeight,
		&i.MaskedImageRef,
		&i.MaskedAt,
		&i.MaskReviewStatus,
		&i.MaskReviewedBy,
		&i.MaskReviewedAt,
		&i.CreatedAt,
		&i.MaskInputSha,
		&i.MaskError,
		&i.TextLossRuns,
	)
	return i, err
}

const nextPageIndex = `-- name: NextPageIndex :one
SELECT COALESCE(MAX(page_index) + 1, 0)::int FROM answer_pages WHERE answer_id = $1
`

func (q *Queries) NextPageIndex(ctx context.Context, answerID int64) (int32, error) {
	row := q.db.QueryRow(ctx, nextPageIndex, answerID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const reclassifyQuarantine = `-- name: ReclassifyQuarantine :execrows
UPDATE upload_quarantine
SET reason = $2
WHERE id = $1 AND resolved_at IS NULL
`

type ReclassifyQuarantineParams struct {
	ID     int64  `json:"id"`
	Reason string `json:"reason"`
}

func (q *Queries) ReclassifyQuarantine(ctx context.Context, arg ReclassifyQuarantineParams) (int64, error) {
	result, err := q.db.Exec(ctx, reclassifyQuarantine, arg.ID, arg.Reason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeAnswerFlag = `-- name: RemoveAnswerFlag :exec
UPDATE answers SET flags = array_remove(flags, $2::text), updated_at = now()
WHERE id = $1 AND $2::text = ANY (flags)
`

type RemoveAnswerFlagParams struct {
	ID   int64  `json:"id"`
	Flag string `json:"flag"`
}

// RemoveAnswerFlag is guarded the same way AddAnswerFlag is (F11): without the
// ANY(flags) check, aggregation's per-answer "clear all agg_* flags, re-add
// raised" loop (grading/aggregate_run.go) rewrites every answer row 3x per
// pass even when nothing changed, stamping a fresh updated_at each time. The
// guard makes the UPDATE match zero rows when the flag was never present.
func (q *Queries) RemoveAnswerFlag(ctx context.Context, arg RemoveAnswerFlagParams) error {
	_, err := q.db.Exec(ctx, removeAnswerFlag, arg.ID, arg.Flag)
	return err
}

const resolveQuarantine = `-- name: ResolveQuarantine :exec
UPDATE upload_quarantine SET resolved_at = now(), resolved_student_id = $2 WHERE id = $1
`

type ResolveQuarantineParams struct {
	ID                int64       `json:"id"`
	ResolvedStudentID pgtype.Int8 `json:"resolved_student_id"`
}

func (q *Queries) ResolveQuarantine(ctx context.Context, arg ResolveQuarantineParams) error {
	_, err := q.db.Exec(ctx, resolveQuarantine, arg.ID, arg.ResolvedStudentID)
	return err
}

const retractSubmission = `-- name: RetractSubmission :exec
UPDATE submissions SET retracted_at = now() WHERE id = $1
`

func (q *Queries) RetractSubmission(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, retractSubmission, id)
	return err
}

const supersedeSubmission = `-- name: SupersedeSubmission :exec
UPDATE submissions SET superseded_by = $2 WHERE id = $1
`

type SupersedeSubmissionParams struct {
	ID           int64       `json:"id"`
	SupersededBy pgtype.Int8 `json:"superseded_by"`
}

func (q *Queries) SupersedeSubmission(ctx context.Context, arg SupersedeSubmissionParams) error {
	_, err := q.db.Exec(ctx, supersedeSubmission, arg.ID, arg.SupersededBy)
	return err
}
