// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: masks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptPendingMasks = `-- name: AcceptPendingMasks :execrows
UPDATE answer_pages ap
SET mask_review_status = 'accepted', mask_reviewed_by = $2, mask_reviewed_at = now()
FROM answers a
JOIN problems p ON p.id = a.problem_id
WHERE ap.answer_id = a.id AND p.assessment_id = $1
  AND ap.mask_review_status = 'pending' AND ap.masked_image_ref IS NOT NULL
`

type AcceptPendingMasksParams struct {
	AssessmentID   int64       `json:"assessment_id"`
	MaskReviewedBy pgtype.Int8 `json:"mask_reviewed_by"`
}

// AcceptPendingMasks bulk-accepts every masked page of an assessment whose
// review is still pending — the "spot-checked a few, accept the rest" path.
// Unmasked pages (no derivative to review) and flagged pages are untouched.
func (q *Queries) AcceptPendingMasks(ctx context.Context, arg AcceptPendingMasksParams) (int64, error) {
	result, err := q.db.Exec(ctx, acceptPendingMasks, arg.AssessmentID, arg.MaskReviewedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countMaskBlockers = `-- name: CountMaskBlockers :one
SELECT count(*)
FROM answer_pages ap
JOIN answers a ON a.id = ap.answer_id
WHERE a.assessment_id = $1
  AND (ap.masked_image_ref IS NULL OR ap.mask_review_status <> 'accepted')
`

func (q *Queries) CountMaskBlockers(ctx context.Context, assessmentID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countMaskBlockers, assessmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMaskRegion = `-- name: CreateMaskRegion :one
INSERT INTO mask_regions (assessment_id, page_scope, x, y, w, h, color, padding)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, assessment_id, page_scope, x, y, w, h, color, padding, created_at
`

type CreateMaskRegionParams struct {
	AssessmentID int64   `json:"assessment_id"`
	PageScope    string  `json:"page_scope"`
	X            float32 `json:"x"`
	Y            float32 `json:"y"`
	W            float32 `json:"w"`
	H            float32 `json:"h"`
	Color        string  `json:"color"`
	Padding      float32 `json:"padding"`
}

func (q *Queries) CreateMaskRegion(ctx context.Context, arg CreateMaskRegionParams) (MaskRegion, error) {
	row := q.db.QueryRow(ctx, createMaskRegion,
		arg.AssessmentID,
		arg.PageScope,
		arg.X,
		arg.Y,
		arg.W,
		arg.H,
		arg.Color,
		arg.Padding,
	)
	var i MaskRegion
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.PageScope,
		&i.X,
		&i.Y,
		&i.W,
		&i.H,
		&i.Color,
		&i.Padding,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMaskRegions = `-- name: DeleteMaskRegions :exec
DELETE FROM mask_regions WHERE assessment_id = $1
`

func (q *Queries) DeleteMaskRegions(ctx context.Context, assessmentID int64) error {
	_, err := q.db.Exec(ctx, deleteMaskRegions, assessmentID)
	return err
}

const listAcceptedMaskPages = `-- name: ListAcceptedMaskPages :many
SELECT ap.id, ap.image_sha256, ap.pdf_page_index, ap.masked_image_ref, ap.mask_input_sha
FROM answer_pages ap
JOIN answers a ON a.id = ap.answer_id
WHERE a.assessment_id = $1 AND ap.mask_review_status = 'accepted'
`

type ListAcceptedMaskPagesRow struct {
	ID             int64       `json:"id"`
	ImageSha256    string      `json:"image_sha256"`
	PdfPageIndex   int32       `json:"pdf_page_index"`
	MaskedImageRef pgtype.Text `json:"masked_image_ref"`
	MaskInputSha   pgtype.Text `json:"mask_input_sha"`
}

// ListAcceptedMaskPages feeds the stale-mask reconciliation (stale-mask fix
// 2026-07-11): the review-ACCEPTED pages of an assessment with just the columns
// ingest.StaleAcceptedMasks needs to recompute each page's mask fingerprint
// (MaskFingerprint is Go-side sha256, so the comparison can't live in SQL).
// Accepted pages are the only ones that matter here — pending/flagged/unmasked
// pages already fail the CountMaskBlockers gates.
func (q *Queries) ListAcceptedMaskPages(ctx context.Context, assessmentID int64) ([]ListAcceptedMaskPagesRow, error) {
	rows, err := q.db.Query(ctx, listAcceptedMaskPages, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAcceptedMaskPagesRow
	for rows.Next() {
		var i ListAcceptedMaskPagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ImageSha256,
			&i.PdfPageIndex,
			&i.MaskedImageRef,
			&i.MaskInputSha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaskRegions = `-- name: ListMaskRegions :many
SELECT id, assessment_id, page_scope, x, y, w, h, color, padding, created_at FROM mask_regions WHERE assessment_id = $1 ORDER BY id
`

func (q *Queries) ListMaskRegions(ctx context.Context, assessmentID int64) ([]MaskRegion, error) {
	rows, err := q.db.Query(ctx, listMaskRegions, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaskRegion
	for rows.Next() {
		var i MaskRegion
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.PageScope,
			&i.X,
			&i.Y,
			&i.W,
			&i.H,
			&i.Color,
			&i.Padding,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPagesForAssessment = `-- name: ListPagesForAssessment :many
SELECT ap.id, ap.answer_id, ap.page_index, ap.submission_id, ap.pdf_page_index, ap.image_ref, ap.image_sha256, ap.image_width, ap.image_height, ap.masked_image_ref, ap.masked_at, ap.mask_review_status, ap.mask_reviewed_by, ap.mask_reviewed_at, ap.created_at, ap.mask_input_sha, ap.mask_error, ap.text_loss_runs, a.assessment_id, a.student_id, a.problem_id
FROM answer_pages ap
JOIN answers a ON a.id = ap.answer_id
WHERE a.assessment_id = $1
ORDER BY ap.answer_id, ap.page_index
`

type ListPagesForAssessmentRow struct {
	ID               int64              `json:"id"`
	AnswerID         int64              `json:"answer_id"`
	PageIndex        int32              `json:"page_index"`
	SubmissionID     int64              `json:"submission_id"`
	PdfPageIndex     int32              `json:"pdf_page_index"`
	ImageRef         string             `json:"image_ref"`
	ImageSha256      string             `json:"image_sha256"`
	ImageWidth       int32              `json:"image_width"`
	ImageHeight      int32              `json:"image_height"`
	MaskedImageRef   pgtype.Text        `json:"masked_image_ref"`
	MaskedAt         pgtype.Timestamptz `json:"masked_at"`
	MaskReviewStatus string             `json:"mask_review_status"`
	MaskReviewedBy   pgtype.Int8        `json:"mask_reviewed_by"`
	MaskReviewedAt   pgtype.Timestamptz `json:"mask_reviewed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	MaskInputSha     pgtype.Text        `json:"mask_input_sha"`
	MaskError        pgtype.Text        `json:"mask_error"`
	TextLossRuns     int32              `json:"text_loss_runs"`
	AssessmentID     int64              `json:"assessment_id"`
	StudentID        int64              `json:"student_id"`
	ProblemID        int64              `json:"problem_id"`
}

func (q *Queries) ListPagesForAssessment(ctx context.Context, assessmentID int64) ([]ListPagesForAssessmentRow, error) {
	rows, err := q.db.Query(ctx, listPagesForAssessment, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPagesForAssessmentRow
	for rows.Next() {
		var i ListPagesForAssessmentRow
		if err := rows.Scan(
			&i.ID,
			&i.AnswerID,
			&i.PageIndex,
			&i.SubmissionID,
			&i.PdfPageIndex,
			&i.ImageRef,
			&i.ImageSha256,
			&i.ImageWidth,
			&i.ImageHeight,
			&i.MaskedImageRef,
			&i.MaskedAt,
			&i.MaskReviewStatus,
			&i.MaskReviewedBy,
			&i.MaskReviewedAt,
			&i.CreatedAt,
			&i.MaskInputSha,
			&i.MaskError,
			&i.TextLossRuns,
			&i.AssessmentID,
			&i.StudentID,
			&i.ProblemID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maskReviewList = `-- name: MaskReviewList :many
SELECT ap.id, ap.answer_id, ap.page_index, ap.masked_image_ref, ap.mask_review_status,
    ap.mask_error, st.student_id, p.number AS problem_number
FROM answer_pages ap
JOIN answers a ON a.id = ap.answer_id
JOIN students st ON st.id = a.student_id
JOIN problems p ON p.id = a.problem_id
WHERE a.assessment_id = $1
ORDER BY p.number, st.student_id, ap.page_index
`

type MaskReviewListRow struct {
	ID               int64       `json:"id"`
	AnswerID         int64       `json:"answer_id"`
	PageIndex        int32       `json:"page_index"`
	MaskedImageRef   pgtype.Text `json:"masked_image_ref"`
	MaskReviewStatus string      `json:"mask_review_status"`
	MaskError        pgtype.Text `json:"mask_error"`
	StudentID        string      `json:"student_id"`
	ProblemNumber    int32       `json:"problem_number"`
}

func (q *Queries) MaskReviewList(ctx context.Context, assessmentID int64) ([]MaskReviewListRow, error) {
	rows, err := q.db.Query(ctx, maskReviewList, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaskReviewListRow
	for rows.Next() {
		var i MaskReviewListRow
		if err := rows.Scan(
			&i.ID,
			&i.AnswerID,
			&i.PageIndex,
			&i.MaskedImageRef,
			&i.MaskReviewStatus,
			&i.MaskError,
			&i.StudentID,
			&i.ProblemNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetStaleMaskReview = `-- name: ResetStaleMaskReview :execrows
UPDATE answer_pages
SET mask_review_status = 'pending', mask_reviewed_by = NULL, mask_reviewed_at = NULL
WHERE id = ANY ($1::bigint [])
  AND mask_review_status = 'accepted'
`

// ResetStaleMaskReview knocks accepted pages back to pending (clearing the
// reviewer stamp) when their masked artifact was produced from inputs that no
// longer match the current region set (stale-mask fix 2026-07-11): without this,
// a region edit after review acceptance leaves the old — possibly identity-
// revealing — masked images flowing to providers forever, because the grading
// gates only check "masked + accepted". The accepted-only guard makes the reset
// idempotent and keeps it from touching flagged pages (already blockers).
func (q *Queries) ResetStaleMaskReview(ctx context.Context, pageIds []int64) (int64, error) {
	result, err := q.db.Exec(ctx, resetStaleMaskReview, pageIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMaskReview = `-- name: SetMaskReview :one
UPDATE answer_pages
SET mask_review_status = $2, mask_reviewed_by = $3, mask_reviewed_at = now()
WHERE id = $1
RETURNING id, answer_id, page_index, submission_id, pdf_page_index, image_ref, image_sha256, image_width, image_height, masked_image_ref, masked_at, mask_review_status, mask_reviewed_by, mask_reviewed_at, created_at, mask_input_sha, mask_error, text_loss_runs
`

type SetMaskReviewParams struct {
	ID               int64       `json:"id"`
	MaskReviewStatus string      `json:"mask_review_status"`
	MaskReviewedBy   pgtype.Int8 `json:"mask_reviewed_by"`
}

func (q *Queries) SetMaskReview(ctx context.Context, arg SetMaskReviewParams) (AnswerPage, error) {
	row := q.db.QueryRow(ctx, setMaskReview, arg.ID, arg.MaskReviewStatus, arg.MaskReviewedBy)
	var i AnswerPage
	err := row.Scan(
		&i.ID,
		&i.AnswerID,
		&i.PageIndex,
		&i.SubmissionID,
		&i.PdfPageIndex,
		&i.ImageRef,
		&i.ImageSha256,
		&i.ImageWidth,
		&i.ImageHeight,
		&i.MaskedImageRef,
		&i.MaskedAt,
		&i.MaskReviewStatus,
		&i.MaskReviewedBy,
		&i.MaskReviewedAt,
		&i.CreatedAt,
		&i.MaskInputSha,
		&i.MaskError,
		&i.TextLossRuns,
	)
	return i, err
}

const setPageMaskError = `-- name: SetPageMaskError :exec
UPDATE answer_pages SET mask_error = $2 WHERE id = $1
`

type SetPageMaskErrorParams struct {
	ID        int64       `json:"id"`
	MaskError pgtype.Text `json:"mask_error"`
}

// SetPageMaskError records a short, PII-FREE terminal error on a page whose mask
// job exhausted its River attempts on a deterministic failure (D27 review, F1),
// so the D10 run gate and the review UI can show WHY the page never masked instead
// of blocking silently. The message is a static reason category only — never a
// dynamic string that could carry a path or student content.
func (q *Queries) SetPageMaskError(ctx context.Context, arg SetPageMaskErrorParams) error {
	_, err := q.db.Exec(ctx, setPageMaskError, arg.ID, arg.MaskError)
	return err
}

const setPageMasked = `-- name: SetPageMasked :one
UPDATE answer_pages
SET masked_image_ref = $2, mask_input_sha = $3, masked_at = now(),
    mask_review_status = 'pending', mask_reviewed_by = NULL, mask_reviewed_at = NULL,
    mask_error = NULL
WHERE id = $1
RETURNING id, answer_id, page_index, submission_id, pdf_page_index, image_ref, image_sha256, image_width, image_height, masked_image_ref, masked_at, mask_review_status, mask_reviewed_by, mask_reviewed_at, created_at, mask_input_sha, mask_error, text_loss_runs
`

type SetPageMaskedParams struct {
	ID             int64       `json:"id"`
	MaskedImageRef pgtype.Text `json:"masked_image_ref"`
	MaskInputSha   pgtype.Text `json:"mask_input_sha"`
}

// SetPageMasked records the freshly-masked artifact and the fingerprint of the
// inputs that produced it (mask_input_sha — original sha + quality + region set),
// and resets the page's mask review to pending (D10). The fingerprint lets a
// re-apply job skip pages already up to date and preserve their review status
// (D27, F2): only pages whose inputs actually changed are re-masked + re-reset.
// It also clears mask_error (D27 review, F1): a successful (re-)mask is the
// recovery from an earlier terminal decode failure.
func (q *Queries) SetPageMasked(ctx context.Context, arg SetPageMaskedParams) (AnswerPage, error) {
	row := q.db.QueryRow(ctx, setPageMasked, arg.ID, arg.MaskedImageRef, arg.MaskInputSha)
	var i AnswerPage
	err := row.Scan(
		&i.ID,
		&i.AnswerID,
		&i.PageIndex,
		&i.SubmissionID,
		&i.PdfPageIndex,
		&i.ImageRef,
		&i.ImageSha256,
		&i.ImageWidth,
		&i.ImageHeight,
		&i.MaskedImageRef,
		&i.MaskedAt,
		&i.MaskReviewStatus,
		&i.MaskReviewedBy,
		&i.MaskReviewedAt,
		&i.CreatedAt,
		&i.MaskInputSha,
		&i.MaskError,
		&i.TextLossRuns,
	)
	return i, err
}
