// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: methods.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countGradingMethods = `-- name: CountGradingMethods :one
SELECT count(*) FROM grading_methods
`

func (q *Queries) CountGradingMethods(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGradingMethods)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGradingMethod = `-- name: CreateGradingMethod :one
INSERT INTO grading_methods (name) VALUES ($1) RETURNING id, name, archived_at, created_at, updated_at
`

func (q *Queries) CreateGradingMethod(ctx context.Context, name string) (GradingMethod, error) {
	row := q.db.QueryRow(ctx, createGradingMethod, name)
	var i GradingMethod
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMethodVersion = `-- name: CreateMethodVersion :one
INSERT INTO grading_method_versions (method_id, version, config, created_by)
VALUES (
    $1,
    (SELECT COALESCE(MAX(version), 0) + 1 FROM grading_method_versions WHERE method_id = $1),
    $2, $3
)
RETURNING id, method_id, version, config, created_by, created_at
`

type CreateMethodVersionParams struct {
	MethodID  int64       `json:"method_id"`
	Config    []byte      `json:"config"`
	CreatedBy pgtype.Int8 `json:"created_by"`
}

func (q *Queries) CreateMethodVersion(ctx context.Context, arg CreateMethodVersionParams) (GradingMethodVersion, error) {
	row := q.db.QueryRow(ctx, createMethodVersion, arg.MethodID, arg.Config, arg.CreatedBy)
	var i GradingMethodVersion
	err := row.Scan(
		&i.ID,
		&i.MethodID,
		&i.Version,
		&i.Config,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createPromptTemplateVersion = `-- name: CreatePromptTemplateVersion :one
INSERT INTO prompt_template_versions (name, version, system_template, user_template, created_by)
VALUES (
    $1,
    (SELECT COALESCE(MAX(version), 0) + 1 FROM prompt_template_versions WHERE name = $1),
    $2, $3, $4
)
RETURNING id, name, version, system_template, user_template, created_by, created_at
`

type CreatePromptTemplateVersionParams struct {
	Name           string      `json:"name"`
	SystemTemplate string      `json:"system_template"`
	UserTemplate   string      `json:"user_template"`
	CreatedBy      pgtype.Int8 `json:"created_by"`
}

func (q *Queries) CreatePromptTemplateVersion(ctx context.Context, arg CreatePromptTemplateVersionParams) (PromptTemplateVersion, error) {
	row := q.db.QueryRow(ctx, createPromptTemplateVersion,
		arg.Name,
		arg.SystemTemplate,
		arg.UserTemplate,
		arg.CreatedBy,
	)
	var i PromptTemplateVersion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.SystemTemplate,
		&i.UserTemplate,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getGradingMethod = `-- name: GetGradingMethod :one
SELECT id, name, archived_at, created_at, updated_at FROM grading_methods WHERE id = $1
`

func (q *Queries) GetGradingMethod(ctx context.Context, id int64) (GradingMethod, error) {
	row := q.db.QueryRow(ctx, getGradingMethod, id)
	var i GradingMethod
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMethodVersion = `-- name: GetMethodVersion :one
SELECT id, method_id, version, config, created_by, created_at FROM grading_method_versions WHERE id = $1
`

func (q *Queries) GetMethodVersion(ctx context.Context, id int64) (GradingMethodVersion, error) {
	row := q.db.QueryRow(ctx, getMethodVersion, id)
	var i GradingMethodVersion
	err := row.Scan(
		&i.ID,
		&i.MethodID,
		&i.Version,
		&i.Config,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPromptTemplateVersion = `-- name: GetPromptTemplateVersion :one
SELECT id, name, version, system_template, user_template, created_by, created_at FROM prompt_template_versions WHERE id = $1
`

func (q *Queries) GetPromptTemplateVersion(ctx context.Context, id int64) (PromptTemplateVersion, error) {
	row := q.db.QueryRow(ctx, getPromptTemplateVersion, id)
	var i PromptTemplateVersion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.SystemTemplate,
		&i.UserTemplate,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const latestMethodVersion = `-- name: LatestMethodVersion :one
SELECT id, method_id, version, config, created_by, created_at FROM grading_method_versions WHERE method_id = $1 ORDER BY version DESC LIMIT 1
`

func (q *Queries) LatestMethodVersion(ctx context.Context, methodID int64) (GradingMethodVersion, error) {
	row := q.db.QueryRow(ctx, latestMethodVersion, methodID)
	var i GradingMethodVersion
	err := row.Scan(
		&i.ID,
		&i.MethodID,
		&i.Version,
		&i.Config,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const latestPromptTemplate = `-- name: LatestPromptTemplate :one
SELECT id, name, version, system_template, user_template, created_by, created_at FROM prompt_template_versions WHERE name = $1 ORDER BY version DESC LIMIT 1
`

func (q *Queries) LatestPromptTemplate(ctx context.Context, name string) (PromptTemplateVersion, error) {
	row := q.db.QueryRow(ctx, latestPromptTemplate, name)
	var i PromptTemplateVersion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.SystemTemplate,
		&i.UserTemplate,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listGradingMethods = `-- name: ListGradingMethods :many
SELECT id, name, archived_at, created_at, updated_at FROM grading_methods
WHERE ($1::bool OR archived_at IS NULL)
ORDER BY name
`

func (q *Queries) ListGradingMethods(ctx context.Context, includeArchived bool) ([]GradingMethod, error) {
	rows, err := q.db.Query(ctx, listGradingMethods, includeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GradingMethod
	for rows.Next() {
		var i GradingMethod
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMethodVersions = `-- name: ListMethodVersions :many
SELECT id, method_id, version, config, created_by, created_at FROM grading_method_versions WHERE method_id = $1 ORDER BY version DESC
`

func (q *Queries) ListMethodVersions(ctx context.Context, methodID int64) ([]GradingMethodVersion, error) {
	rows, err := q.db.Query(ctx, listMethodVersions, methodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GradingMethodVersion
	for rows.Next() {
		var i GradingMethodVersion
		if err := rows.Scan(
			&i.ID,
			&i.MethodID,
			&i.Version,
			&i.Config,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMethodArchived = `-- name: SetMethodArchived :one
UPDATE grading_methods
SET archived_at = CASE WHEN $2::bool THEN now() ELSE NULL END,
    updated_at = now()
WHERE id = $1
RETURNING id, name, archived_at, created_at, updated_at
`

type SetMethodArchivedParams struct {
	ID       int64 `json:"id"`
	Archived bool  `json:"archived"`
}

func (q *Queries) SetMethodArchived(ctx context.Context, arg SetMethodArchivedParams) (GradingMethod, error) {
	row := q.db.QueryRow(ctx, setMethodArchived, arg.ID, arg.Archived)
	var i GradingMethod
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
