// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AggregationPolicy struct {
	ID               int64              `json:"id"`
	AssessmentID     int64              `json:"assessment_id"`
	MethodVersionIds []int64            `json:"method_version_ids"`
	Combiner         string             `json:"combiner"`
	FaultTolerance   int32              `json:"fault_tolerance"`
	FlagTriggers     []string           `json:"flag_triggers"`
	SetOfficial      bool               `json:"set_official"`
	UpdatedBy        pgtype.Int8        `json:"updated_by"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Answer struct {
	ID               int64              `json:"id"`
	AssessmentID     int64              `json:"assessment_id"`
	StudentID        int64              `json:"student_id"`
	ProblemID        int64              `json:"problem_id"`
	OfficialRecordID pgtype.Int8        `json:"official_record_id"`
	OfficialSetBy    pgtype.Int8        `json:"official_set_by"`
	OfficialSetAt    pgtype.Timestamptz `json:"official_set_at"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
	Flags            []string           `json:"flags"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type AnswerPage struct {
	ID               int64              `json:"id"`
	AnswerID         int64              `json:"answer_id"`
	PageIndex        int32              `json:"page_index"`
	SubmissionID     int64              `json:"submission_id"`
	PdfPageIndex     int32              `json:"pdf_page_index"`
	ImageRef         string             `json:"image_ref"`
	ImageSha256      string             `json:"image_sha256"`
	ImageWidth       int32              `json:"image_width"`
	ImageHeight      int32              `json:"image_height"`
	MaskedImageRef   pgtype.Text        `json:"masked_image_ref"`
	MaskedAt         pgtype.Timestamptz `json:"masked_at"`
	MaskReviewStatus string             `json:"mask_review_status"`
	MaskReviewedBy   pgtype.Int8        `json:"mask_reviewed_by"`
	MaskReviewedAt   pgtype.Timestamptz `json:"mask_reviewed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	MaskInputSha     pgtype.Text        `json:"mask_input_sha"`
	MaskError        pgtype.Text        `json:"mask_error"`
	TextLossRuns     int32              `json:"text_loss_runs"`
}

type Assessment struct {
	ID              int64              `json:"id"`
	Kind            string             `json:"kind"`
	Name            string             `json:"name"`
	ArchivedAt      pgtype.Timestamptz `json:"archived_at"`
	CreatedBy       pgtype.Int8        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	FinalSourceKind pgtype.Text        `json:"final_source_kind"`
	FinalMethodID   pgtype.Int8        `json:"final_method_id"`
	RegradeDeadline pgtype.Timestamptz `json:"regrade_deadline"`
	FinalRunID      pgtype.Int8        `json:"final_run_id"`
}

type AuditLog struct {
	ID          int64              `json:"id"`
	ActorUserID pgtype.Int8        `json:"actor_user_id"`
	Action      string             `json:"action"`
	TargetKind  string             `json:"target_kind"`
	TargetID    string             `json:"target_id"`
	Detail      []byte             `json:"detail"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type DirectUpload struct {
	ID               int64              `json:"id"`
	AssessmentID     int64              `json:"assessment_id"`
	OriginalFilename string             `json:"original_filename"`
	SourceRef        string             `json:"source_ref"`
	SourceSha256     string             `json:"source_sha256"`
	SourceKind       string             `json:"source_kind"`
	Force            bool               `json:"force"`
	UploadedBy       pgtype.Int8        `json:"uploaded_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	FinishedAt       pgtype.Timestamptz `json:"finished_at"`
	Status           pgtype.Text        `json:"status"`
	Reason           pgtype.Text        `json:"reason"`
	SubmissionID     pgtype.Int8        `json:"submission_id"`
	Error            pgtype.Text        `json:"error"`
}

type GradingMethod struct {
	ID         int64              `json:"id"`
	Name       string             `json:"name"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type GradingMethodVersion struct {
	ID        int64              `json:"id"`
	MethodID  int64              `json:"method_id"`
	Version   int32              `json:"version"`
	Config    []byte             `json:"config"`
	CreatedBy pgtype.Int8        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GradingRecord struct {
	ID                         int64              `json:"id"`
	AnswerID                   int64              `json:"answer_id"`
	RunID                      pgtype.Int8        `json:"run_id"`
	Source                     string             `json:"source"`
	Provider                   pgtype.Text        `json:"provider"`
	ModelID                    pgtype.Text        `json:"model_id"`
	MethodVersionID            pgtype.Int8        `json:"method_version_id"`
	RubricVersionID            int64              `json:"rubric_version_id"`
	ReferenceSolutionVersionID pgtype.Int8        `json:"reference_solution_version_id"`
	PromptTemplateVersionID    pgtype.Int8        `json:"prompt_template_version_id"`
	GradedImageShas            []string           `json:"graded_image_shas"`
	CriterionScores            []byte             `json:"criterion_scores"`
	Total                      pgtype.Numeric     `json:"total"`
	Comment                    string             `json:"comment"`
	Transcription              pgtype.Text        `json:"transcription"`
	Confidence                 pgtype.Text        `json:"confidence"`
	Adjustments                []byte             `json:"adjustments"`
	RawOutput                  []byte             `json:"raw_output"`
	InputTokens                pgtype.Int4        `json:"input_tokens"`
	OutputTokens               pgtype.Int4        `json:"output_tokens"`
	CostUsd                    pgtype.Numeric     `json:"cost_usd"`
	Temperature                pgtype.Float4      `json:"temperature"`
	CreatedBy                  pgtype.Int8        `json:"created_by"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	Policy                     pgtype.Text        `json:"policy"`
}

type GradingRun struct {
	ID              int64              `json:"id"`
	AssessmentID    int64              `json:"assessment_id"`
	ScopeKind       string             `json:"scope_kind"`
	ScopeID         int64              `json:"scope_id"`
	MethodVersionID int64              `json:"method_version_id"`
	Status          string             `json:"status"`
	ExecutionMode   string             `json:"execution_mode"`
	Error           pgtype.Text        `json:"error"`
	CreatedBy       pgtype.Int8        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
	CostCapUsd      pgtype.Numeric     `json:"cost_cap_usd"`
}

type GradingRunItem struct {
	ID                         int64              `json:"id"`
	RunID                      int64              `json:"run_id"`
	AnswerID                   int64              `json:"answer_id"`
	ModelID                    string             `json:"model_id"`
	Provider                   string             `json:"provider"`
	State                      string             `json:"state"`
	Attempts                   int32              `json:"attempts"`
	Error                      pgtype.Text        `json:"error"`
	RecordID                   pgtype.Int8        `json:"record_id"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	RubricVersionID            pgtype.Int8        `json:"rubric_version_id"`
	ReferenceSolutionVersionID pgtype.Int8        `json:"reference_solution_version_id"`
}

type IDRegion struct {
	ID           int64              `json:"id"`
	AssessmentID int64              `json:"assessment_id"`
	X            float32            `json:"x"`
	Y            float32            `json:"y"`
	W            float32            `json:"w"`
	H            float32            `json:"h"`
	Color        string             `json:"color"`
	Padding      float32            `json:"padding"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Kind         string             `json:"kind"`
}

type LlmProvider struct {
	ID                int64              `json:"id"`
	Name              string             `json:"name"`
	Kind              string             `json:"kind"`
	BaseUrl           string             `json:"base_url"`
	ApiKeyCiphertext  []byte             `json:"api_key_ciphertext"`
	ApiKeyHint        string             `json:"api_key_hint"`
	Models            []string           `json:"models"`
	RequestsPerSecond float32            `json:"requests_per_second"`
	Burst             int32              `json:"burst"`
	Enabled           bool               `json:"enabled"`
	LastVerifiedAt    pgtype.Timestamptz `json:"last_verified_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type LoginToken struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	TokenHash  []byte             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type MaskRegion struct {
	ID           int64              `json:"id"`
	AssessmentID int64              `json:"assessment_id"`
	PageScope    string             `json:"page_scope"`
	X            float32            `json:"x"`
	Y            float32            `json:"y"`
	W            float32            `json:"w"`
	H            float32            `json:"h"`
	Color        string             `json:"color"`
	Padding      float32            `json:"padding"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type ModelPricing struct {
	ID               int64              `json:"id"`
	ProviderID       int64              `json:"provider_id"`
	Model            string             `json:"model"`
	InputUsdPerMtok  pgtype.Numeric     `json:"input_usd_per_mtok"`
	OutputUsdPerMtok pgtype.Numeric     `json:"output_usd_per_mtok"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Problem struct {
	ID           int64              `json:"id"`
	AssessmentID int64              `json:"assessment_id"`
	Number       int32              `json:"number"`
	Title        string             `json:"title"`
	Statement    string             `json:"statement"`
	MaxPoints    pgtype.Numeric     `json:"max_points"`
	Position     int32              `json:"position"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ProblemTaAssignment struct {
	ID         int64              `json:"id"`
	ProblemID  int64              `json:"problem_id"`
	UserID     int64              `json:"user_id"`
	AssignedBy pgtype.Int8        `json:"assigned_by"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
}

type PromptTemplateVersion struct {
	ID             int64              `json:"id"`
	Name           string             `json:"name"`
	Version        int32              `json:"version"`
	SystemTemplate string             `json:"system_template"`
	UserTemplate   string             `json:"user_template"`
	CreatedBy      pgtype.Int8        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type PublishBatch struct {
	ID           int64              `json:"id"`
	AssessmentID int64              `json:"assessment_id"`
	Note         string             `json:"note"`
	ResendAll    bool               `json:"resend_all"`
	CreatedBy    pgtype.Int8        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	SupersededAt pgtype.Timestamptz `json:"superseded_at"`
	Attachment   string             `json:"attachment"`
	Zip          bool               `json:"zip"`
}

type PublishItem struct {
	ID                int64              `json:"id"`
	BatchID           int64              `json:"batch_id"`
	StudentID         int64              `json:"student_id"`
	Snapshot          []byte             `json:"snapshot"`
	RecipientEmail    string             `json:"recipient_email"`
	RegradeToken      string             `json:"regrade_token"`
	EmailStatus       string             `json:"email_status"`
	ProviderMessageID pgtype.Text        `json:"provider_message_id"`
	SentAt            pgtype.Timestamptz `json:"sent_at"`
	Error             pgtype.Text        `json:"error"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	EmailGeneration   int32              `json:"email_generation"`
	DeliveryKey       pgtype.UUID        `json:"delivery_key"`
	DeliveryJobID     pgtype.Int8        `json:"delivery_job_id"`
	DeliveryStateAt   pgtype.Timestamptz `json:"delivery_state_at"`
}

type ReferenceSolutionVersion struct {
	ID        int64              `json:"id"`
	ProblemID int64              `json:"problem_id"`
	Version   int32              `json:"version"`
	Content   string             `json:"content"`
	CreatedBy pgtype.Int8        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RegradeRequest struct {
	ID             int64              `json:"id"`
	PublishItemID  pgtype.Int8        `json:"publish_item_id"`
	StudentID      pgtype.Int8        `json:"student_id"`
	AssessmentID   pgtype.Int8        `json:"assessment_id"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
	FromEmail      string             `json:"from_email"`
	SpfVerdict     pgtype.Text        `json:"spf_verdict"`
	DkimVerdict    pgtype.Text        `json:"dkim_verdict"`
	Subject        string             `json:"subject"`
	Body           string             `json:"body"`
	Status         string             `json:"status"`
	ResolverID     pgtype.Int8        `json:"resolver_id"`
	ResolutionNote string             `json:"resolution_note"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	MessageID      pgtype.Text        `json:"message_id"`
	Turn           pgtype.Int4        `json:"turn"`
	AiError        pgtype.Text        `json:"ai_error"`
	Kind           string             `json:"kind"`
	ResultSentAt   pgtype.Timestamptz `json:"result_sent_at"`
}

type RegradeRequestProblem struct {
	ID              int64              `json:"id"`
	RequestID       int64              `json:"request_id"`
	ProblemID       int64              `json:"problem_id"`
	ComplaintText   string             `json:"complaint_text"`
	AiRecordID      pgtype.Int8        `json:"ai_record_id"`
	AiError         pgtype.Text        `json:"ai_error"`
	Verdict         pgtype.Text        `json:"verdict"`
	VerdictNote     string             `json:"verdict_note"`
	VerdictBy       pgtype.Int8        `json:"verdict_by"`
	VerdictAt       pgtype.Timestamptz `json:"verdict_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	AdoptedRecordID pgtype.Int8        `json:"adopted_record_id"`
}

type RegradeRoundMethod struct {
	AssessmentID int64              `json:"assessment_id"`
	Turn         int32              `json:"turn"`
	MethodID     int64              `json:"method_id"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type RubricCriterium struct {
	ID                 int64          `json:"id"`
	RubricVersionID    int64          `json:"rubric_version_id"`
	Position           int32          `json:"position"`
	Description        string         `json:"description"`
	Points             pgtype.Numeric `json:"points"`
	PartialCreditNotes string         `json:"partial_credit_notes"`
}

type RubricVersion struct {
	ID             int64              `json:"id"`
	ProblemID      int64              `json:"problem_id"`
	Version        int32              `json:"version"`
	Notes          string             `json:"notes"`
	ScoreIncrement pgtype.Numeric     `json:"score_increment"`
	CreatedBy      pgtype.Int8        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ScanBatch struct {
	ID           int64              `json:"id"`
	AssessmentID int64              `json:"assessment_id"`
	OcrEnabled   bool               `json:"ocr_enabled"`
	OcrProvider  pgtype.Text        `json:"ocr_provider"`
	OcrModel     pgtype.Text        `json:"ocr_model"`
	SourceRef    pgtype.Text        `json:"source_ref"`
	CreatedBy    pgtype.Int8        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type ScanPage struct {
	ID                  int64              `json:"id"`
	SourceID            int64              `json:"source_id"`
	BatchID             int64              `json:"batch_id"`
	AssessmentID        int64              `json:"assessment_id"`
	PageIndex           int32              `json:"page_index"`
	ImageRef            pgtype.Text        `json:"image_ref"`
	ImageSha256         pgtype.Text        `json:"image_sha256"`
	ImageWidth          pgtype.Int4        `json:"image_width"`
	ImageHeight         pgtype.Int4        `json:"image_height"`
	StudentIDCropRef    pgtype.Text        `json:"student_id_crop_ref"`
	NameCropRef         pgtype.Text        `json:"name_crop_ref"`
	ProblemCropRef      pgtype.Text        `json:"problem_crop_ref"`
	OcrStudentID        pgtype.Text        `json:"ocr_student_id"`
	OcrName             pgtype.Text        `json:"ocr_name"`
	OcrProblem          pgtype.Text        `json:"ocr_problem"`
	OcrStudentIDLegible pgtype.Bool        `json:"ocr_student_id_legible"`
	OcrNameLegible      pgtype.Bool        `json:"ocr_name_legible"`
	OcrProblemLegible   pgtype.Bool        `json:"ocr_problem_legible"`
	OcrEngine           pgtype.Text        `json:"ocr_engine"`
	IdentifiedAt        pgtype.Timestamptz `json:"identified_at"`
	ProposedStudentID   pgtype.Int8        `json:"proposed_student_id"`
	ProposedProblemID   pgtype.Int8        `json:"proposed_problem_id"`
	ProposalSource      pgtype.Text        `json:"proposal_source"`
	AssignedStudentID   pgtype.Int8        `json:"assigned_student_id"`
	AssignedProblemID   pgtype.Int8        `json:"assigned_problem_id"`
	AssignedBy          pgtype.Int8        `json:"assigned_by"`
	AssignedAt          pgtype.Timestamptz `json:"assigned_at"`
	ForcePromote        bool               `json:"force_promote"`
	ParkedReason        pgtype.Text        `json:"parked_reason"`
	ParkedAgainst       pgtype.Int8        `json:"parked_against"`
	DiscardedAt         pgtype.Timestamptz `json:"discarded_at"`
	DiscardReason       pgtype.Text        `json:"discard_reason"`
	SubmissionID        pgtype.Int8        `json:"submission_id"`
	Error               pgtype.Text        `json:"error"`
	Attempts            int32              `json:"attempts"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ParkStudentID       pgtype.Int8        `json:"park_student_id"`
	ParkProblemID       pgtype.Int8        `json:"park_problem_id"`
	TextLossRuns        int32              `json:"text_loss_runs"`
}

type ScanSource struct {
	ID               int64              `json:"id"`
	BatchID          int64              `json:"batch_id"`
	OriginalFilename string             `json:"original_filename"`
	SourceRef        string             `json:"source_ref"`
	SourceSha256     string             `json:"source_sha256"`
	SourceKind       string             `json:"source_kind"`
	PageCount        pgtype.Int4        `json:"page_count"`
	Error            pgtype.Text        `json:"error"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	Token  string             `json:"token"`
	Data   []byte             `json:"data"`
	Expiry pgtype.Timestamptz `json:"expiry"`
}

type SpotCheck struct {
	ID              int64              `json:"id"`
	RunID           int64              `json:"run_id"`
	GradingRecordID int64              `json:"grading_record_id"`
	Verdict         pgtype.Text        `json:"verdict"`
	Note            string             `json:"note"`
	CheckerID       pgtype.Int8        `json:"checker_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CheckedAt       pgtype.Timestamptz `json:"checked_at"`
}

type Student struct {
	ID          int64              `json:"id"`
	StudentID   string             `json:"student_id"`
	Name        string             `json:"name"`
	Email       string             `json:"email"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	WithdrawnAt pgtype.Timestamptz `json:"withdrawn_at"`
}

type Submission struct {
	ID               int64              `json:"id"`
	AssessmentID     int64              `json:"assessment_id"`
	StudentID        int64              `json:"student_id"`
	OriginalFilename string             `json:"original_filename"`
	SourceRef        string             `json:"source_ref"`
	SourceSha256     string             `json:"source_sha256"`
	PageCount        int32              `json:"page_count"`
	UploadedBy       pgtype.Int8        `json:"uploaded_by"`
	UploadedAt       pgtype.Timestamptz `json:"uploaded_at"`
	SupersededBy     pgtype.Int8        `json:"superseded_by"`
	SourceKind       string             `json:"source_kind"`
	ProblemID        pgtype.Int8        `json:"problem_id"`
	RetractedAt      pgtype.Timestamptz `json:"retracted_at"`
}

type UploadQuarantine struct {
	ID                int64              `json:"id"`
	AssessmentID      int64              `json:"assessment_id"`
	OriginalFilename  string             `json:"original_filename"`
	PdfRef            string             `json:"pdf_ref"`
	PdfSha256         string             `json:"pdf_sha256"`
	Reason            string             `json:"reason"`
	UploadedBy        pgtype.Int8        `json:"uploaded_by"`
	UploadedAt        pgtype.Timestamptz `json:"uploaded_at"`
	ResolvedAt        pgtype.Timestamptz `json:"resolved_at"`
	ResolvedStudentID pgtype.Int8        `json:"resolved_student_id"`
}

type User struct {
	ID          int64              `json:"id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	Role        string             `json:"role"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type WaivedRun struct {
	RunID    int64              `json:"run_id"`
	Reason   string             `json:"reason"`
	WaivedBy pgtype.Int8        `json:"waived_by"`
	WaivedAt pgtype.Timestamptz `json:"waived_at"`
}
