// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pricing.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getModelPricing = `-- name: GetModelPricing :one
SELECT id, provider_id, model, input_usd_per_mtok, output_usd_per_mtok, updated_at FROM model_pricing WHERE provider_id = $1 AND model = $2
`

type GetModelPricingParams struct {
	ProviderID int64  `json:"provider_id"`
	Model      string `json:"model"`
}

func (q *Queries) GetModelPricing(ctx context.Context, arg GetModelPricingParams) (ModelPricing, error) {
	row := q.db.QueryRow(ctx, getModelPricing, arg.ProviderID, arg.Model)
	var i ModelPricing
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Model,
		&i.InputUsdPerMtok,
		&i.OutputUsdPerMtok,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllModelPricing = `-- name: ListAllModelPricing :many
SELECT id, provider_id, model, input_usd_per_mtok, output_usd_per_mtok, updated_at FROM model_pricing ORDER BY provider_id, model
`

func (q *Queries) ListAllModelPricing(ctx context.Context) ([]ModelPricing, error) {
	rows, err := q.db.Query(ctx, listAllModelPricing)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelPricing
	for rows.Next() {
		var i ModelPricing
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Model,
			&i.InputUsdPerMtok,
			&i.OutputUsdPerMtok,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelPricing = `-- name: ListModelPricing :many
SELECT id, provider_id, model, input_usd_per_mtok, output_usd_per_mtok, updated_at FROM model_pricing WHERE provider_id = $1 ORDER BY model
`

func (q *Queries) ListModelPricing(ctx context.Context, providerID int64) ([]ModelPricing, error) {
	rows, err := q.db.Query(ctx, listModelPricing, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelPricing
	for rows.Next() {
		var i ModelPricing
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Model,
			&i.InputUsdPerMtok,
			&i.OutputUsdPerMtok,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const monthToDateCost = `-- name: MonthToDateCost :one
SELECT COALESCE(sum(cost_usd), 0)::numeric AS total
FROM grading_records
WHERE source IN ('model', 'regrade_ai')
  AND created_at >= (date_trunc('month', now() AT TIME ZONE 'UTC') AT TIME ZONE 'UTC')
`

// MonthToDateCost sums cost_usd for grading_records created since the start of the
// current UTC month (D36 monthly global cap). NULL cost_usd rows (no pricing at
// insert time) contribute 0, matching "absence is visible, not a fake charge" --
// the caller separately surfaces missing-pricing coverage via ListModelPricing.
// Both run-leaf ('model') AND stricter-AI-regrade ('regrade_ai', migration 0024,
// spec §8) records are real provider spend and must both count toward month-to-date —
// a regrade_ai record's cost is otherwise invisible to the budget gate.
func (q *Queries) MonthToDateCost(ctx context.Context) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, monthToDateCost)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const runCost = `-- name: RunCost :one
SELECT COALESCE(sum(cost_usd), 0)::numeric AS total,
    COALESCE(sum(input_tokens), 0)::bigint AS input_tokens,
    COALESCE(sum(output_tokens), 0)::bigint AS output_tokens
FROM grading_records
WHERE run_id = $1
`

type RunCostRow struct {
	Total        pgtype.Numeric `json:"total"`
	InputTokens  int64          `json:"input_tokens"`
	OutputTokens int64          `json:"output_tokens"`
}

func (q *Queries) RunCost(ctx context.Context, runID pgtype.Int8) (RunCostRow, error) {
	row := q.db.QueryRow(ctx, runCost, runID)
	var i RunCostRow
	err := row.Scan(&i.Total, &i.InputTokens, &i.OutputTokens)
	return i, err
}

const setRunCostCap = `-- name: SetRunCostCap :one
UPDATE grading_runs SET cost_cap_usd = $2 WHERE id = $1 RETURNING id, assessment_id, scope_kind, scope_id, method_version_id, status, execution_mode, error, created_by, created_at, started_at, finished_at, cost_cap_usd
`

type SetRunCostCapParams struct {
	ID         int64          `json:"id"`
	CostCapUsd pgtype.Numeric `json:"cost_cap_usd"`
}

func (q *Queries) SetRunCostCap(ctx context.Context, arg SetRunCostCapParams) (GradingRun, error) {
	row := q.db.QueryRow(ctx, setRunCostCap, arg.ID, arg.CostCapUsd)
	var i GradingRun
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.ScopeKind,
		&i.ScopeID,
		&i.MethodVersionID,
		&i.Status,
		&i.ExecutionMode,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CostCapUsd,
	)
	return i, err
}

const upsertModelPricing = `-- name: UpsertModelPricing :one

INSERT INTO model_pricing (provider_id, model, input_usd_per_mtok, output_usd_per_mtok)
VALUES ($1, $2, $3, $4)
ON CONFLICT (provider_id, model) DO UPDATE
    SET input_usd_per_mtok = EXCLUDED.input_usd_per_mtok,
        output_usd_per_mtok = EXCLUDED.output_usd_per_mtok,
        updated_at = now()
RETURNING id, provider_id, model, input_usd_per_mtok, output_usd_per_mtok, updated_at
`

type UpsertModelPricingParams struct {
	ProviderID       int64          `json:"provider_id"`
	Model            string         `json:"model"`
	InputUsdPerMtok  pgtype.Numeric `json:"input_usd_per_mtok"`
	OutputUsdPerMtok pgtype.Numeric `json:"output_usd_per_mtok"`
}

// Model pricing + spend queries (trust spec §2-3).
func (q *Queries) UpsertModelPricing(ctx context.Context, arg UpsertModelPricingParams) (ModelPricing, error) {
	row := q.db.QueryRow(ctx, upsertModelPricing,
		arg.ProviderID,
		arg.Model,
		arg.InputUsdPerMtok,
		arg.OutputUsdPerMtok,
	)
	var i ModelPricing
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Model,
		&i.InputUsdPerMtok,
		&i.OutputUsdPerMtok,
		&i.UpdatedAt,
	)
	return i, err
}
