// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: problems.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProblemPages = `-- name: CountProblemPages :one
SELECT count(*)
FROM answer_pages ap
JOIN answers a ON a.id = ap.answer_id
WHERE a.problem_id = $1
`

func (q *Queries) CountProblemPages(ctx context.Context, problemID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countProblemPages, problemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProblemRecords = `-- name: CountProblemRecords :one
SELECT count(*)
FROM grading_records gr
JOIN answers a ON a.id = gr.answer_id
WHERE a.problem_id = $1
`

func (q *Queries) CountProblemRecords(ctx context.Context, problemID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countProblemRecords, problemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProblem = `-- name: CreateProblem :one
INSERT INTO problems (assessment_id, number, title, statement, max_points, position)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, assessment_id, number, title, statement, max_points, position, created_at, updated_at
`

type CreateProblemParams struct {
	AssessmentID int64          `json:"assessment_id"`
	Number       int32          `json:"number"`
	Title        string         `json:"title"`
	Statement    string         `json:"statement"`
	MaxPoints    pgtype.Numeric `json:"max_points"`
	Position     int32          `json:"position"`
}

func (q *Queries) CreateProblem(ctx context.Context, arg CreateProblemParams) (Problem, error) {
	row := q.db.QueryRow(ctx, createProblem,
		arg.AssessmentID,
		arg.Number,
		arg.Title,
		arg.Statement,
		arg.MaxPoints,
		arg.Position,
	)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.Number,
		&i.Title,
		&i.Statement,
		&i.MaxPoints,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProblem = `-- name: DeleteProblem :exec
DELETE FROM problems WHERE id = $1
`

func (q *Queries) DeleteProblem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProblem, id)
	return err
}

const getProblem = `-- name: GetProblem :one
SELECT id, assessment_id, number, title, statement, max_points, position, created_at, updated_at FROM problems WHERE id = $1
`

func (q *Queries) GetProblem(ctx context.Context, id int64) (Problem, error) {
	row := q.db.QueryRow(ctx, getProblem, id)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.Number,
		&i.Title,
		&i.Statement,
		&i.MaxPoints,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProblems = `-- name: ListProblems :many
SELECT id, assessment_id, number, title, statement, max_points, position, created_at, updated_at FROM problems WHERE assessment_id = $1 ORDER BY position, number
`

func (q *Queries) ListProblems(ctx context.Context, assessmentID int64) ([]Problem, error) {
	rows, err := q.db.Query(ctx, listProblems, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Problem
	for rows.Next() {
		var i Problem
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.Number,
			&i.Title,
			&i.Statement,
			&i.MaxPoints,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProblem = `-- name: UpdateProblem :one
UPDATE problems
SET number = $2, title = $3, statement = $4, max_points = $5, position = $6, updated_at = now()
WHERE id = $1
RETURNING id, assessment_id, number, title, statement, max_points, position, created_at, updated_at
`

type UpdateProblemParams struct {
	ID        int64          `json:"id"`
	Number    int32          `json:"number"`
	Title     string         `json:"title"`
	Statement string         `json:"statement"`
	MaxPoints pgtype.Numeric `json:"max_points"`
	Position  int32          `json:"position"`
}

func (q *Queries) UpdateProblem(ctx context.Context, arg UpdateProblemParams) (Problem, error) {
	row := q.db.QueryRow(ctx, updateProblem,
		arg.ID,
		arg.Number,
		arg.Title,
		arg.Statement,
		arg.MaxPoints,
		arg.Position,
	)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.Number,
		&i.Title,
		&i.Statement,
		&i.MaxPoints,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
