// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: providers.sql

package db

import (
	"context"
)

const countMethodVersionsUsingProvider = `-- name: CountMethodVersionsUsingProvider :one
SELECT count(*) FROM grading_method_versions WHERE config ->> 'provider' = $1::text
`

func (q *Queries) CountMethodVersionsUsingProvider(ctx context.Context, provider string) (int64, error) {
	row := q.db.QueryRow(ctx, countMethodVersionsUsingProvider, provider)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProviders = `-- name: CountProviders :one
SELECT count(*) FROM llm_providers
`

func (q *Queries) CountProviders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProviders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProvider = `-- name: CreateProvider :one
INSERT INTO llm_providers (name, kind, base_url, api_key_ciphertext, api_key_hint, models, requests_per_second, burst)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, kind, base_url, api_key_ciphertext, api_key_hint, models, requests_per_second, burst, enabled, last_verified_at, created_at, updated_at
`

type CreateProviderParams struct {
	Name              string   `json:"name"`
	Kind              string   `json:"kind"`
	BaseUrl           string   `json:"base_url"`
	ApiKeyCiphertext  []byte   `json:"api_key_ciphertext"`
	ApiKeyHint        string   `json:"api_key_hint"`
	Models            []string `json:"models"`
	RequestsPerSecond float32  `json:"requests_per_second"`
	Burst             int32    `json:"burst"`
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.Name,
		arg.Kind,
		arg.BaseUrl,
		arg.ApiKeyCiphertext,
		arg.ApiKeyHint,
		arg.Models,
		arg.RequestsPerSecond,
		arg.Burst,
	)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.BaseUrl,
		&i.ApiKeyCiphertext,
		&i.ApiKeyHint,
		&i.Models,
		&i.RequestsPerSecond,
		&i.Burst,
		&i.Enabled,
		&i.LastVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProvider = `-- name: DeleteProvider :exec
DELETE FROM llm_providers WHERE id = $1
`

func (q *Queries) DeleteProvider(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProvider, id)
	return err
}

const getProvider = `-- name: GetProvider :one
SELECT id, name, kind, base_url, api_key_ciphertext, api_key_hint, models, requests_per_second, burst, enabled, last_verified_at, created_at, updated_at FROM llm_providers WHERE id = $1
`

func (q *Queries) GetProvider(ctx context.Context, id int64) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, getProvider, id)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.BaseUrl,
		&i.ApiKeyCiphertext,
		&i.ApiKeyHint,
		&i.Models,
		&i.RequestsPerSecond,
		&i.Burst,
		&i.Enabled,
		&i.LastVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderByName = `-- name: GetProviderByName :one
SELECT id, name, kind, base_url, api_key_ciphertext, api_key_hint, models, requests_per_second, burst, enabled, last_verified_at, created_at, updated_at FROM llm_providers WHERE name = $1
`

func (q *Queries) GetProviderByName(ctx context.Context, name string) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, getProviderByName, name)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.BaseUrl,
		&i.ApiKeyCiphertext,
		&i.ApiKeyHint,
		&i.Models,
		&i.RequestsPerSecond,
		&i.Burst,
		&i.Enabled,
		&i.LastVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledProviders = `-- name: ListEnabledProviders :many
SELECT id, name, kind, base_url, api_key_ciphertext, api_key_hint, models, requests_per_second, burst, enabled, last_verified_at, created_at, updated_at FROM llm_providers WHERE enabled ORDER BY name
`

func (q *Queries) ListEnabledProviders(ctx context.Context) ([]LlmProvider, error) {
	rows, err := q.db.Query(ctx, listEnabledProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmProvider
	for rows.Next() {
		var i LlmProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.BaseUrl,
			&i.ApiKeyCiphertext,
			&i.ApiKeyHint,
			&i.Models,
			&i.RequestsPerSecond,
			&i.Burst,
			&i.Enabled,
			&i.LastVerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviders = `-- name: ListProviders :many
SELECT id, name, kind, base_url, api_key_ciphertext, api_key_hint, models, requests_per_second, burst, enabled, last_verified_at, created_at, updated_at FROM llm_providers ORDER BY name
`

func (q *Queries) ListProviders(ctx context.Context) ([]LlmProvider, error) {
	rows, err := q.db.Query(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmProvider
	for rows.Next() {
		var i LlmProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.BaseUrl,
			&i.ApiKeyCiphertext,
			&i.ApiKeyHint,
			&i.Models,
			&i.RequestsPerSecond,
			&i.Burst,
			&i.Enabled,
			&i.LastVerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markProviderVerified = `-- name: MarkProviderVerified :exec
UPDATE llm_providers SET last_verified_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) MarkProviderVerified(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markProviderVerified, id)
	return err
}

const setProviderModels = `-- name: SetProviderModels :exec
UPDATE llm_providers SET models = $2, updated_at = now() WHERE id = $1
`

type SetProviderModelsParams struct {
	ID     int64    `json:"id"`
	Models []string `json:"models"`
}

func (q *Queries) SetProviderModels(ctx context.Context, arg SetProviderModelsParams) error {
	_, err := q.db.Exec(ctx, setProviderModels, arg.ID, arg.Models)
	return err
}

const updateProvider = `-- name: UpdateProvider :one
UPDATE llm_providers
SET base_url = $2,
    api_key_ciphertext = $3,
    api_key_hint = $4,
    models = $5,
    requests_per_second = $6,
    burst = $7,
    enabled = $8,
    updated_at = now()
WHERE id = $1
RETURNING id, name, kind, base_url, api_key_ciphertext, api_key_hint, models, requests_per_second, burst, enabled, last_verified_at, created_at, updated_at
`

type UpdateProviderParams struct {
	ID                int64    `json:"id"`
	BaseUrl           string   `json:"base_url"`
	ApiKeyCiphertext  []byte   `json:"api_key_ciphertext"`
	ApiKeyHint        string   `json:"api_key_hint"`
	Models            []string `json:"models"`
	RequestsPerSecond float32  `json:"requests_per_second"`
	Burst             int32    `json:"burst"`
	Enabled           bool     `json:"enabled"`
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, updateProvider,
		arg.ID,
		arg.BaseUrl,
		arg.ApiKeyCiphertext,
		arg.ApiKeyHint,
		arg.Models,
		arg.RequestsPerSecond,
		arg.Burst,
		arg.Enabled,
	)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.BaseUrl,
		&i.ApiKeyCiphertext,
		&i.ApiKeyHint,
		&i.Models,
		&i.RequestsPerSecond,
		&i.Burst,
		&i.Enabled,
		&i.LastVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
