// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: regrade.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adoptedOverlaysForAssessment = `-- name: AdoptedOverlaysForAssessment :many
SELECT DISTINCT ON (a.id)
    a.id AS answer_id, rp.adopted_record_id, rr.turn, gr.total
FROM regrade_request_problems rp
JOIN regrade_requests rr ON rr.id = rp.request_id
LEFT JOIN publish_items pi ON pi.id = rr.publish_item_id
LEFT JOIN publish_batches pb ON pb.id = pi.batch_id
JOIN answers a ON a.assessment_id = rr.assessment_id
    AND a.student_id = rr.student_id AND a.problem_id = rp.problem_id
JOIN grading_records gr ON gr.id = rp.adopted_record_id
WHERE rr.assessment_id = $1 AND rp.verdict = 'regraded' AND rp.adopted_record_id IS NOT NULL
ORDER BY a.id, (pb.superseded_at IS NOT NULL), rp.verdict_at DESC NULLS LAST, rr.turn DESC, rp.id DESC
`

type AdoptedOverlaysForAssessmentRow struct {
	AnswerID        int64          `json:"answer_id"`
	AdoptedRecordID pgtype.Int8    `json:"adopted_record_id"`
	Turn            pgtype.Int4    `json:"turn"`
	Total           pgtype.Numeric `json:"total"`
}

// AdoptedOverlaysForAssessment returns, per answer, the EFFECTIVE adopted record —
// the regrade overlay stack collapsed to its top. Resolution matches ExportRows'
// canonical LATERAL (regrade-round correctness fix): live publish chain first, then
// most-recently adjudicated, then turn/id; and only 'regraded' verdicts' adoptions
// count. Joined by consumers (totals/export) as the effective-grade override of round 0.
func (q *Queries) AdoptedOverlaysForAssessment(ctx context.Context, assessmentID pgtype.Int8) ([]AdoptedOverlaysForAssessmentRow, error) {
	rows, err := q.db.Query(ctx, adoptedOverlaysForAssessment, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdoptedOverlaysForAssessmentRow
	for rows.Next() {
		var i AdoptedOverlaysForAssessmentRow
		if err := rows.Scan(
			&i.AnswerID,
			&i.AdoptedRecordID,
			&i.Turn,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const assignProblemTA = `-- name: AssignProblemTA :one
INSERT INTO problem_ta_assignments (problem_id, user_id, assigned_by)
VALUES ($1, $2, $3)
ON CONFLICT (problem_id) DO UPDATE
    SET user_id = EXCLUDED.user_id, assigned_by = EXCLUDED.assigned_by, assigned_at = now()
RETURNING id, problem_id, user_id, assigned_by, assigned_at
`

type AssignProblemTAParams struct {
	ProblemID  int64       `json:"problem_id"`
	UserID     int64       `json:"user_id"`
	AssignedBy pgtype.Int8 `json:"assigned_by"`
}

// At most one TA per problem (UNIQUE(problem_id), migration 0025, spec §6 D60):
// assigning a new TA to an already-assigned problem must replace the row, not error
// -- the picker UI is "set the TA for this problem", not "add another assignment".
func (q *Queries) AssignProblemTA(ctx context.Context, arg AssignProblemTAParams) (ProblemTaAssignment, error) {
	row := q.db.QueryRow(ctx, assignProblemTA, arg.ProblemID, arg.UserID, arg.AssignedBy)
	var i ProblemTaAssignment
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.UserID,
		&i.AssignedBy,
		&i.AssignedAt,
	)
	return i, err
}

const consumedTokenExists = `-- name: ConsumedTokenExists :one
SELECT EXISTS (
    SELECT 1 FROM regrade_requests
    WHERE publish_item_id = $1 AND turn = $2 AND kind IN ('filed', 'handed_off')
) AS exists
`

type ConsumedTokenExistsParams struct {
	PublishItemID pgtype.Int8 `json:"publish_item_id"`
	Turn          pgtype.Int4 `json:"turn"`
}

// true iff this (publish_item_id, turn) token has already been CONSUMED -- i.e. a row
// exists that filed against it (kind='filed') OR that already fired the final-turn
// handoff (kind='handed_off'). This is the consumed-token pre-check the webhook uses
// (spec §4 D57): once a handoff row exists, MarkRequestHandedOff has flipped it OUT of
// the partial unique index's WHERE kind='filed', freeing the raw index slot -- so a
// FiledRequestExists-only check would wrongly let a SECOND reply to the MAX+1 token file
// again. This query closes that gap by treating both consuming kinds as consumed. The
// partial unique index still structurally guarantees at most one 'filed' row per slot
// for the racing case; this read complements it for the handoff-already-happened case.
func (q *Queries) ConsumedTokenExists(ctx context.Context, arg ConsumedTokenExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, consumedTokenExists, arg.PublishItemID, arg.Turn)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const contestedAnswerForSubItem = `-- name: ContestedAnswerForSubItem :many
SELECT a.id AS answer_id, a.problem_id,
    egr.id AS record_id, egr.provider, egr.model_id, egr.method_version_id,
    egr.rubric_version_id, egr.reference_solution_version_id, egr.prompt_template_version_id,
    egr.criterion_scores, egr.comment AS original_comment
FROM answers a
LEFT JOIN LATERAL (
    SELECT rp.adopted_record_id AS record_id
    FROM regrade_request_problems rp
    JOIN regrade_requests rr ON rr.id = rp.request_id
    LEFT JOIN publish_items pi ON pi.id = rr.publish_item_id
    LEFT JOIN publish_batches pb ON pb.id = pi.batch_id
    WHERE rr.assessment_id = a.assessment_id
      AND rr.student_id = a.student_id
      AND rp.problem_id = a.problem_id
      AND rp.verdict = 'regraded'
      AND rp.adopted_record_id IS NOT NULL
      AND rp.id <> $1
    ORDER BY (pb.superseded_at IS NOT NULL), rp.verdict_at DESC NULLS LAST, rr.turn DESC, rp.id DESC
    LIMIT 1
) overlay ON true
JOIN grading_records egr ON egr.id = COALESCE(overlay.record_id, a.official_record_id)
WHERE a.assessment_id = $2
  AND a.student_id = $3
  AND a.problem_id = $4
ORDER BY a.problem_id
`

type ContestedAnswerForSubItemParams struct {
	ExcludeSubItemID int64 `json:"exclude_sub_item_id"`
	AssessmentID     int64 `json:"assessment_id"`
	StudentID        int64 `json:"student_id"`
	ProblemID        int64 `json:"problem_id"`
}

type ContestedAnswerForSubItemRow struct {
	AnswerID                   int64       `json:"answer_id"`
	ProblemID                  int64       `json:"problem_id"`
	RecordID                   int64       `json:"record_id"`
	Provider                   pgtype.Text `json:"provider"`
	ModelID                    pgtype.Text `json:"model_id"`
	MethodVersionID            pgtype.Int8 `json:"method_version_id"`
	RubricVersionID            int64       `json:"rubric_version_id"`
	ReferenceSolutionVersionID pgtype.Int8 `json:"reference_solution_version_id"`
	PromptTemplateVersionID    pgtype.Int8 `json:"prompt_template_version_id"`
	CriterionScores            []byte      `json:"criterion_scores"`
	OriginalComment            string      `json:"original_comment"`
}

// The single contested answer a sub-item's AI re-grade re-examines (spec §8, per-sub-item
// re-scope): the student's answer for THAT problem, with the CURRENT EFFECTIVE record's
// pinned method/rubric/refsol/prompt and scores so the re-grade is apples-to-apples
// (D53). Returns 0 or 1 row (a student has at most one answer per problem); :many keeps
// the caller's "empty ⇒ nothing to re-examine, fail open" shape.
//
// EFFECTIVE, not round-0 official (regrade-round correctness fix): a turn-N re-grade
// must be briefed against the grade the student is actually contesting — round 0
// overlaid by the latest ADOPTED record from a prior turn — not round 0 itself, or a
// turn-2 re-grade would silently re-examine (and could lower) a grade turn 1 already
// raised. The overlay LATERAL matches ExportRows' canonical resolver, plus an exclude
// clause: the sub-item being adjudicated NOW is skipped so it never briefs against its
// own (possibly re-run) prior adoption. The effective record is then joined on
// COALESCE(overlay.record_id, a.official_record_id); no effective record ⇒ no row.
func (q *Queries) ContestedAnswerForSubItem(ctx context.Context, arg ContestedAnswerForSubItemParams) ([]ContestedAnswerForSubItemRow, error) {
	rows, err := q.db.Query(ctx, contestedAnswerForSubItem,
		arg.ExcludeSubItemID,
		arg.AssessmentID,
		arg.StudentID,
		arg.ProblemID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContestedAnswerForSubItemRow
	for rows.Next() {
		var i ContestedAnswerForSubItemRow
		if err := rows.Scan(
			&i.AnswerID,
			&i.ProblemID,
			&i.RecordID,
			&i.Provider,
			&i.ModelID,
			&i.MethodVersionID,
			&i.RubricVersionID,
			&i.ReferenceSolutionVersionID,
			&i.PromptTemplateVersionID,
			&i.CriterionScores,
			&i.OriginalComment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countRegradeRequests = `-- name: CountRegradeRequests :one
SELECT count(*)
FROM regrade_requests rr
LEFT JOIN students st ON st.id = rr.student_id
WHERE ($1::text IS NULL OR rr.status = $1)
  AND ($2::bigint IS NULL OR rr.assessment_id = $2)
  AND ($3::text IS NULL OR rr.kind = $3)
  AND ($4::text IS NULL OR st.student_id ILIKE $4)
  AND ($5::bool IS NULL
       OR (rr.status IN ('received', 'under_review')) = $5)
  AND ($6::bool IS NULL
       OR (rr.kind = 'filed'
           AND rr.status IN ('resolved_upheld', 'resolved_regraded')
           AND rr.result_sent_at IS NULL) = $6)
`

type CountRegradeRequestsParams struct {
	Status                pgtype.Text `json:"status"`
	AssessmentID          pgtype.Int8 `json:"assessment_id"`
	Kind                  pgtype.Text `json:"kind"`
	StudentPrefix         pgtype.Text `json:"student_prefix"`
	OnlyOpen              pgtype.Bool `json:"only_open"`
	OnlyUndeliveredResult pgtype.Bool `json:"only_undelivered_result"`
}

func (q *Queries) CountRegradeRequests(ctx context.Context, arg CountRegradeRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRegradeRequests,
		arg.Status,
		arg.AssessmentID,
		arg.Kind,
		arg.StudentPrefix,
		arg.OnlyOpen,
		arg.OnlyUndeliveredResult,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequestProblems = `-- name: CountRequestProblems :one
SELECT count(*) FROM regrade_request_problems WHERE request_id = $1
`

// Companion to CountUnverdictedProblems: a request with ZERO sub-items is not
// "all verdicted" in any meaningful sense (nothing to send a result about) -- the
// store-level AllProblemsVerdicted helper combines both counts so that edge case is
// explicit rather than accidentally true (0 unverdicted out of 0 total).
func (q *Queries) CountRequestProblems(ctx context.Context, requestID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countRequestProblems, requestID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSkippedAIRegradeSubItems = `-- name: CountSkippedAIRegradeSubItems :one
SELECT count(*)
FROM regrade_request_problems rrp
JOIN regrade_requests rr ON rr.id = rrp.request_id
WHERE rr.assessment_id = $1
  AND rr.kind = 'filed'
  AND rr.status IN ('received', 'under_review')
  AND rrp.ai_record_id IS NOT NULL
`

// Sub-items the "AI re-grade all" batch skips (spec §8): those on open filed requests
// that ALREADY carry an AI record. Reported alongside the enqueued count so a TA sees
// why fewer jobs ran than there are contested problems.
func (q *Queries) CountSkippedAIRegradeSubItems(ctx context.Context, assessmentID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countSkippedAIRegradeSubItems, assessmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnverdictedProblems = `-- name: CountUnverdictedProblems :one
SELECT count(*) FROM regrade_request_problems WHERE request_id = $1 AND verdict IS NULL
`

// Backs AllProblemsVerdicted(requestID): the send-result gate (spec §5) must 409 until
// EVERY sub-item on the request has a verdict. Uses the partial index
// regrade_request_problems_unverdicted_idx (migration 0025, WHERE verdict IS NULL).
func (q *Queries) CountUnverdictedProblems(ctx context.Context, requestID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUnverdictedProblems, requestID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getProblemTA = `-- name: GetProblemTA :one
SELECT id, problem_id, user_id, assigned_by, assigned_at FROM problem_ta_assignments WHERE problem_id = $1
`

func (q *Queries) GetProblemTA(ctx context.Context, problemID int64) (ProblemTaAssignment, error) {
	row := q.db.QueryRow(ctx, getProblemTA, problemID)
	var i ProblemTaAssignment
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.UserID,
		&i.AssignedBy,
		&i.AssignedAt,
	)
	return i, err
}

const getRegradeRequest = `-- name: GetRegradeRequest :one
SELECT id, publish_item_id, student_id, assessment_id, received_at, from_email, spf_verdict, dkim_verdict, subject, body, status, resolver_id, resolution_note, resolved_at, created_at, message_id, turn, ai_error, kind, result_sent_at FROM regrade_requests WHERE id = $1
`

func (q *Queries) GetRegradeRequest(ctx context.Context, id int64) (RegradeRequest, error) {
	row := q.db.QueryRow(ctx, getRegradeRequest, id)
	var i RegradeRequest
	err := row.Scan(
		&i.ID,
		&i.PublishItemID,
		&i.StudentID,
		&i.AssessmentID,
		&i.ReceivedAt,
		&i.FromEmail,
		&i.SpfVerdict,
		&i.DkimVerdict,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.ResolverID,
		&i.ResolutionNote,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.MessageID,
		&i.Turn,
		&i.AiError,
		&i.Kind,
		&i.ResultSentAt,
	)
	return i, err
}

const getRegradeRoundMethod = `-- name: GetRegradeRoundMethod :one
SELECT assessment_id, turn, method_id, updated_at FROM regrade_round_methods WHERE assessment_id = $1 AND turn = $2
`

type GetRegradeRoundMethodParams struct {
	AssessmentID int64 `json:"assessment_id"`
	Turn         int32 `json:"turn"`
}

func (q *Queries) GetRegradeRoundMethod(ctx context.Context, arg GetRegradeRoundMethodParams) (RegradeRoundMethod, error) {
	row := q.db.QueryRow(ctx, getRegradeRoundMethod, arg.AssessmentID, arg.Turn)
	var i RegradeRoundMethod
	err := row.Scan(
		&i.AssessmentID,
		&i.Turn,
		&i.MethodID,
		&i.UpdatedAt,
	)
	return i, err
}

const getRequestProblem = `-- name: GetRequestProblem :one
SELECT id, request_id, problem_id, complaint_text, ai_record_id, ai_error, verdict, verdict_note, verdict_by, verdict_at, created_at, adopted_record_id FROM regrade_request_problems WHERE id = $1
`

func (q *Queries) GetRequestProblem(ctx context.Context, id int64) (RegradeRequestProblem, error) {
	row := q.db.QueryRow(ctx, getRequestProblem, id)
	var i RegradeRequestProblem
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ProblemID,
		&i.ComplaintText,
		&i.AiRecordID,
		&i.AiError,
		&i.Verdict,
		&i.VerdictNote,
		&i.VerdictBy,
		&i.VerdictAt,
		&i.CreatedAt,
		&i.AdoptedRecordID,
	)
	return i, err
}

const insertRegradeAIRecord = `-- name: InsertRegradeAIRecord :one
INSERT INTO grading_records (
    answer_id, source, provider, model_id, method_version_id,
    rubric_version_id, reference_solution_version_id, prompt_template_version_id,
    graded_image_shas, criterion_scores, total, comment, transcription, confidence,
    adjustments, raw_output, input_tokens, output_tokens, cost_usd, temperature, policy
)
VALUES ($1, 'regrade_ai', $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20)
RETURNING id, answer_id, run_id, source, provider, model_id, method_version_id, rubric_version_id, reference_solution_version_id, prompt_template_version_id, graded_image_shas, criterion_scores, total, comment, transcription, confidence, adjustments, raw_output, input_tokens, output_tokens, cost_usd, temperature, created_by, created_at, policy
`

type InsertRegradeAIRecordParams struct {
	AnswerID                   int64          `json:"answer_id"`
	Provider                   pgtype.Text    `json:"provider"`
	ModelID                    pgtype.Text    `json:"model_id"`
	MethodVersionID            pgtype.Int8    `json:"method_version_id"`
	RubricVersionID            int64          `json:"rubric_version_id"`
	ReferenceSolutionVersionID pgtype.Int8    `json:"reference_solution_version_id"`
	PromptTemplateVersionID    pgtype.Int8    `json:"prompt_template_version_id"`
	GradedImageShas            []string       `json:"graded_image_shas"`
	CriterionScores            []byte         `json:"criterion_scores"`
	Total                      pgtype.Numeric `json:"total"`
	Comment                    string         `json:"comment"`
	Transcription              pgtype.Text    `json:"transcription"`
	Confidence                 pgtype.Text    `json:"confidence"`
	Adjustments                []byte         `json:"adjustments"`
	RawOutput                  []byte         `json:"raw_output"`
	InputTokens                pgtype.Int4    `json:"input_tokens"`
	OutputTokens               pgtype.Int4    `json:"output_tokens"`
	CostUsd                    pgtype.Numeric `json:"cost_usd"`
	Temperature                pgtype.Float4  `json:"temperature"`
	Policy                     pgtype.Text    `json:"policy"`
}

// The stricter AI re-grade result (spec §8 v1, D50 -- unaffected by the v2 schema
// change: this inserts into grading_records, not regrade_requests, so migration 0025
// doesn't touch it). An append-only grading_records row with source='regrade_ai' and
// a baked-in policy (regrade_strict). run_id is NULL (this is a single-leaf, on-demand
// job, not a run leaf) and there is no created_by (machine-authored -- migration 0024
// widens grading_records_check to admit that). model_id / method / rubric / refsol /
// prompt are pinned from the CONTESTED official record so the comparison stays
// apples-to-apples (D53). NEVER auto-official: the caller links it via
// SetProblemAIRecord (v2: one grading_records row per sub-item, spec §5) and the TA
// walks the normal path.
func (q *Queries) InsertRegradeAIRecord(ctx context.Context, arg InsertRegradeAIRecordParams) (GradingRecord, error) {
	row := q.db.QueryRow(ctx, insertRegradeAIRecord,
		arg.AnswerID,
		arg.Provider,
		arg.ModelID,
		arg.MethodVersionID,
		arg.RubricVersionID,
		arg.ReferenceSolutionVersionID,
		arg.PromptTemplateVersionID,
		arg.GradedImageShas,
		arg.CriterionScores,
		arg.Total,
		arg.Comment,
		arg.Transcription,
		arg.Confidence,
		arg.Adjustments,
		arg.RawOutput,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostUsd,
		arg.Temperature,
		arg.Policy,
	)
	var i GradingRecord
	err := row.Scan(
		&i.ID,
		&i.AnswerID,
		&i.RunID,
		&i.Source,
		&i.Provider,
		&i.ModelID,
		&i.MethodVersionID,
		&i.RubricVersionID,
		&i.ReferenceSolutionVersionID,
		&i.PromptTemplateVersionID,
		&i.GradedImageShas,
		&i.CriterionScores,
		&i.Total,
		&i.Comment,
		&i.Transcription,
		&i.Confidence,
		&i.Adjustments,
		&i.RawOutput,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CostUsd,
		&i.Temperature,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Policy,
	)
	return i, err
}

const insertRegradeRequestV2 = `-- name: InsertRegradeRequestV2 :one

INSERT INTO regrade_requests (
    publish_item_id, student_id, assessment_id, from_email,
    spf_verdict, dkim_verdict, subject, body, status, message_id,
    kind, turn
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, publish_item_id, student_id, assessment_id, received_at, from_email, spf_verdict, dkim_verdict, subject, body, status, resolver_id, resolution_note, resolved_at, created_at, message_id, turn, ai_error, kind, result_sent_at
`

type InsertRegradeRequestV2Params struct {
	PublishItemID pgtype.Int8 `json:"publish_item_id"`
	StudentID     pgtype.Int8 `json:"student_id"`
	AssessmentID  pgtype.Int8 `json:"assessment_id"`
	FromEmail     string      `json:"from_email"`
	SpfVerdict    pgtype.Text `json:"spf_verdict"`
	DkimVerdict   pgtype.Text `json:"dkim_verdict"`
	Subject       string      `json:"subject"`
	Body          string      `json:"body"`
	Status        string      `json:"status"`
	MessageID     pgtype.Text `json:"message_id"`
	Kind          string      `json:"kind"`
	Turn          pgtype.Int4 `json:"turn"`
}

// Regrade v2 (design doc 2026-07-03-regrade-v2-design.md §9, task W1): one request row
// per inbound email (kind filed|addendum|unparsed|handed_off), per-problem sub-items in
// regrade_request_problems, per-problem TA assignment in problem_ta_assignments. The v1
// single problem_id/ai_record_id/escalated request-level columns are gone (migration
// 0025) -- REPLACES v1's per-email-single-problem model, not additive.
// message_id is the provider's per-delivery id (F1 idempotency key, unchanged from v1,
// migration 0020): a partial unique index rejects a second insert carrying the same
// non-empty message_id. kind/turn are set by the caller (the parser/webhook path):
// turn NULL for rows whose token never parsed or that carry no turn concept
// (kind='addendum' rows still carry the turn of the token they replied to). The
// partial unique index on (publish_item_id, turn) WHERE kind='filed' (migration 0025,
// D57) is the structural race-killer: a second concurrent INSERT ... kind='filed' for
// the same (item, turn) fails as a unique violation, which the caller (IsUniqueViolation)
// maps to "re-record this reply as an addendum instead", not a hard error.
func (q *Queries) InsertRegradeRequestV2(ctx context.Context, arg InsertRegradeRequestV2Params) (RegradeRequest, error) {
	row := q.db.QueryRow(ctx, insertRegradeRequestV2,
		arg.PublishItemID,
		arg.StudentID,
		arg.AssessmentID,
		arg.FromEmail,
		arg.SpfVerdict,
		arg.DkimVerdict,
		arg.Subject,
		arg.Body,
		arg.Status,
		arg.MessageID,
		arg.Kind,
		arg.Turn,
	)
	var i RegradeRequest
	err := row.Scan(
		&i.ID,
		&i.PublishItemID,
		&i.StudentID,
		&i.AssessmentID,
		&i.ReceivedAt,
		&i.FromEmail,
		&i.SpfVerdict,
		&i.DkimVerdict,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.ResolverID,
		&i.ResolutionNote,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.MessageID,
		&i.Turn,
		&i.AiError,
		&i.Kind,
		&i.ResultSentAt,
	)
	return i, err
}

const insertRequestProblem = `-- name: InsertRequestProblem :one
INSERT INTO regrade_request_problems (request_id, problem_id, complaint_text)
VALUES ($1, $2, $3)
RETURNING id, request_id, problem_id, complaint_text, ai_record_id, ai_error, verdict, verdict_note, verdict_by, verdict_at, created_at, adopted_record_id
`

type InsertRequestProblemParams struct {
	RequestID     int64  `json:"request_id"`
	ProblemID     int64  `json:"problem_id"`
	ComplaintText string `json:"complaint_text"`
}

// One sub-item per contested problem (spec §5 D59). UNIQUE(request_id, problem_id)
// guards the TA escape-hatch add/correct path (§5) from creating a second sub-item
// for a problem already on the request.
func (q *Queries) InsertRequestProblem(ctx context.Context, arg InsertRequestProblemParams) (RegradeRequestProblem, error) {
	row := q.db.QueryRow(ctx, insertRequestProblem, arg.RequestID, arg.ProblemID, arg.ComplaintText)
	var i RegradeRequestProblem
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ProblemID,
		&i.ComplaintText,
		&i.AiRecordID,
		&i.AiError,
		&i.Verdict,
		&i.VerdictNote,
		&i.VerdictBy,
		&i.VerdictAt,
		&i.CreatedAt,
		&i.AdoptedRecordID,
	)
	return i, err
}

const listEligibleAIRegradeSubItems = `-- name: ListEligibleAIRegradeSubItems :many
SELECT rrp.id AS sub_item_id, rrp.problem_id,
    gr.provider AS provider, gr.model_id AS model_id
FROM regrade_request_problems rrp
JOIN regrade_requests rr ON rr.id = rrp.request_id
LEFT JOIN answers a ON a.assessment_id = rr.assessment_id AND a.student_id = rr.student_id
    AND a.problem_id = rrp.problem_id
LEFT JOIN grading_records gr ON gr.id = a.official_record_id
WHERE rr.assessment_id = $1
  AND rr.kind = 'filed'
  AND rr.status IN ('received', 'under_review')
  AND rrp.ai_record_id IS NULL
ORDER BY rrp.id
`

type ListEligibleAIRegradeSubItemsRow struct {
	SubItemID int64       `json:"sub_item_id"`
	ProblemID int64       `json:"problem_id"`
	Provider  pgtype.Text `json:"provider"`
	ModelID   pgtype.Text `json:"model_id"`
}

// The "AI re-grade all" enqueue set, re-scoped to SUB-ITEMS (spec §8): every contested
// problem of an OPEN FILED request in the assessment that has no AI record yet, paired
// with the contested official record's provider/model for the cost estimate. A sub-item
// with no official answer to re-examine is still enumerable but drops out of the pricing
// (LEFT JOIN leaves provider/model NULL) -- it fails open at execution time with a
// terminal ai_error, same posture as the single-sub-item path.
func (q *Queries) ListEligibleAIRegradeSubItems(ctx context.Context, assessmentID pgtype.Int8) ([]ListEligibleAIRegradeSubItemsRow, error) {
	rows, err := q.db.Query(ctx, listEligibleAIRegradeSubItems, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEligibleAIRegradeSubItemsRow
	for rows.Next() {
		var i ListEligibleAIRegradeSubItemsRow
		if err := rows.Scan(
			&i.SubItemID,
			&i.ProblemID,
			&i.Provider,
			&i.ModelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegradeRequests = `-- name: ListRegradeRequests :many
SELECT rr.id, rr.publish_item_id, rr.student_id, rr.assessment_id, rr.received_at, rr.from_email, rr.spf_verdict, rr.dkim_verdict, rr.subject, rr.body, rr.status, rr.resolver_id, rr.resolution_note, rr.resolved_at, rr.created_at, rr.message_id, rr.turn, rr.ai_error, rr.kind, rr.result_sent_at, st.student_id AS student_external_id, st.name AS student_name,
    (st.withdrawn_at IS NOT NULL)::bool AS student_withdrawn,
    a.name AS assessment_name
FROM regrade_requests rr
LEFT JOIN students st ON st.id = rr.student_id
LEFT JOIN assessments a ON a.id = rr.assessment_id
WHERE ($1::text IS NULL OR rr.status = $1)
  AND ($2::bigint IS NULL OR rr.assessment_id = $2)
  AND ($3::text IS NULL OR rr.kind = $3)
  AND ($4::text IS NULL OR st.student_id ILIKE $4)
  AND ($5::bool IS NULL
       OR (rr.status IN ('received', 'under_review')) = $5)
  AND ($6::bool IS NULL
       OR (rr.kind = 'filed'
           AND rr.status IN ('resolved_upheld', 'resolved_regraded')
           AND rr.result_sent_at IS NULL) = $6)
ORDER BY rr.id DESC
LIMIT $8 OFFSET $7
`

type ListRegradeRequestsParams struct {
	Status                pgtype.Text `json:"status"`
	AssessmentID          pgtype.Int8 `json:"assessment_id"`
	Kind                  pgtype.Text `json:"kind"`
	StudentPrefix         pgtype.Text `json:"student_prefix"`
	OnlyOpen              pgtype.Bool `json:"only_open"`
	OnlyUndeliveredResult pgtype.Bool `json:"only_undelivered_result"`
	RowOffset             int32       `json:"row_offset"`
	RowLimit              int32       `json:"row_limit"`
}

type ListRegradeRequestsRow struct {
	ID                int64              `json:"id"`
	PublishItemID     pgtype.Int8        `json:"publish_item_id"`
	StudentID         pgtype.Int8        `json:"student_id"`
	AssessmentID      pgtype.Int8        `json:"assessment_id"`
	ReceivedAt        pgtype.Timestamptz `json:"received_at"`
	FromEmail         string             `json:"from_email"`
	SpfVerdict        pgtype.Text        `json:"spf_verdict"`
	DkimVerdict       pgtype.Text        `json:"dkim_verdict"`
	Subject           string             `json:"subject"`
	Body              string             `json:"body"`
	Status            string             `json:"status"`
	ResolverID        pgtype.Int8        `json:"resolver_id"`
	ResolutionNote    string             `json:"resolution_note"`
	ResolvedAt        pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	MessageID         pgtype.Text        `json:"message_id"`
	Turn              pgtype.Int4        `json:"turn"`
	AiError           pgtype.Text        `json:"ai_error"`
	Kind              string             `json:"kind"`
	ResultSentAt      pgtype.Timestamptz `json:"result_sent_at"`
	StudentExternalID pgtype.Text        `json:"student_external_id"`
	StudentName       pgtype.Text        `json:"student_name"`
	StudentWithdrawn  bool               `json:"student_withdrawn"`
	AssessmentName    pgtype.Text        `json:"assessment_name"`
}

// ListRegradeRequests / CountRegradeRequests share one WHERE: the queue page and
// its pager total must always agree. student_prefix is a pre-escaped ILIKE
// pattern (the store wrapper escapes \ % _ and appends %) matching the external
// student ID; rows with no linked student (NULL FK) never match a student search.
// student_withdrawn (roster-lifecycle plan 2026-07-10): withdrawn students keep
// their regrade channel (停修 rights preserved), but the queue flags them so a
// TA sees the status while adjudicating. False for rows with no linked student.
//
// Status-GROUP filters (HCI audit, regrades-list correctness): the UI's default
// "Actionable" queue is kind=filed AND an open status — a compound the single-value
// status param can't express, which used to force fetch-unfiltered-narrow-client-side
// (empty pages + lying totals once >1 page existed). Both nargs are true-or-NULL:
//
//	only_open: status IN (received, under_review). Combine with kind as needed.
//	only_undelivered_result: the resolved-but-never-delivered recovery set
//	  (migration 0026) — kind='filed' is INSIDE the predicate because a reminded
//	  unparsed row is also resolved_upheld with result_sent_at NULL, yet no result
//	  email was ever owed there.
func (q *Queries) ListRegradeRequests(ctx context.Context, arg ListRegradeRequestsParams) ([]ListRegradeRequestsRow, error) {
	rows, err := q.db.Query(ctx, listRegradeRequests,
		arg.Status,
		arg.AssessmentID,
		arg.Kind,
		arg.StudentPrefix,
		arg.OnlyOpen,
		arg.OnlyUndeliveredResult,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRegradeRequestsRow
	for rows.Next() {
		var i ListRegradeRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublishItemID,
			&i.StudentID,
			&i.AssessmentID,
			&i.ReceivedAt,
			&i.FromEmail,
			&i.SpfVerdict,
			&i.DkimVerdict,
			&i.Subject,
			&i.Body,
			&i.Status,
			&i.ResolverID,
			&i.ResolutionNote,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.MessageID,
			&i.Turn,
			&i.AiError,
			&i.Kind,
			&i.ResultSentAt,
			&i.StudentExternalID,
			&i.StudentName,
			&i.StudentWithdrawn,
			&i.AssessmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegradeRoundMethods = `-- name: ListRegradeRoundMethods :many
SELECT assessment_id, turn, method_id, updated_at FROM regrade_round_methods WHERE assessment_id = $1 ORDER BY turn
`

func (q *Queries) ListRegradeRoundMethods(ctx context.Context, assessmentID int64) ([]RegradeRoundMethod, error) {
	rows, err := q.db.Query(ctx, listRegradeRoundMethods, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegradeRoundMethod
	for rows.Next() {
		var i RegradeRoundMethod
		if err := rows.Scan(
			&i.AssessmentID,
			&i.Turn,
			&i.MethodID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestProblems = `-- name: ListRequestProblems :many
SELECT id, request_id, problem_id, complaint_text, ai_record_id, ai_error, verdict, verdict_note, verdict_by, verdict_at, created_at, adopted_record_id FROM regrade_request_problems WHERE request_id = $1 ORDER BY problem_id
`

func (q *Queries) ListRequestProblems(ctx context.Context, requestID int64) ([]RegradeRequestProblem, error) {
	rows, err := q.db.Query(ctx, listRequestProblems, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegradeRequestProblem
	for rows.Next() {
		var i RegradeRequestProblem
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.ProblemID,
			&i.ComplaintText,
			&i.AiRecordID,
			&i.AiError,
			&i.Verdict,
			&i.VerdictNote,
			&i.VerdictBy,
			&i.VerdictAt,
			&i.CreatedAt,
			&i.AdoptedRecordID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTAAssignments = `-- name: ListTAAssignments :many
SELECT p.id AS problem_id, p.number AS problem_number,
    pta.user_id, pta.assigned_by, pta.assigned_at
FROM problems p
LEFT JOIN problem_ta_assignments pta ON pta.problem_id = p.id
WHERE p.assessment_id = $1
ORDER BY p.position, p.number
`

type ListTAAssignmentsRow struct {
	ProblemID     int64              `json:"problem_id"`
	ProblemNumber int32              `json:"problem_number"`
	UserID        pgtype.Int8        `json:"user_id"`
	AssignedBy    pgtype.Int8        `json:"assigned_by"`
	AssignedAt    pgtype.Timestamptz `json:"assigned_at"`
}

// Every problem in an assessment with its TA assignment, if any (spec §6: "assignment
// state visible on regrade rows", publish preview's unassigned-problem warning). LEFT
// JOIN so unassigned problems still appear (assigned columns NULL).
func (q *Queries) ListTAAssignments(ctx context.Context, assessmentID int64) ([]ListTAAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listTAAssignments, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTAAssignmentsRow
	for rows.Next() {
		var i ListTAAssignmentsRow
		if err := rows.Scan(
			&i.ProblemID,
			&i.ProblemNumber,
			&i.UserID,
			&i.AssignedBy,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRegradeRequest = `-- name: LockRegradeRequest :one
SELECT status, kind FROM regrade_requests WHERE id = $1 FOR UPDATE
`

type LockRegradeRequestRow struct {
	Status string `json:"status"`
	Kind   string `json:"kind"`
}

// LockRegradeRequest serializes side effects that must happen at most once per
// request but cannot be performed inside SQL (currently the reminder email send).
// The caller must use this through transaction-bound Queries.
func (q *Queries) LockRegradeRequest(ctx context.Context, id int64) (LockRegradeRequestRow, error) {
	row := q.db.QueryRow(ctx, lockRegradeRequest, id)
	var i LockRegradeRequestRow
	err := row.Scan(&i.Status, &i.Kind)
	return i, err
}

const markRequestHandedOff = `-- name: MarkRequestHandedOff :one
UPDATE regrade_requests SET kind = 'handed_off' WHERE id = $1 RETURNING id, publish_item_id, student_id, assessment_id, received_at, from_email, spf_verdict, dkim_verdict, subject, body, status, resolver_id, resolution_note, resolved_at, created_at, message_id, turn, ai_error, kind, result_sent_at
`

// Consuming the final-turn (handoff) token (spec §6 D60): the request itself records
// kind='handed_off' (distinct from a normal 'filed' request -- no further adjudication
// happens on it, the assigned TAs take over person-to-person). Does not touch status;
// the request's status lifecycle (received/under_review/resolved_*) is orthogonal to
// kind and callers manage it separately if at all for a handed-off row.
func (q *Queries) MarkRequestHandedOff(ctx context.Context, id int64) (RegradeRequest, error) {
	row := q.db.QueryRow(ctx, markRequestHandedOff, id)
	var i RegradeRequest
	err := row.Scan(
		&i.ID,
		&i.PublishItemID,
		&i.StudentID,
		&i.AssessmentID,
		&i.ReceivedAt,
		&i.FromEmail,
		&i.SpfVerdict,
		&i.DkimVerdict,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.ResolverID,
		&i.ResolutionNote,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.MessageID,
		&i.Turn,
		&i.AiError,
		&i.Kind,
		&i.ResultSentAt,
	)
	return i, err
}

const nextOpenTurn = `-- name: NextOpenTurn :one
SELECT (COALESCE(MAX(turn), 0) + 1)::int AS next_turn
FROM regrade_requests
WHERE publish_item_id = $1 AND kind IN ('filed', 'handed_off')
`

// The live chain's next open turn slot for a publish item: max consumed turn + 1 over
// the rows that consume slots (kind IN ('filed','handed_off') — the same kinds
// ConsumedTokenExists treats as consumed), COALESCEd to 1 for a chain with no filings
// yet. Used by the webhook's rung-2 re-bind (wave-5 verifier finding): a superseded
// chain's token must be REMAPPED to this slot rather than carrying its stale turn onto
// the live chain — a preserved stale turn 2 would consume (live item, 2) before the
// live chain ever sent result #1, stranding the student's later legitimate turn-2 reply
// as a silent addendum. Addendum/unparsed rows never consume a slot, so they don't count.
func (q *Queries) NextOpenTurn(ctx context.Context, publishItemID pgtype.Int8) (int32, error) {
	row := q.db.QueryRow(ctx, nextOpenTurn, publishItemID)
	var next_turn int32
	err := row.Scan(&next_turn)
	return next_turn, err
}

const pendingRoundSubItems = `-- name: PendingRoundSubItems :many
SELECT rp.id
FROM regrade_request_problems rp
JOIN regrade_requests rr ON rr.id = rp.request_id
WHERE rr.assessment_id = $1
  AND rr.turn = $2
  AND rr.kind = 'filed'
  AND rr.status IN ('received', 'under_review')
  AND rp.ai_record_id IS NULL
  AND rp.verdict IS NULL
ORDER BY rp.id
`

type PendingRoundSubItemsParams struct {
	AssessmentID pgtype.Int8 `json:"assessment_id"`
	Turn         pgtype.Int4 `json:"turn"`
}

// PendingRoundSubItems is the round batch-grade work list: filed, still-open
// requests of this turn whose sub-items have no AI record and no terminal AI
// error yet.
func (q *Queries) PendingRoundSubItems(ctx context.Context, arg PendingRoundSubItemsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, pendingRoundSubItems, arg.AssessmentID, arg.Turn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const priorProblemVerdicts = `-- name: PriorProblemVerdicts :many
SELECT rr.turn AS turn, rrp.verdict AS verdict, rrp.verdict_note AS verdict_note
FROM regrade_requests rr
JOIN regrade_request_problems rrp ON rrp.request_id = rr.id
JOIN problems p ON p.id = rrp.problem_id
WHERE rr.publish_item_id = $1
  AND p.number = $2
  AND rr.kind = 'filed'
ORDER BY rr.turn
`

type PriorProblemVerdictsParams struct {
	PublishItemID pgtype.Int8 `json:"publish_item_id"`
	Number        int32       `json:"number"`
}

type PriorProblemVerdictsRow struct {
	Turn        pgtype.Int4 `json:"turn"`
	Verdict     pgtype.Text `json:"verdict"`
	VerdictNote string      `json:"verdict_note"`
}

// The verdict history for one problem across every FILED request of a publish item's
// token chain (spec §6: the assigned TA gets the student's full prior-turn history for
// that problem on handoff). Joins each filed request's sub-item for the given problem
// NUMBER (matched via problems.number so it survives the handoff request's own row), in
// turn order. Verdict may be NULL for a still-open prior turn; the caller skips those.
func (q *Queries) PriorProblemVerdicts(ctx context.Context, arg PriorProblemVerdictsParams) ([]PriorProblemVerdictsRow, error) {
	rows, err := q.db.Query(ctx, priorProblemVerdicts, arg.PublishItemID, arg.Number)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PriorProblemVerdictsRow
	for rows.Next() {
		var i PriorProblemVerdictsRow
		if err := rows.Scan(&i.Turn, &i.Verdict, &i.VerdictNote); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const regradeLayersForAnswer = `-- name: RegradeLayersForAnswer :many
SELECT rr.turn, rr.id AS request_id, rp.id AS sub_item_id,
    rp.verdict, rp.verdict_note, rp.verdict_at,
    rp.adopted_record_id, gr.total AS adopted_total
FROM regrade_request_problems rp
JOIN regrade_requests rr ON rr.id = rp.request_id
JOIN answers a ON a.assessment_id = rr.assessment_id
    AND a.student_id = rr.student_id AND a.problem_id = rp.problem_id
LEFT JOIN grading_records gr ON gr.id = rp.adopted_record_id
WHERE a.id = $1 AND rp.verdict IS NOT NULL
ORDER BY rr.turn, rp.id
`

type RegradeLayersForAnswerRow struct {
	Turn            pgtype.Int4        `json:"turn"`
	RequestID       int64              `json:"request_id"`
	SubItemID       int64              `json:"sub_item_id"`
	Verdict         pgtype.Text        `json:"verdict"`
	VerdictNote     string             `json:"verdict_note"`
	VerdictAt       pgtype.Timestamptz `json:"verdict_at"`
	AdoptedRecordID pgtype.Int8        `json:"adopted_record_id"`
	AdoptedTotal    pgtype.Numeric     `json:"adopted_total"`
}

// RegradeLayersForAnswer lists an answer's ADJUDICATED regrade overlays (the
// layer stack above round 0), oldest turn first — the answer page's layer
// pager renders one entry per turn that actually touched this problem.
func (q *Queries) RegradeLayersForAnswer(ctx context.Context, id int64) ([]RegradeLayersForAnswerRow, error) {
	rows, err := q.db.Query(ctx, regradeLayersForAnswer, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegradeLayersForAnswerRow
	for rows.Next() {
		var i RegradeLayersForAnswerRow
		if err := rows.Scan(
			&i.Turn,
			&i.RequestID,
			&i.SubItemID,
			&i.Verdict,
			&i.VerdictNote,
			&i.VerdictAt,
			&i.AdoptedRecordID,
			&i.AdoptedTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const regradeRoundCounts = `-- name: RegradeRoundCounts :many
SELECT rr.turn,
    count(*) FILTER (WHERE rp.ai_record_id IS NULL AND rp.verdict IS NULL
        AND rr.status IN ('received', 'under_review'))          AS pending,
    count(*) FILTER (WHERE rp.ai_record_id IS NOT NULL AND rp.verdict IS NULL) AS graded,
    count(*) FILTER (WHERE rp.verdict IS NOT NULL)              AS adjudicated
FROM regrade_requests rr
JOIN regrade_request_problems rp ON rp.request_id = rr.id
WHERE rr.assessment_id = $1 AND rr.kind = 'filed' AND rr.turn IS NOT NULL
GROUP BY rr.turn
ORDER BY rr.turn
`

type RegradeRoundCountsRow struct {
	Turn        pgtype.Int4 `json:"turn"`
	Pending     int64       `json:"pending"`
	Graded      int64       `json:"graded"`
	Adjudicated int64       `json:"adjudicated"`
}

// RegradeRoundCounts feeds the Regrade tab's per-round work summary.
func (q *Queries) RegradeRoundCounts(ctx context.Context, assessmentID pgtype.Int8) ([]RegradeRoundCountsRow, error) {
	rows, err := q.db.Query(ctx, regradeRoundCounts, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegradeRoundCountsRow
	for rows.Next() {
		var i RegradeRoundCountsRow
		if err := rows.Scan(
			&i.Turn,
			&i.Pending,
			&i.Graded,
			&i.Adjudicated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProblemTA = `-- name: RemoveProblemTA :exec
DELETE FROM problem_ta_assignments WHERE problem_id = $1
`

// Unassign (spec §6 D60 UI: "assign/unassign TA") -- deletes the row rather than
// nulling user_id, since user_id is NOT NULL (an assignment row only exists when
// there IS an assignee; "no TA" is "no row", matching ListTAAssignments' LEFT JOIN).
func (q *Queries) RemoveProblemTA(ctx context.Context, problemID int64) error {
	_, err := q.db.Exec(ctx, removeProblemTA, problemID)
	return err
}

const resolveRegradeRequest = `-- name: ResolveRegradeRequest :one
UPDATE regrade_requests
SET status = $2, resolver_id = $3, resolution_note = $4, resolved_at = now()
WHERE id = $1 AND status IN ('received', 'under_review')
RETURNING id, publish_item_id, student_id, assessment_id, received_at, from_email, spf_verdict, dkim_verdict, subject, body, status, resolver_id, resolution_note, resolved_at, created_at, message_id, turn, ai_error, kind, result_sent_at
`

type ResolveRegradeRequestParams struct {
	ID             int64       `json:"id"`
	Status         string      `json:"status"`
	ResolverID     pgtype.Int8 `json:"resolver_id"`
	ResolutionNote string      `json:"resolution_note"`
}

// F2 (TOCTOU on resolve, unchanged from v1): the status guard is enforced HERE,
// atomically with the write, not just in the handler's pre-check read.
func (q *Queries) ResolveRegradeRequest(ctx context.Context, arg ResolveRegradeRequestParams) (RegradeRequest, error) {
	row := q.db.QueryRow(ctx, resolveRegradeRequest,
		arg.ID,
		arg.Status,
		arg.ResolverID,
		arg.ResolutionNote,
	)
	var i RegradeRequest
	err := row.Scan(
		&i.ID,
		&i.PublishItemID,
		&i.StudentID,
		&i.AssessmentID,
		&i.ReceivedAt,
		&i.FromEmail,
		&i.SpfVerdict,
		&i.DkimVerdict,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.ResolverID,
		&i.ResolutionNote,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.MessageID,
		&i.Turn,
		&i.AiError,
		&i.Kind,
		&i.ResultSentAt,
	)
	return i, err
}

const roundHasGradedSubItems = `-- name: RoundHasGradedSubItems :one
SELECT EXISTS (
    SELECT 1
    FROM regrade_request_problems rp
    JOIN regrade_requests rr ON rr.id = rp.request_id
    WHERE rr.assessment_id = $1 AND rr.turn = $2 AND rp.ai_record_id IS NOT NULL
) AS graded
`

type RoundHasGradedSubItemsParams struct {
	AssessmentID pgtype.Int8 `json:"assessment_id"`
	Turn         pgtype.Int4 `json:"turn"`
}

// RoundHasGradedSubItems gates round-method edits: a round's method is preset
// and editable only until it has actually graded something.
func (q *Queries) RoundHasGradedSubItems(ctx context.Context, arg RoundHasGradedSubItemsParams) (bool, error) {
	row := q.db.QueryRow(ctx, roundHasGradedSubItems, arg.AssessmentID, arg.Turn)
	var graded bool
	err := row.Scan(&graded)
	return graded, err
}

const setProblemAIError = `-- name: SetProblemAIError :one
UPDATE regrade_request_problems SET ai_error = $2 WHERE id = $1 RETURNING id, request_id, problem_id, complaint_text, ai_record_id, ai_error, verdict, verdict_note, verdict_by, verdict_at, created_at, adopted_record_id
`

type SetProblemAIErrorParams struct {
	ID      int64       `json:"id"`
	AiError pgtype.Text `json:"ai_error"`
}

// Terminal AI re-grade failure reason for one sub-item: short constant string only
// (CLAUDE.md PII rule), never touches verdict or ai_record_id.
func (q *Queries) SetProblemAIError(ctx context.Context, arg SetProblemAIErrorParams) (RegradeRequestProblem, error) {
	row := q.db.QueryRow(ctx, setProblemAIError, arg.ID, arg.AiError)
	var i RegradeRequestProblem
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ProblemID,
		&i.ComplaintText,
		&i.AiRecordID,
		&i.AiError,
		&i.Verdict,
		&i.VerdictNote,
		&i.VerdictBy,
		&i.VerdictAt,
		&i.CreatedAt,
		&i.AdoptedRecordID,
	)
	return i, err
}

const setProblemAIRecord = `-- name: SetProblemAIRecord :one
UPDATE regrade_request_problems SET ai_record_id = $2, ai_error = NULL WHERE id = $1 RETURNING id, request_id, problem_id, complaint_text, ai_record_id, ai_error, verdict, verdict_note, verdict_by, verdict_at, created_at, adopted_record_id
`

type SetProblemAIRecordParams struct {
	ID         int64       `json:"id"`
	AiRecordID pgtype.Int8 `json:"ai_record_id"`
}

// Links the per-sub-item AI re-grade result (spec §5: AI assist re-scopes to one
// sub-item per job). Mirrors v1's SetRegradeAIRecord posture: never touches verdict,
// clears any stale ai_error so a successful re-grade doesn't leave an old failure
// reason visible next to the freshly linked record.
func (q *Queries) SetProblemAIRecord(ctx context.Context, arg SetProblemAIRecordParams) (RegradeRequestProblem, error) {
	row := q.db.QueryRow(ctx, setProblemAIRecord, arg.ID, arg.AiRecordID)
	var i RegradeRequestProblem
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ProblemID,
		&i.ComplaintText,
		&i.AiRecordID,
		&i.AiError,
		&i.Verdict,
		&i.VerdictNote,
		&i.VerdictBy,
		&i.VerdictAt,
		&i.CreatedAt,
		&i.AdoptedRecordID,
	)
	return i, err
}

const setProblemVerdict = `-- name: SetProblemVerdict :one
UPDATE regrade_request_problems
SET verdict = $2, verdict_note = $3, verdict_by = $4, verdict_at = now()
WHERE id = $1
RETURNING id, request_id, problem_id, complaint_text, ai_record_id, ai_error, verdict, verdict_note, verdict_by, verdict_at, created_at, adopted_record_id
`

type SetProblemVerdictParams struct {
	ID          int64       `json:"id"`
	Verdict     pgtype.Text `json:"verdict"`
	VerdictNote string      `json:"verdict_note"`
	VerdictBy   pgtype.Int8 `json:"verdict_by"`
}

// TA adjudication of one sub-item (spec §5): outcome upheld|regraded, note, who, when.
// The CHECK on verdict (migration 0025) rejects anything else at the database level.
func (q *Queries) SetProblemVerdict(ctx context.Context, arg SetProblemVerdictParams) (RegradeRequestProblem, error) {
	row := q.db.QueryRow(ctx, setProblemVerdict,
		arg.ID,
		arg.Verdict,
		arg.VerdictNote,
		arg.VerdictBy,
	)
	var i RegradeRequestProblem
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ProblemID,
		&i.ComplaintText,
		&i.AiRecordID,
		&i.AiError,
		&i.Verdict,
		&i.VerdictNote,
		&i.VerdictBy,
		&i.VerdictAt,
		&i.CreatedAt,
		&i.AdoptedRecordID,
	)
	return i, err
}

const setProblemVerdictAndAdoption = `-- name: SetProblemVerdictAndAdoption :one
UPDATE regrade_request_problems
SET verdict = $2, verdict_note = $3, verdict_by = $4, verdict_at = now(),
    adopted_record_id = $5
WHERE id = $1
RETURNING id, request_id, problem_id, complaint_text, ai_record_id, ai_error, verdict, verdict_note, verdict_by, verdict_at, created_at, adopted_record_id
`

type SetProblemVerdictAndAdoptionParams struct {
	ID              int64       `json:"id"`
	Verdict         pgtype.Text `json:"verdict"`
	VerdictNote     string      `json:"verdict_note"`
	VerdictBy       pgtype.Int8 `json:"verdict_by"`
	AdoptedRecordID pgtype.Int8 `json:"adopted_record_id"`
}

// SetProblemVerdictAndAdoption records a TA's adjudication AND its overlay in ONE
// atomic statement (regrade-round correctness fix): the old handler ran SetProblemVerdict
// then SetSubItemAdoptedRecord as two writes, so a failure between them could strand a
// verdict='upheld' row still carrying a stale adopted_record_id — an override overlay
// consumers would apply for a grade the student was never told about. Setting verdict,
// note, who, when, and adopted_record_id together makes the pair all-or-nothing:
// adopted_record_id carries the record for a 'regraded' verdict, or SQL NULL (narg) for
// 'upheld'.
func (q *Queries) SetProblemVerdictAndAdoption(ctx context.Context, arg SetProblemVerdictAndAdoptionParams) (RegradeRequestProblem, error) {
	row := q.db.QueryRow(ctx, setProblemVerdictAndAdoption,
		arg.ID,
		arg.Verdict,
		arg.VerdictNote,
		arg.VerdictBy,
		arg.AdoptedRecordID,
	)
	var i RegradeRequestProblem
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ProblemID,
		&i.ComplaintText,
		&i.AiRecordID,
		&i.AiError,
		&i.Verdict,
		&i.VerdictNote,
		&i.VerdictBy,
		&i.VerdictAt,
		&i.CreatedAt,
		&i.AdoptedRecordID,
	)
	return i, err
}

const setRegradeResultSentAt = `-- name: SetRegradeResultSentAt :one
UPDATE regrade_requests SET result_sent_at = now() WHERE id = $1 RETURNING id, publish_item_id, student_id, assessment_id, received_at, from_email, spf_verdict, dkim_verdict, subject, body, status, resolver_id, resolution_note, resolved_at, created_at, message_id, turn, ai_error, kind, result_sent_at
`

// Send-failure recovery path (whole-branch review F1, migration 0026): records that
// result email #N was actually DELIVERED for this request -- set only after a
// successful provider send, by both the original send-result flow and the
// resend-result recovery route. NULL means "resolved but nothing was ever
// delivered" (a provider failure after the atomic resolve flip) -- the signal
// resend-result's guard checks for.
func (q *Queries) SetRegradeResultSentAt(ctx context.Context, id int64) (RegradeRequest, error) {
	row := q.db.QueryRow(ctx, setRegradeResultSentAt, id)
	var i RegradeRequest
	err := row.Scan(
		&i.ID,
		&i.PublishItemID,
		&i.StudentID,
		&i.AssessmentID,
		&i.ReceivedAt,
		&i.FromEmail,
		&i.SpfVerdict,
		&i.DkimVerdict,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.ResolverID,
		&i.ResolutionNote,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.MessageID,
		&i.Turn,
		&i.AiError,
		&i.Kind,
		&i.ResultSentAt,
	)
	return i, err
}

const setRegradeStatus = `-- name: SetRegradeStatus :one
UPDATE regrade_requests SET status = $2 WHERE id = $1 RETURNING id, publish_item_id, student_id, assessment_id, received_at, from_email, spf_verdict, dkim_verdict, subject, body, status, resolver_id, resolution_note, resolved_at, created_at, message_id, turn, ai_error, kind, result_sent_at
`

type SetRegradeStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

// Used for the intermediate 'under_review' transition.
func (q *Queries) SetRegradeStatus(ctx context.Context, arg SetRegradeStatusParams) (RegradeRequest, error) {
	row := q.db.QueryRow(ctx, setRegradeStatus, arg.ID, arg.Status)
	var i RegradeRequest
	err := row.Scan(
		&i.ID,
		&i.PublishItemID,
		&i.StudentID,
		&i.AssessmentID,
		&i.ReceivedAt,
		&i.FromEmail,
		&i.SpfVerdict,
		&i.DkimVerdict,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.ResolverID,
		&i.ResolutionNote,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.MessageID,
		&i.Turn,
		&i.AiError,
		&i.Kind,
		&i.ResultSentAt,
	)
	return i, err
}

const setSubItemAdoptedRecord = `-- name: SetSubItemAdoptedRecord :one
UPDATE regrade_request_problems
SET adopted_record_id = $2
WHERE id = $1
RETURNING id, request_id, problem_id, complaint_text, ai_record_id, ai_error, verdict, verdict_note, verdict_by, verdict_at, created_at, adopted_record_id
`

type SetSubItemAdoptedRecordParams struct {
	ID       int64       `json:"id"`
	RecordID pgtype.Int8 `json:"record_id"`
}

// SetSubItemAdoptedRecord stamps the overlay layer for a regraded verdict
// (0028): the adopted record IS that turn's grade for the answer.
func (q *Queries) SetSubItemAdoptedRecord(ctx context.Context, arg SetSubItemAdoptedRecordParams) (RegradeRequestProblem, error) {
	row := q.db.QueryRow(ctx, setSubItemAdoptedRecord, arg.ID, arg.RecordID)
	var i RegradeRequestProblem
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ProblemID,
		&i.ComplaintText,
		&i.AiRecordID,
		&i.AiError,
		&i.Verdict,
		&i.VerdictNote,
		&i.VerdictBy,
		&i.VerdictAt,
		&i.CreatedAt,
		&i.AdoptedRecordID,
	)
	return i, err
}

const studentOfficialTotalForProblem = `-- name: StudentOfficialTotalForProblem :one
SELECT
    coalesce(sum(gr.total), 0)::numeric AS total,
    coalesce((SELECT p.max_points FROM problems p WHERE p.id = $2), 0)::numeric AS max,
    count(a.official_record_id) AS graded
FROM answers a
LEFT JOIN grading_records gr ON gr.id = a.official_record_id
WHERE a.student_id = $1 AND a.problem_id = $2
`

type StudentOfficialTotalForProblemParams struct {
	StudentID int64 `json:"student_id"`
	ID        int64 `json:"id"`
}

type StudentOfficialTotalForProblemRow struct {
	Total  pgtype.Numeric `json:"total"`
	Max    pgtype.Numeric `json:"max"`
	Graded int64          `json:"graded"`
}

// A student's current official (score, max) for ONE problem, straight from live grading
// state -- the fresh figure the result email announces for a REGRADED verdict (C2:
// never the superseded snapshot the token was minted against). graded counts whether
// the answer carries an official record; zero means nothing is official for this
// (student, problem) yet, so the caller omits the New-score line rather than announcing
// "0/max".
func (q *Queries) StudentOfficialTotalForProblem(ctx context.Context, arg StudentOfficialTotalForProblemParams) (StudentOfficialTotalForProblemRow, error) {
	row := q.db.QueryRow(ctx, studentOfficialTotalForProblem, arg.StudentID, arg.ID)
	var i StudentOfficialTotalForProblemRow
	err := row.Scan(&i.Total, &i.Max, &i.Graded)
	return i, err
}

const upsertRegradeRoundMethod = `-- name: UpsertRegradeRoundMethod :one
INSERT INTO regrade_round_methods (assessment_id, turn, method_id)
VALUES ($1, $2, $3)
ON CONFLICT (assessment_id, turn) DO UPDATE
    SET method_id = EXCLUDED.method_id, updated_at = now()
RETURNING assessment_id, turn, method_id, updated_at
`

type UpsertRegradeRoundMethodParams struct {
	AssessmentID int64 `json:"assessment_id"`
	Turn         int32 `json:"turn"`
	MethodID     int64 `json:"method_id"`
}

// Per-round regrade methods (0027): one method per email turn, preset on the
// Regrade tab, usually a single strict model.
func (q *Queries) UpsertRegradeRoundMethod(ctx context.Context, arg UpsertRegradeRoundMethodParams) (RegradeRoundMethod, error) {
	row := q.db.QueryRow(ctx, upsertRegradeRoundMethod, arg.AssessmentID, arg.Turn, arg.MethodID)
	var i RegradeRoundMethod
	err := row.Scan(
		&i.AssessmentID,
		&i.Turn,
		&i.MethodID,
		&i.UpdatedAt,
	)
	return i, err
}
