// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assessmentStudentTotals = `-- name: AssessmentStudentTotals :many
SELECT st.student_id, st.name, st.email,
    (st.withdrawn_at IS NOT NULL)::bool AS withdrawn,
    count(a.id) AS answers,
    count(COALESCE(overlay.record_id, a.official_record_id)) AS graded,
    sum(COALESCE(ogr.total, gr.total))::numeric AS total
FROM answers a
JOIN students st ON st.id = a.student_id
LEFT JOIN grading_records gr ON gr.id = a.official_record_id
LEFT JOIN LATERAL (
    SELECT rp.adopted_record_id AS record_id
    FROM regrade_request_problems rp
    JOIN regrade_requests rr ON rr.id = rp.request_id
    LEFT JOIN publish_items pi ON pi.id = rr.publish_item_id
    LEFT JOIN publish_batches pb ON pb.id = pi.batch_id
    WHERE rr.assessment_id = a.assessment_id
      AND rr.student_id = a.student_id
      AND rp.problem_id = a.problem_id
      AND rp.verdict = 'regraded'
      AND rp.adopted_record_id IS NOT NULL
    ORDER BY (pb.superseded_at IS NOT NULL), rp.verdict_at DESC NULLS LAST, rr.turn DESC, rp.id DESC
    LIMIT 1
) overlay ON true
LEFT JOIN grading_records ogr ON ogr.id = overlay.record_id
WHERE a.assessment_id = $1
GROUP BY st.id
ORDER BY st.student_id
`

type AssessmentStudentTotalsRow struct {
	StudentID string         `json:"student_id"`
	Name      string         `json:"name"`
	Email     string         `json:"email"`
	Withdrawn bool           `json:"withdrawn"`
	Answers   int64          `json:"answers"`
	Graded    int64          `json:"graded"`
	Total     pgtype.Numeric `json:"total"`
}

// AssessmentStudentTotals sums each student's EFFECTIVE grades (rounds design,
// 0028): the latest adopted regrade-overlay record per answer wins over the
// round-0 official; the official alone otherwise. NULL total until anything
// effective exists (D3). Withdrawn students stay visible with `withdrawn`
// true (never silently dropped, roster-lifecycle plan 2026-07-10) — the
// totals card badges them instead. The overlay LATERAL is byte-identical to
// ExportRows' (see that query's note on the cross-chain ordering fix).
func (q *Queries) AssessmentStudentTotals(ctx context.Context, assessmentID int64) ([]AssessmentStudentTotalsRow, error) {
	rows, err := q.db.Query(ctx, assessmentStudentTotals, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssessmentStudentTotalsRow
	for rows.Next() {
		var i AssessmentStudentTotalsRow
		if err := rows.Scan(
			&i.StudentID,
			&i.Name,
			&i.Email,
			&i.Withdrawn,
			&i.Answers,
			&i.Graded,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportRows = `-- name: ExportRows :many
SELECT st.student_id, st.name, p.number AS problem_number,
    COALESCE(ogr.total, gr.total)::numeric AS total,
    COALESCE(ogr.source, gr.source, '')::text AS official_source,
    (st.withdrawn_at IS NOT NULL)::bool AS withdrawn
FROM answers a
JOIN students st ON st.id = a.student_id
JOIN problems p ON p.id = a.problem_id
LEFT JOIN grading_records gr ON gr.id = a.official_record_id
LEFT JOIN LATERAL (
    SELECT rp.adopted_record_id AS record_id
    FROM regrade_request_problems rp
    JOIN regrade_requests rr ON rr.id = rp.request_id
    LEFT JOIN publish_items pi ON pi.id = rr.publish_item_id
    LEFT JOIN publish_batches pb ON pb.id = pi.batch_id
    WHERE rr.assessment_id = a.assessment_id
      AND rr.student_id = a.student_id
      AND rp.problem_id = a.problem_id
      AND rp.verdict = 'regraded'
      AND rp.adopted_record_id IS NOT NULL
    ORDER BY (pb.superseded_at IS NOT NULL), rp.verdict_at DESC NULLS LAST, rr.turn DESC, rp.id DESC
    LIMIT 1
) overlay ON true
LEFT JOIN grading_records ogr ON ogr.id = overlay.record_id
WHERE a.assessment_id = $1
ORDER BY st.student_id, p.number
`

type ExportRowsRow struct {
	StudentID      string         `json:"student_id"`
	Name           string         `json:"name"`
	ProblemNumber  int32          `json:"problem_number"`
	Total          pgtype.Numeric `json:"total"`
	OfficialSource string         `json:"official_source"`
	Withdrawn      bool           `json:"withdrawn"`
}

// ExportRows exports EFFECTIVE grades (rounds design, 0028): the latest
// adopted regrade overlay wins over the round-0 official. Withdrawn students
// are NOT filtered — exports must never silently drop a student
// (roster-lifecycle plan 2026-07-10) — they are flagged via `withdrawn`
// instead, which the CSV emits as a final status column.
//
// The overlay LATERAL below is the ONE canonical effective-grade resolver,
// reproduced byte-for-byte in AssessmentStudentTotals and
// PublishSnapshotInputs (and, with an extra exclude clause, in
// ContestedAnswerForSubItem) — keep the four in sync. Ordering (regrade-round
// correctness fix): turn numbers RESTART per publish chain, so a superseded
// chain's high-turn adoption must not outrank the live chain's newer,
// lower-turn one. So resolve by (1) live chain first — the request's publish
// item's batch is NOT superseded — then (2) most-recently adjudicated
// (verdict_at), then turn/id as stable tiebreaks. `rp.verdict = 'regraded'`
// guards against a stale adopted_record_id left behind by a later flip to
// 'upheld' (only a regraded verdict's adoption is an effective grade).
func (q *Queries) ExportRows(ctx context.Context, assessmentID int64) ([]ExportRowsRow, error) {
	rows, err := q.db.Query(ctx, exportRows, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportRowsRow
	for rows.Next() {
		var i ExportRowsRow
		if err := rows.Scan(
			&i.StudentID,
			&i.Name,
			&i.ProblemNumber,
			&i.Total,
			&i.OfficialSource,
			&i.Withdrawn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnswerContext = `-- name: GetAnswerContext :one
SELECT a.id, a.assessment_id, a.student_id, a.problem_id, a.official_record_id, a.official_set_by, a.official_set_at, a.published_at, a.flags, a.created_at, a.updated_at,
    st.student_id AS student_external_id, st.name AS student_name, st.email AS student_email,
    p.number AS problem_number, p.title AS problem_title, p.max_points, p.statement,
    ass.name AS assessment_name
FROM answers a
JOIN students st ON st.id = a.student_id
JOIN problems p ON p.id = a.problem_id
JOIN assessments ass ON ass.id = a.assessment_id
WHERE a.id = $1
`

type GetAnswerContextRow struct {
	ID                int64              `json:"id"`
	AssessmentID      int64              `json:"assessment_id"`
	StudentID         int64              `json:"student_id"`
	ProblemID         int64              `json:"problem_id"`
	OfficialRecordID  pgtype.Int8        `json:"official_record_id"`
	OfficialSetBy     pgtype.Int8        `json:"official_set_by"`
	OfficialSetAt     pgtype.Timestamptz `json:"official_set_at"`
	PublishedAt       pgtype.Timestamptz `json:"published_at"`
	Flags             []string           `json:"flags"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	StudentExternalID string             `json:"student_external_id"`
	StudentName       string             `json:"student_name"`
	StudentEmail      string             `json:"student_email"`
	ProblemNumber     int32              `json:"problem_number"`
	ProblemTitle      string             `json:"problem_title"`
	MaxPoints         pgtype.Numeric     `json:"max_points"`
	Statement         string             `json:"statement"`
	AssessmentName    string             `json:"assessment_name"`
}

func (q *Queries) GetAnswerContext(ctx context.Context, id int64) (GetAnswerContextRow, error) {
	row := q.db.QueryRow(ctx, getAnswerContext, id)
	var i GetAnswerContextRow
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.StudentID,
		&i.ProblemID,
		&i.OfficialRecordID,
		&i.OfficialSetBy,
		&i.OfficialSetAt,
		&i.PublishedAt,
		&i.Flags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StudentExternalID,
		&i.StudentName,
		&i.StudentEmail,
		&i.ProblemNumber,
		&i.ProblemTitle,
		&i.MaxPoints,
		&i.Statement,
		&i.AssessmentName,
	)
	return i, err
}

const getRecord = `-- name: GetRecord :one
SELECT id, answer_id, run_id, source, provider, model_id, method_version_id, rubric_version_id, reference_solution_version_id, prompt_template_version_id, graded_image_shas, criterion_scores, total, comment, transcription, confidence, adjustments, raw_output, input_tokens, output_tokens, cost_usd, temperature, created_by, created_at, policy FROM grading_records WHERE id = $1
`

func (q *Queries) GetRecord(ctx context.Context, id int64) (GradingRecord, error) {
	row := q.db.QueryRow(ctx, getRecord, id)
	var i GradingRecord
	err := row.Scan(
		&i.ID,
		&i.AnswerID,
		&i.RunID,
		&i.Source,
		&i.Provider,
		&i.ModelID,
		&i.MethodVersionID,
		&i.RubricVersionID,
		&i.ReferenceSolutionVersionID,
		&i.PromptTemplateVersionID,
		&i.GradedImageShas,
		&i.CriterionScores,
		&i.Total,
		&i.Comment,
		&i.Transcription,
		&i.Confidence,
		&i.Adjustments,
		&i.RawOutput,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CostUsd,
		&i.Temperature,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Policy,
	)
	return i, err
}

const listRecordsForAnswer = `-- name: ListRecordsForAnswer :many
SELECT id, answer_id, run_id, source, provider, model_id, method_version_id, rubric_version_id, reference_solution_version_id, prompt_template_version_id, graded_image_shas, criterion_scores, total, comment, transcription, confidence, adjustments, raw_output, input_tokens, output_tokens, cost_usd, temperature, created_by, created_at, policy FROM grading_records WHERE answer_id = $1 ORDER BY id DESC
`

func (q *Queries) ListRecordsForAnswer(ctx context.Context, answerID int64) ([]GradingRecord, error) {
	rows, err := q.db.Query(ctx, listRecordsForAnswer, answerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GradingRecord
	for rows.Next() {
		var i GradingRecord
		if err := rows.Scan(
			&i.ID,
			&i.AnswerID,
			&i.RunID,
			&i.Source,
			&i.Provider,
			&i.ModelID,
			&i.MethodVersionID,
			&i.RubricVersionID,
			&i.ReferenceSolutionVersionID,
			&i.PromptTemplateVersionID,
			&i.GradedImageShas,
			&i.CriterionScores,
			&i.Total,
			&i.Comment,
			&i.Transcription,
			&i.Confidence,
			&i.Adjustments,
			&i.RawOutput,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostUsd,
			&i.Temperature,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Policy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const problemStudentRows = `-- name: ProblemStudentRows :many
SELECT a.id AS answer_id, st.student_id, st.name, st.email, a.flags, a.published_at,
    a.official_record_id,
    (SELECT count(*) FROM answer_pages ap WHERE ap.answer_id = a.id) AS page_count,
    (SELECT count(*) FROM grading_records gr WHERE gr.answer_id = a.id) AS record_count,
    ogr.total AS official_total,
    ogr.source AS official_source
FROM answers a
JOIN students st ON st.id = a.student_id
LEFT JOIN grading_records ogr ON ogr.id = a.official_record_id
WHERE a.problem_id = $1
ORDER BY st.student_id
`

type ProblemStudentRowsRow struct {
	AnswerID         int64              `json:"answer_id"`
	StudentID        string             `json:"student_id"`
	Name             string             `json:"name"`
	Email            string             `json:"email"`
	Flags            []string           `json:"flags"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
	OfficialRecordID pgtype.Int8        `json:"official_record_id"`
	PageCount        int64              `json:"page_count"`
	RecordCount      int64              `json:"record_count"`
	OfficialTotal    pgtype.Numeric     `json:"official_total"`
	OfficialSource   pgtype.Text        `json:"official_source"`
}

func (q *Queries) ProblemStudentRows(ctx context.Context, problemID int64) ([]ProblemStudentRowsRow, error) {
	rows, err := q.db.Query(ctx, problemStudentRows, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProblemStudentRowsRow
	for rows.Next() {
		var i ProblemStudentRowsRow
		if err := rows.Scan(
			&i.AnswerID,
			&i.StudentID,
			&i.Name,
			&i.Email,
			&i.Flags,
			&i.PublishedAt,
			&i.OfficialRecordID,
			&i.PageCount,
			&i.RecordCount,
			&i.OfficialTotal,
			&i.OfficialSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const problemSummaries = `-- name: ProblemSummaries :many

SELECT p.id, p.number, p.title, p.max_points, p.position,
    count(a.id) AS answer_count,
    count(*) FILTER (WHERE EXISTS (SELECT 1 FROM answer_pages ap WHERE ap.answer_id = a.id)) AS with_pages,
    count(*) FILTER (WHERE a.official_record_id IS NOT NULL) AS official_set,
    count(*) FILTER (WHERE EXISTS (SELECT 1 FROM grading_records gr WHERE gr.answer_id = a.id AND gr.source = 'model')) AS ai_graded,
    count(*) FILTER (WHERE EXISTS (SELECT 1 FROM grading_records gr WHERE gr.answer_id = a.id AND gr.source = 'human')) AS human_graded,
    count(*) FILTER (WHERE cardinality(a.flags) > 0) AS flagged,
    count(*) FILTER (WHERE a.published_at IS NOT NULL) AS published
FROM problems p
LEFT JOIN answers a ON a.problem_id = p.id
WHERE p.assessment_id = $1
GROUP BY p.id
ORDER BY p.position, p.number
`

type ProblemSummariesRow struct {
	ID          int64          `json:"id"`
	Number      int32          `json:"number"`
	Title       string         `json:"title"`
	MaxPoints   pgtype.Numeric `json:"max_points"`
	Position    int32          `json:"position"`
	AnswerCount int64          `json:"answer_count"`
	WithPages   int64          `json:"with_pages"`
	OfficialSet int64          `json:"official_set"`
	AiGraded    int64          `json:"ai_graded"`
	HumanGraded int64          `json:"human_graded"`
	Flagged     int64          `json:"flagged"`
	Published   int64          `json:"published"`
}

// Drill-down read models. Status is DERIVED from facts at query time (D2) — no
// status enum exists anywhere.
func (q *Queries) ProblemSummaries(ctx context.Context, assessmentID int64) ([]ProblemSummariesRow, error) {
	rows, err := q.db.Query(ctx, problemSummaries, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProblemSummariesRow
	for rows.Next() {
		var i ProblemSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Title,
			&i.MaxPoints,
			&i.Position,
			&i.AnswerCount,
			&i.WithPages,
			&i.OfficialSet,
			&i.AiGraded,
			&i.HumanGraded,
			&i.Flagged,
			&i.Published,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const studentSubmissionRows = `-- name: StudentSubmissionRows :many
SELECT a.id AS answer_id, p.number AS problem_number, p.title AS problem_title,
    (SELECT count(*) FROM grading_records gr WHERE gr.answer_id = a.id) AS record_count,
    a.official_record_id,
    ap.id AS page_id, ap.page_index,
    (ap.masked_image_ref IS NOT NULL)::bool AS masked
FROM answers a
JOIN problems p ON p.id = a.problem_id
JOIN students st ON st.id = a.student_id
LEFT JOIN answer_pages ap ON ap.answer_id = a.id
WHERE a.assessment_id = $1 AND st.student_id = $2
ORDER BY p.position, p.number, ap.page_index
`

type StudentSubmissionRowsParams struct {
	AssessmentID int64  `json:"assessment_id"`
	StudentID    string `json:"student_id"`
}

type StudentSubmissionRowsRow struct {
	AnswerID         int64       `json:"answer_id"`
	ProblemNumber    int32       `json:"problem_number"`
	ProblemTitle     string      `json:"problem_title"`
	RecordCount      int64       `json:"record_count"`
	OfficialRecordID pgtype.Int8 `json:"official_record_id"`
	PageID           pgtype.Int8 `json:"page_id"`
	PageIndex        pgtype.Int4 `json:"page_index"`
	Masked           bool        `json:"masked"`
}

func (q *Queries) StudentSubmissionRows(ctx context.Context, arg StudentSubmissionRowsParams) ([]StudentSubmissionRowsRow, error) {
	rows, err := q.db.Query(ctx, studentSubmissionRows, arg.AssessmentID, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StudentSubmissionRowsRow
	for rows.Next() {
		var i StudentSubmissionRowsRow
		if err := rows.Scan(
			&i.AnswerID,
			&i.ProblemNumber,
			&i.ProblemTitle,
			&i.RecordCount,
			&i.OfficialRecordID,
			&i.PageID,
			&i.PageIndex,
			&i.Masked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
