// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rubrics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRubricCriterion = `-- name: CreateRubricCriterion :one
INSERT INTO rubric_criteria (rubric_version_id, position, description, points, partial_credit_notes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, rubric_version_id, position, description, points, partial_credit_notes
`

type CreateRubricCriterionParams struct {
	RubricVersionID    int64          `json:"rubric_version_id"`
	Position           int32          `json:"position"`
	Description        string         `json:"description"`
	Points             pgtype.Numeric `json:"points"`
	PartialCreditNotes string         `json:"partial_credit_notes"`
}

func (q *Queries) CreateRubricCriterion(ctx context.Context, arg CreateRubricCriterionParams) (RubricCriterium, error) {
	row := q.db.QueryRow(ctx, createRubricCriterion,
		arg.RubricVersionID,
		arg.Position,
		arg.Description,
		arg.Points,
		arg.PartialCreditNotes,
	)
	var i RubricCriterium
	err := row.Scan(
		&i.ID,
		&i.RubricVersionID,
		&i.Position,
		&i.Description,
		&i.Points,
		&i.PartialCreditNotes,
	)
	return i, err
}

const createRubricVersion = `-- name: CreateRubricVersion :one
INSERT INTO rubric_versions (problem_id, version, notes, score_increment, created_by)
VALUES (
    $1,
    (SELECT COALESCE(MAX(version), 0) + 1 FROM rubric_versions WHERE problem_id = $1),
    $2, $3, $4
)
RETURNING id, problem_id, version, notes, score_increment, created_by, created_at
`

type CreateRubricVersionParams struct {
	ProblemID      int64          `json:"problem_id"`
	Notes          string         `json:"notes"`
	ScoreIncrement pgtype.Numeric `json:"score_increment"`
	CreatedBy      pgtype.Int8    `json:"created_by"`
}

func (q *Queries) CreateRubricVersion(ctx context.Context, arg CreateRubricVersionParams) (RubricVersion, error) {
	row := q.db.QueryRow(ctx, createRubricVersion,
		arg.ProblemID,
		arg.Notes,
		arg.ScoreIncrement,
		arg.CreatedBy,
	)
	var i RubricVersion
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Version,
		&i.Notes,
		&i.ScoreIncrement,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createSolutionVersion = `-- name: CreateSolutionVersion :one
INSERT INTO reference_solution_versions (problem_id, version, content, created_by)
VALUES (
    $1,
    (SELECT COALESCE(MAX(version), 0) + 1 FROM reference_solution_versions WHERE problem_id = $1),
    $2, $3
)
RETURNING id, problem_id, version, content, created_by, created_at
`

type CreateSolutionVersionParams struct {
	ProblemID int64       `json:"problem_id"`
	Content   string      `json:"content"`
	CreatedBy pgtype.Int8 `json:"created_by"`
}

func (q *Queries) CreateSolutionVersion(ctx context.Context, arg CreateSolutionVersionParams) (ReferenceSolutionVersion, error) {
	row := q.db.QueryRow(ctx, createSolutionVersion, arg.ProblemID, arg.Content, arg.CreatedBy)
	var i ReferenceSolutionVersion
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Version,
		&i.Content,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getRubricVersion = `-- name: GetRubricVersion :one
SELECT id, problem_id, version, notes, score_increment, created_by, created_at FROM rubric_versions WHERE id = $1
`

func (q *Queries) GetRubricVersion(ctx context.Context, id int64) (RubricVersion, error) {
	row := q.db.QueryRow(ctx, getRubricVersion, id)
	var i RubricVersion
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Version,
		&i.Notes,
		&i.ScoreIncrement,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getSolutionVersion = `-- name: GetSolutionVersion :one
SELECT id, problem_id, version, content, created_by, created_at FROM reference_solution_versions WHERE id = $1
`

func (q *Queries) GetSolutionVersion(ctx context.Context, id int64) (ReferenceSolutionVersion, error) {
	row := q.db.QueryRow(ctx, getSolutionVersion, id)
	var i ReferenceSolutionVersion
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Version,
		&i.Content,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const latestRubricVersion = `-- name: LatestRubricVersion :one

SELECT id, problem_id, version, notes, score_increment, created_by, created_at FROM rubric_versions WHERE problem_id = $1 ORDER BY version DESC LIMIT 1
`

// Rubric + reference-solution versions are insert-only (DECISIONS D5): new content
// is always version MAX+1 for the problem; nothing is ever mutated.
func (q *Queries) LatestRubricVersion(ctx context.Context, problemID int64) (RubricVersion, error) {
	row := q.db.QueryRow(ctx, latestRubricVersion, problemID)
	var i RubricVersion
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Version,
		&i.Notes,
		&i.ScoreIncrement,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const latestSolutionVersion = `-- name: LatestSolutionVersion :one
SELECT id, problem_id, version, content, created_by, created_at FROM reference_solution_versions WHERE problem_id = $1 ORDER BY version DESC LIMIT 1
`

func (q *Queries) LatestSolutionVersion(ctx context.Context, problemID int64) (ReferenceSolutionVersion, error) {
	row := q.db.QueryRow(ctx, latestSolutionVersion, problemID)
	var i ReferenceSolutionVersion
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Version,
		&i.Content,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listRubricCriteria = `-- name: ListRubricCriteria :many
SELECT id, rubric_version_id, position, description, points, partial_credit_notes FROM rubric_criteria WHERE rubric_version_id = $1 ORDER BY position
`

func (q *Queries) ListRubricCriteria(ctx context.Context, rubricVersionID int64) ([]RubricCriterium, error) {
	rows, err := q.db.Query(ctx, listRubricCriteria, rubricVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RubricCriterium
	for rows.Next() {
		var i RubricCriterium
		if err := rows.Scan(
			&i.ID,
			&i.RubricVersionID,
			&i.Position,
			&i.Description,
			&i.Points,
			&i.PartialCreditNotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRubricVersions = `-- name: ListRubricVersions :many
SELECT id, problem_id, version, notes, score_increment, created_by, created_at FROM rubric_versions WHERE problem_id = $1 ORDER BY version DESC
`

func (q *Queries) ListRubricVersions(ctx context.Context, problemID int64) ([]RubricVersion, error) {
	rows, err := q.db.Query(ctx, listRubricVersions, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RubricVersion
	for rows.Next() {
		var i RubricVersion
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.Version,
			&i.Notes,
			&i.ScoreIncrement,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSolutionVersions = `-- name: ListSolutionVersions :many
SELECT id, problem_id, version, content, created_by, created_at FROM reference_solution_versions WHERE problem_id = $1 ORDER BY version DESC
`

func (q *Queries) ListSolutionVersions(ctx context.Context, problemID int64) ([]ReferenceSolutionVersion, error) {
	rows, err := q.db.Query(ctx, listSolutionVersions, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReferenceSolutionVersion
	for rows.Next() {
		var i ReferenceSolutionVersion
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.Version,
			&i.Content,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
