// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const answerIDsForAssessment = `-- name: AnswerIDsForAssessment :many
SELECT a.id FROM answers a
JOIN students st ON st.id = a.student_id
WHERE a.assessment_id = $1
  AND st.withdrawn_at IS NULL
  AND EXISTS (SELECT 1 FROM answer_pages ap WHERE ap.answer_id = a.id)
ORDER BY a.id
`

// AnswerIDsForAssessment / AnswerIDsForProblem resolve a NEW run's scope to
// answer ids. Withdrawn students are excluded (roster-lifecycle plan
// 2026-07-10): launching a run after a 停修 must not spend tokens grading a
// student who will never receive results. Items of an already-launched run
// are untouched — the scope is resolved once at launch.
func (q *Queries) AnswerIDsForAssessment(ctx context.Context, assessmentID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, answerIDsForAssessment, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const answerIDsForProblem = `-- name: AnswerIDsForProblem :many
SELECT a.id FROM answers a
JOIN students st ON st.id = a.student_id
WHERE a.problem_id = $1
  AND st.withdrawn_at IS NULL
  AND EXISTS (SELECT 1 FROM answer_pages ap WHERE ap.answer_id = a.id)
ORDER BY a.id
`

func (q *Queries) AnswerIDsForProblem(ctx context.Context, problemID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, answerIDsForProblem, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const answersWithProblems = `-- name: AnswersWithProblems :many
SELECT id, problem_id FROM answers WHERE id = ANY ($1::bigint []) ORDER BY id
`

type AnswersWithProblemsRow struct {
	ID        int64 `json:"id"`
	ProblemID int64 `json:"problem_id"`
}

func (q *Queries) AnswersWithProblems(ctx context.Context, answerIds []int64) ([]AnswersWithProblemsRow, error) {
	rows, err := q.db.Query(ctx, answersWithProblems, answerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnswersWithProblemsRow
	for rows.Next() {
		var i AnswersWithProblemsRow
		if err := rows.Scan(&i.ID, &i.ProblemID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countMaskBlockersForAnswers = `-- name: CountMaskBlockersForAnswers :one
SELECT count(*)
FROM answer_pages ap
WHERE ap.answer_id = ANY ($1::bigint [])
  AND (ap.masked_image_ref IS NULL OR ap.mask_review_status <> 'accepted')
`

func (q *Queries) CountMaskBlockersForAnswers(ctx context.Context, answerIds []int64) (int64, error) {
	row := q.db.QueryRow(ctx, countMaskBlockersForAnswers, answerIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSucceededItemsForRun = `-- name: CountSucceededItemsForRun :one

SELECT count(*) FROM grading_run_items WHERE run_id = $1 AND state = 'succeeded'
`

// (SetOfficialForRunUnflagged removed in 0027: officials are derived from the
// assessment's final source by RecomputeOfficials — runs never set officials.)
// CountSucceededItemsForRun backs the final-source zero-leaf guard (A3): a
// completed run whose leaves are ALL failed/skipped can never produce a
// spot-check sample (createSpotCheckSample only pools state='succeeded'
// items), which would wedge publish behind an unreachable "review spot-check"
// call to action. Same state definition as RunItemStateCounts' "succeeded"
// bucket (the picker's "N succeeded" figure), so this check and that display
// can never disagree.
func (q *Queries) CountSucceededItemsForRun(ctx context.Context, runID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countSucceededItemsForRun, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO grading_runs (assessment_id, scope_kind, scope_id, method_version_id, execution_mode, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, assessment_id, scope_kind, scope_id, method_version_id, status, execution_mode, error, created_by, created_at, started_at, finished_at, cost_cap_usd
`

type CreateRunParams struct {
	AssessmentID    int64       `json:"assessment_id"`
	ScopeKind       string      `json:"scope_kind"`
	ScopeID         int64       `json:"scope_id"`
	MethodVersionID int64       `json:"method_version_id"`
	ExecutionMode   string      `json:"execution_mode"`
	CreatedBy       pgtype.Int8 `json:"created_by"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (GradingRun, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.AssessmentID,
		arg.ScopeKind,
		arg.ScopeID,
		arg.MethodVersionID,
		arg.ExecutionMode,
		arg.CreatedBy,
	)
	var i GradingRun
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.ScopeKind,
		&i.ScopeID,
		&i.MethodVersionID,
		&i.Status,
		&i.ExecutionMode,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CostCapUsd,
	)
	return i, err
}

const createRunItem = `-- name: CreateRunItem :one
INSERT INTO grading_run_items (run_id, answer_id, model_id, provider, rubric_version_id, reference_solution_version_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (run_id, answer_id, model_id) DO NOTHING
RETURNING id, run_id, answer_id, model_id, provider, state, attempts, error, record_id, updated_at, rubric_version_id, reference_solution_version_id
`

type CreateRunItemParams struct {
	RunID                      int64       `json:"run_id"`
	AnswerID                   int64       `json:"answer_id"`
	ModelID                    string      `json:"model_id"`
	Provider                   string      `json:"provider"`
	RubricVersionID            pgtype.Int8 `json:"rubric_version_id"`
	ReferenceSolutionVersionID pgtype.Int8 `json:"reference_solution_version_id"`
}

func (q *Queries) CreateRunItem(ctx context.Context, arg CreateRunItemParams) (GradingRunItem, error) {
	row := q.db.QueryRow(ctx, createRunItem,
		arg.RunID,
		arg.AnswerID,
		arg.ModelID,
		arg.Provider,
		arg.RubricVersionID,
		arg.ReferenceSolutionVersionID,
	)
	var i GradingRunItem
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.AnswerID,
		&i.ModelID,
		&i.Provider,
		&i.State,
		&i.Attempts,
		&i.Error,
		&i.RecordID,
		&i.UpdatedAt,
		&i.RubricVersionID,
		&i.ReferenceSolutionVersionID,
	)
	return i, err
}

const getRecordForLeaf = `-- name: GetRecordForLeaf :one
SELECT id, answer_id, run_id, source, provider, model_id, method_version_id, rubric_version_id, reference_solution_version_id, prompt_template_version_id, graded_image_shas, criterion_scores, total, comment, transcription, confidence, adjustments, raw_output, input_tokens, output_tokens, cost_usd, temperature, created_by, created_at, policy FROM grading_records
WHERE run_id = $1 AND answer_id = $2 AND model_id = $3
`

type GetRecordForLeafParams struct {
	RunID    pgtype.Int8 `json:"run_id"`
	AnswerID int64       `json:"answer_id"`
	ModelID  pgtype.Text `json:"model_id"`
}

func (q *Queries) GetRecordForLeaf(ctx context.Context, arg GetRecordForLeafParams) (GradingRecord, error) {
	row := q.db.QueryRow(ctx, getRecordForLeaf, arg.RunID, arg.AnswerID, arg.ModelID)
	var i GradingRecord
	err := row.Scan(
		&i.ID,
		&i.AnswerID,
		&i.RunID,
		&i.Source,
		&i.Provider,
		&i.ModelID,
		&i.MethodVersionID,
		&i.RubricVersionID,
		&i.ReferenceSolutionVersionID,
		&i.PromptTemplateVersionID,
		&i.GradedImageShas,
		&i.CriterionScores,
		&i.Total,
		&i.Comment,
		&i.Transcription,
		&i.Confidence,
		&i.Adjustments,
		&i.RawOutput,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CostUsd,
		&i.Temperature,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Policy,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, assessment_id, scope_kind, scope_id, method_version_id, status, execution_mode, error, created_by, created_at, started_at, finished_at, cost_cap_usd FROM grading_runs WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id int64) (GradingRun, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i GradingRun
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.ScopeKind,
		&i.ScopeID,
		&i.MethodVersionID,
		&i.Status,
		&i.ExecutionMode,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CostCapUsd,
	)
	return i, err
}

const getRunForUpdate = `-- name: GetRunForUpdate :one
SELECT id, assessment_id, scope_kind, scope_id, method_version_id, status, execution_mode, error, created_by, created_at, started_at, finished_at, cost_cap_usd FROM grading_runs WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetRunForUpdate(ctx context.Context, id int64) (GradingRun, error) {
	row := q.db.QueryRow(ctx, getRunForUpdate, id)
	var i GradingRun
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.ScopeKind,
		&i.ScopeID,
		&i.MethodVersionID,
		&i.Status,
		&i.ExecutionMode,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CostCapUsd,
	)
	return i, err
}

const getRunItem = `-- name: GetRunItem :one
SELECT id, run_id, answer_id, model_id, provider, state, attempts, error, record_id, updated_at, rubric_version_id, reference_solution_version_id FROM grading_run_items WHERE id = $1
`

func (q *Queries) GetRunItem(ctx context.Context, id int64) (GradingRunItem, error) {
	row := q.db.QueryRow(ctx, getRunItem, id)
	var i GradingRunItem
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.AnswerID,
		&i.ModelID,
		&i.Provider,
		&i.State,
		&i.Attempts,
		&i.Error,
		&i.RecordID,
		&i.UpdatedAt,
		&i.RubricVersionID,
		&i.ReferenceSolutionVersionID,
	)
	return i, err
}

const insertModelRecord = `-- name: InsertModelRecord :one
INSERT INTO grading_records (
    answer_id, run_id, source, provider, model_id, method_version_id,
    rubric_version_id, reference_solution_version_id, prompt_template_version_id,
    graded_image_shas, criterion_scores, total, comment, transcription, confidence,
    adjustments, raw_output, input_tokens, output_tokens, cost_usd, temperature, policy
)
VALUES ($1, $2, 'model', $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21)
ON CONFLICT (run_id, answer_id, model_id) WHERE run_id IS NOT NULL DO NOTHING
RETURNING id, answer_id, run_id, source, provider, model_id, method_version_id, rubric_version_id, reference_solution_version_id, prompt_template_version_id, graded_image_shas, criterion_scores, total, comment, transcription, confidence, adjustments, raw_output, input_tokens, output_tokens, cost_usd, temperature, created_by, created_at, policy
`

type InsertModelRecordParams struct {
	AnswerID                   int64          `json:"answer_id"`
	RunID                      pgtype.Int8    `json:"run_id"`
	Provider                   pgtype.Text    `json:"provider"`
	ModelID                    pgtype.Text    `json:"model_id"`
	MethodVersionID            pgtype.Int8    `json:"method_version_id"`
	RubricVersionID            int64          `json:"rubric_version_id"`
	ReferenceSolutionVersionID pgtype.Int8    `json:"reference_solution_version_id"`
	PromptTemplateVersionID    pgtype.Int8    `json:"prompt_template_version_id"`
	GradedImageShas            []string       `json:"graded_image_shas"`
	CriterionScores            []byte         `json:"criterion_scores"`
	Total                      pgtype.Numeric `json:"total"`
	Comment                    string         `json:"comment"`
	Transcription              pgtype.Text    `json:"transcription"`
	Confidence                 pgtype.Text    `json:"confidence"`
	Adjustments                []byte         `json:"adjustments"`
	RawOutput                  []byte         `json:"raw_output"`
	InputTokens                pgtype.Int4    `json:"input_tokens"`
	OutputTokens               pgtype.Int4    `json:"output_tokens"`
	CostUsd                    pgtype.Numeric `json:"cost_usd"`
	Temperature                pgtype.Float4  `json:"temperature"`
	Policy                     pgtype.Text    `json:"policy"`
}

func (q *Queries) InsertModelRecord(ctx context.Context, arg InsertModelRecordParams) (GradingRecord, error) {
	row := q.db.QueryRow(ctx, insertModelRecord,
		arg.AnswerID,
		arg.RunID,
		arg.Provider,
		arg.ModelID,
		arg.MethodVersionID,
		arg.RubricVersionID,
		arg.ReferenceSolutionVersionID,
		arg.PromptTemplateVersionID,
		arg.GradedImageShas,
		arg.CriterionScores,
		arg.Total,
		arg.Comment,
		arg.Transcription,
		arg.Confidence,
		arg.Adjustments,
		arg.RawOutput,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostUsd,
		arg.Temperature,
		arg.Policy,
	)
	var i GradingRecord
	err := row.Scan(
		&i.ID,
		&i.AnswerID,
		&i.RunID,
		&i.Source,
		&i.Provider,
		&i.ModelID,
		&i.MethodVersionID,
		&i.RubricVersionID,
		&i.ReferenceSolutionVersionID,
		&i.PromptTemplateVersionID,
		&i.GradedImageShas,
		&i.CriterionScores,
		&i.Total,
		&i.Comment,
		&i.Transcription,
		&i.Confidence,
		&i.Adjustments,
		&i.RawOutput,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CostUsd,
		&i.Temperature,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Policy,
	)
	return i, err
}

const isFinalRunSelected = `-- name: IsFinalRunSelected :one
SELECT EXISTS (SELECT 1 FROM assessments WHERE final_run_id = $1)
`

func (q *Queries) IsFinalRunSelected(ctx context.Context, finalRunID pgtype.Int8) (bool, error) {
	row := q.db.QueryRow(ctx, isFinalRunSelected, finalRunID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const latestCompletedRunForMethod = `-- name: LatestCompletedRunForMethod :one
SELECT r.id, r.assessment_id, r.scope_kind, r.scope_id, r.method_version_id, r.status, r.execution_mode, r.error, r.created_by, r.created_at, r.started_at, r.finished_at, r.cost_cap_usd
FROM grading_runs r
JOIN grading_method_versions mv ON mv.id = r.method_version_id
WHERE r.assessment_id = $1
  AND mv.method_id = $2
  AND r.status = 'completed'
ORDER BY r.id DESC
LIMIT 1
`

type LatestCompletedRunForMethodParams struct {
	AssessmentID int64 `json:"assessment_id"`
	MethodID     int64 `json:"method_id"`
}

// LatestCompletedRunForMethod anchors the publish-time spot-check gate (0027):
// when the final source is a single method, its most recent completed run's
// sample must be reviewed or waived before results can go out.
func (q *Queries) LatestCompletedRunForMethod(ctx context.Context, arg LatestCompletedRunForMethodParams) (GradingRun, error) {
	row := q.db.QueryRow(ctx, latestCompletedRunForMethod, arg.AssessmentID, arg.MethodID)
	var i GradingRun
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.ScopeKind,
		&i.ScopeID,
		&i.MethodVersionID,
		&i.Status,
		&i.ExecutionMode,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CostCapUsd,
	)
	return i, err
}

const listRunItems = `-- name: ListRunItems :many
SELECT i.id, i.run_id, i.answer_id, i.model_id, i.provider, i.state, i.attempts, i.error, i.record_id, i.updated_at, i.rubric_version_id, i.reference_solution_version_id, st.student_id, p.number AS problem_number
FROM grading_run_items i
JOIN answers a ON a.id = i.answer_id
JOIN students st ON st.id = a.student_id
JOIN problems p ON p.id = a.problem_id
WHERE i.run_id = $1
ORDER BY i.id
LIMIT $2
`

type ListRunItemsParams struct {
	RunID     int64 `json:"run_id"`
	ItemLimit int32 `json:"item_limit"`
}

type ListRunItemsRow struct {
	ID                         int64              `json:"id"`
	RunID                      int64              `json:"run_id"`
	AnswerID                   int64              `json:"answer_id"`
	ModelID                    string             `json:"model_id"`
	Provider                   string             `json:"provider"`
	State                      string             `json:"state"`
	Attempts                   int32              `json:"attempts"`
	Error                      pgtype.Text        `json:"error"`
	RecordID                   pgtype.Int8        `json:"record_id"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	RubricVersionID            pgtype.Int8        `json:"rubric_version_id"`
	ReferenceSolutionVersionID pgtype.Int8        `json:"reference_solution_version_id"`
	StudentID                  string             `json:"student_id"`
	ProblemNumber              int32              `json:"problem_number"`
}

// ListRunItems returns every item for the run, capped at sqlc.arg(item_limit)
// (F20: the run-detail poll must not pull an unbounded ~1800-row table by
// default; handleGetRun uses this only for the explicit `?all=1` view and
// echoes a truncated flag when the cap is hit). Callers that need the true
// unfiltered set for driving logic (not HTTP responses) pass a high cap.
func (q *Queries) ListRunItems(ctx context.Context, arg ListRunItemsParams) ([]ListRunItemsRow, error) {
	rows, err := q.db.Query(ctx, listRunItems, arg.RunID, arg.ItemLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunItemsRow
	for rows.Next() {
		var i ListRunItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.AnswerID,
			&i.ModelID,
			&i.Provider,
			&i.State,
			&i.Attempts,
			&i.Error,
			&i.RecordID,
			&i.UpdatedAt,
			&i.RubricVersionID,
			&i.ReferenceSolutionVersionID,
			&i.StudentID,
			&i.ProblemNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunItemsInteresting = `-- name: ListRunItemsInteresting :many
SELECT i.id, i.run_id, i.answer_id, i.model_id, i.provider, i.state, i.attempts, i.error, i.record_id, i.updated_at, i.rubric_version_id, i.reference_solution_version_id, st.student_id, p.number AS problem_number
FROM grading_run_items i
JOIN answers a ON a.id = i.answer_id
JOIN students st ON st.id = a.student_id
JOIN problems p ON p.id = a.problem_id
WHERE i.run_id = $1 AND i.state IN ('failed', 'running')
ORDER BY i.id
LIMIT $2
`

type ListRunItemsInterestingParams struct {
	RunID     int64 `json:"run_id"`
	ItemLimit int32 `json:"item_limit"`
}

type ListRunItemsInterestingRow struct {
	ID                         int64              `json:"id"`
	RunID                      int64              `json:"run_id"`
	AnswerID                   int64              `json:"answer_id"`
	ModelID                    string             `json:"model_id"`
	Provider                   string             `json:"provider"`
	State                      string             `json:"state"`
	Attempts                   int32              `json:"attempts"`
	Error                      pgtype.Text        `json:"error"`
	RecordID                   pgtype.Int8        `json:"record_id"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	RubricVersionID            pgtype.Int8        `json:"rubric_version_id"`
	ReferenceSolutionVersionID pgtype.Int8        `json:"reference_solution_version_id"`
	StudentID                  string             `json:"student_id"`
	ProblemNumber              int32              `json:"problem_number"`
}

// ListRunItemsInteresting is handleGetRun's default (F20): only items a TA
// would act on (failed needs retry, running is the live edge) plus the
// GROUP-BY counts already cover the aggregate progress bar. Capped the same
// way as ListRunItems for symmetry, though in practice failed+running is
// always a small slice of a run.
func (q *Queries) ListRunItemsInteresting(ctx context.Context, arg ListRunItemsInterestingParams) ([]ListRunItemsInterestingRow, error) {
	rows, err := q.db.Query(ctx, listRunItemsInteresting, arg.RunID, arg.ItemLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunItemsInterestingRow
	for rows.Next() {
		var i ListRunItemsInterestingRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.AnswerID,
			&i.ModelID,
			&i.Provider,
			&i.State,
			&i.Attempts,
			&i.Error,
			&i.RecordID,
			&i.UpdatedAt,
			&i.RubricVersionID,
			&i.ReferenceSolutionVersionID,
			&i.StudentID,
			&i.ProblemNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT r.id, r.assessment_id, r.scope_kind, r.scope_id, r.method_version_id, r.status, r.execution_mode, r.error, r.created_by, r.created_at, r.started_at, r.finished_at, r.cost_cap_usd, m.name AS method_name, mv.version AS method_version, a.name AS assessment_name
FROM grading_runs r
JOIN grading_method_versions mv ON mv.id = r.method_version_id
JOIN grading_methods m ON m.id = mv.method_id
JOIN assessments a ON a.id = r.assessment_id
WHERE ($1::bigint IS NULL OR r.assessment_id = $1)
  AND ($2::text IS NULL OR r.status = $2)
ORDER BY r.id DESC
LIMIT $3
`

type ListRunsParams struct {
	AssessmentID pgtype.Int8 `json:"assessment_id"`
	Status       pgtype.Text `json:"status"`
	RowLimit     int32       `json:"row_limit"`
}

type ListRunsRow struct {
	ID              int64              `json:"id"`
	AssessmentID    int64              `json:"assessment_id"`
	ScopeKind       string             `json:"scope_kind"`
	ScopeID         int64              `json:"scope_id"`
	MethodVersionID int64              `json:"method_version_id"`
	Status          string             `json:"status"`
	ExecutionMode   string             `json:"execution_mode"`
	Error           pgtype.Text        `json:"error"`
	CreatedBy       pgtype.Int8        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
	CostCapUsd      pgtype.Numeric     `json:"cost_cap_usd"`
	MethodName      string             `json:"method_name"`
	MethodVersion   int32              `json:"method_version"`
	AssessmentName  string             `json:"assessment_name"`
}

// ListRuns is the runs-page list; the narg filters are the TA-facing
// assessment/status dropdowns (NULL = no filter), applied here rather than
// client-side because the list is capped at row_limit rows.
func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]ListRunsRow, error) {
	rows, err := q.db.Query(ctx, listRuns, arg.AssessmentID, arg.Status, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunsRow
	for rows.Next() {
		var i ListRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.ScopeKind,
			&i.ScopeID,
			&i.MethodVersionID,
			&i.Status,
			&i.ExecutionMode,
			&i.Error,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CostCapUsd,
			&i.MethodName,
			&i.MethodVersion,
			&i.AssessmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markItemRunning = `-- name: MarkItemRunning :one
UPDATE grading_run_items
SET state = 'running', attempts = attempts + 1, updated_at = now()
WHERE id = $1
RETURNING id, run_id, answer_id, model_id, provider, state, attempts, error, record_id, updated_at, rubric_version_id, reference_solution_version_id
`

func (q *Queries) MarkItemRunning(ctx context.Context, id int64) (GradingRunItem, error) {
	row := q.db.QueryRow(ctx, markItemRunning, id)
	var i GradingRunItem
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.AnswerID,
		&i.ModelID,
		&i.Provider,
		&i.State,
		&i.Attempts,
		&i.Error,
		&i.RecordID,
		&i.UpdatedAt,
		&i.RubricVersionID,
		&i.ReferenceSolutionVersionID,
	)
	return i, err
}

const markItemTerminal = `-- name: MarkItemTerminal :one
UPDATE grading_run_items
SET state = $2, error = $3, record_id = $4, updated_at = now()
WHERE id = $1
RETURNING id, run_id, answer_id, model_id, provider, state, attempts, error, record_id, updated_at, rubric_version_id, reference_solution_version_id
`

type MarkItemTerminalParams struct {
	ID       int64       `json:"id"`
	State    string      `json:"state"`
	Error    pgtype.Text `json:"error"`
	RecordID pgtype.Int8 `json:"record_id"`
}

func (q *Queries) MarkItemTerminal(ctx context.Context, arg MarkItemTerminalParams) (GradingRunItem, error) {
	row := q.db.QueryRow(ctx, markItemTerminal,
		arg.ID,
		arg.State,
		arg.Error,
		arg.RecordID,
	)
	var i GradingRunItem
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.AnswerID,
		&i.ModelID,
		&i.Provider,
		&i.State,
		&i.Attempts,
		&i.Error,
		&i.RecordID,
		&i.UpdatedAt,
		&i.RubricVersionID,
		&i.ReferenceSolutionVersionID,
	)
	return i, err
}

const maybeCompleteRun = `-- name: MaybeCompleteRun :execrows
UPDATE grading_runs
SET status = 'completed', finished_at = now()
WHERE grading_runs.id = $1 AND status = 'running'
  AND NOT EXISTS (SELECT 1 FROM grading_run_items i WHERE i.run_id = $1 AND i.state IN ('pending', 'running'))
`

func (q *Queries) MaybeCompleteRun(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, maybeCompleteRun, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetFailedItems = `-- name: ResetFailedItems :many
UPDATE grading_run_items
SET state = 'pending', error = NULL, updated_at = now()
WHERE run_id = $1 AND state = 'failed'
RETURNING id
`

func (q *Queries) ResetFailedItems(ctx context.Context, runID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, resetFailedItems, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runItemStateCounts = `-- name: RunItemStateCounts :many
SELECT state, count(*) AS n FROM grading_run_items WHERE run_id = $1 GROUP BY state
`

type RunItemStateCountsRow struct {
	State string `json:"state"`
	N     int64  `json:"n"`
}

func (q *Queries) RunItemStateCounts(ctx context.Context, runID int64) ([]RunItemStateCountsRow, error) {
	rows, err := q.db.Query(ctx, runItemStateCounts, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunItemStateCountsRow
	for rows.Next() {
		var i RunItemStateCountsRow
		if err := rows.Scan(&i.State, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRunStatus = `-- name: SetRunStatus :one
UPDATE grading_runs
SET status = $2,
    error = $3,
    started_at = CASE WHEN $2 = 'running' AND started_at IS NULL THEN now() ELSE started_at END,
    finished_at = CASE WHEN $2 IN ('completed', 'cancelled', 'failed') THEN now() ELSE finished_at END
WHERE id = $1
RETURNING id, assessment_id, scope_kind, scope_id, method_version_id, status, execution_mode, error, created_by, created_at, started_at, finished_at, cost_cap_usd
`

type SetRunStatusParams struct {
	ID     int64       `json:"id"`
	Status string      `json:"status"`
	Error  pgtype.Text `json:"error"`
}

func (q *Queries) SetRunStatus(ctx context.Context, arg SetRunStatusParams) (GradingRun, error) {
	row := q.db.QueryRow(ctx, setRunStatus, arg.ID, arg.Status, arg.Error)
	var i GradingRun
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.ScopeKind,
		&i.ScopeID,
		&i.MethodVersionID,
		&i.Status,
		&i.ExecutionMode,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CostCapUsd,
	)
	return i, err
}
