// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scan.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignScanPage = `-- name: AssignScanPage :exec

UPDATE scan_pages
SET assigned_student_id = $2, assigned_problem_id = $3, assigned_by = $4,
    assigned_at = now(), parked_reason = NULL, parked_against = NULL,
    park_student_id = NULL, park_problem_id = NULL,
    discarded_at = NULL, discard_reason = NULL, error = NULL, updated_at = now()
WHERE id = $1
`

type AssignScanPageParams struct {
	ID                int64       `json:"id"`
	AssignedStudentID pgtype.Int8 `json:"assigned_student_id"`
	AssignedProblemID pgtype.Int8 `json:"assigned_problem_id"`
	AssignedBy        pgtype.Int8 `json:"assigned_by"`
}

// ---- pages: assignment & lifecycle ----
// AssignScanPage clears parked/discard/error state: assignment (auto or manual)
// always wins over a stale park or error, and a TA who assigns by eye after an
// OCR outage must not be blocked by a lingering error.
func (q *Queries) AssignScanPage(ctx context.Context, arg AssignScanPageParams) error {
	_, err := q.db.Exec(ctx, assignScanPage,
		arg.ID,
		arg.AssignedStudentID,
		arg.AssignedProblemID,
		arg.AssignedBy,
	)
	return err
}

const clearPromotionErrorsForAssessment = `-- name: ClearPromotionErrorsForAssessment :exec
UPDATE scan_pages
SET error = NULL, updated_at = now()
WHERE assessment_id = $1
  AND assigned_student_id IS NOT NULL
  AND submission_id IS NULL
  AND discarded_at IS NULL
  AND error LIKE 'promotion rejected:%'
`

// ClearPromotionErrorsForAssessment lets a Finalize re-run re-attempt pages whose
// error came from a previous promotion ("promotion rejected: " prefix) without
// clearing genuine render/OCR errors.
func (q *Queries) ClearPromotionErrorsForAssessment(ctx context.Context, assessmentID int64) error {
	_, err := q.db.Exec(ctx, clearPromotionErrorsForAssessment, assessmentID)
	return err
}

const clearScanPageError = `-- name: ClearScanPageError :exec
UPDATE scan_pages SET error = NULL, updated_at = now() WHERE id = $1
`

func (q *Queries) ClearScanPageError(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, clearScanPageError, id)
	return err
}

const countMissingCells = `-- name: CountMissingCells :one
SELECT count(*)
FROM students st
CROSS JOIN problems p
WHERE p.assessment_id = $1
  AND st.withdrawn_at IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM scan_pages sp
    WHERE sp.assessment_id = $1
      AND sp.assigned_student_id = st.id AND sp.assigned_problem_id = p.id
      AND sp.discarded_at IS NULL
  )
  AND NOT EXISTS (
    SELECT 1 FROM submissions s
    WHERE s.assessment_id = $1
      AND s.student_id = st.id
      AND s.superseded_by IS NULL AND s.retracted_at IS NULL
      AND (s.problem_id IS NULL OR s.problem_id = p.id)
  )
`

// A cell is missing when an active student × problem has neither a live assigned
// page nor a live submission covering it (per-problem, or whole-assessment).
// Count only in the finalize gate (PII discipline).
func (q *Queries) CountMissingCells(ctx context.Context, assessmentID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countMissingCells, assessmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIDRegion = `-- name: CreateIDRegion :one
INSERT INTO id_regions (assessment_id, kind, x, y, w, h, color, padding)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, assessment_id, x, y, w, h, color, padding, created_at, kind
`

type CreateIDRegionParams struct {
	AssessmentID int64   `json:"assessment_id"`
	Kind         string  `json:"kind"`
	X            float32 `json:"x"`
	Y            float32 `json:"y"`
	W            float32 `json:"w"`
	H            float32 `json:"h"`
	Color        string  `json:"color"`
	Padding      float32 `json:"padding"`
}

func (q *Queries) CreateIDRegion(ctx context.Context, arg CreateIDRegionParams) (IDRegion, error) {
	row := q.db.QueryRow(ctx, createIDRegion,
		arg.AssessmentID,
		arg.Kind,
		arg.X,
		arg.Y,
		arg.W,
		arg.H,
		arg.Color,
		arg.Padding,
	)
	var i IDRegion
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.X,
		&i.Y,
		&i.W,
		&i.H,
		&i.Color,
		&i.Padding,
		&i.CreatedAt,
		&i.Kind,
	)
	return i, err
}

const createScanBatch = `-- name: CreateScanBatch :one


INSERT INTO scan_batches (assessment_id, ocr_enabled, ocr_provider, ocr_model, source_ref, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, assessment_id, ocr_enabled, ocr_provider, ocr_model, source_ref, created_by, created_at
`

type CreateScanBatchParams struct {
	AssessmentID int64       `json:"assessment_id"`
	OcrEnabled   bool        `json:"ocr_enabled"`
	OcrProvider  pgtype.Text `json:"ocr_provider"`
	OcrModel     pgtype.Text `json:"ocr_model"`
	SourceRef    pgtype.Text `json:"source_ref"`
	CreatedBy    pgtype.Int8 `json:"created_by"`
}

// Page-level scan intake queries (design spec 2026-07-04). All OCR text columns
// hold PII (D14): callers select them only into DB-bound rows or staff-facing
// JSON, never into logs, job args, or error strings.
// ---- batches ----
func (q *Queries) CreateScanBatch(ctx context.Context, arg CreateScanBatchParams) (ScanBatch, error) {
	row := q.db.QueryRow(ctx, createScanBatch,
		arg.AssessmentID,
		arg.OcrEnabled,
		arg.OcrProvider,
		arg.OcrModel,
		arg.SourceRef,
		arg.CreatedBy,
	)
	var i ScanBatch
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.OcrEnabled,
		&i.OcrProvider,
		&i.OcrModel,
		&i.SourceRef,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createScanPage = `-- name: CreateScanPage :one

INSERT INTO scan_pages (source_id, batch_id, assessment_id, page_index)
VALUES ($1, $2, $3, $4)
ON CONFLICT (source_id, page_index) DO NOTHING
RETURNING id, source_id, batch_id, assessment_id, page_index, image_ref, image_sha256, image_width, image_height, student_id_crop_ref, name_crop_ref, problem_crop_ref, ocr_student_id, ocr_name, ocr_problem, ocr_student_id_legible, ocr_name_legible, ocr_problem_legible, ocr_engine, identified_at, proposed_student_id, proposed_problem_id, proposal_source, assigned_student_id, assigned_problem_id, assigned_by, assigned_at, force_promote, parked_reason, parked_against, discarded_at, discard_reason, submission_id, error, attempts, created_at, updated_at, park_student_id, park_problem_id, text_loss_runs
`

type CreateScanPageParams struct {
	SourceID     int64 `json:"source_id"`
	BatchID      int64 `json:"batch_id"`
	AssessmentID int64 `json:"assessment_id"`
	PageIndex    int32 `json:"page_index"`
}

// ---- pages: creation & pipeline writes ----
// CreateScanPage is idempotent per source page (UNIQUE(source_id, page_index)):
// a redelivered scan.split re-inserts harmlessly.
func (q *Queries) CreateScanPage(ctx context.Context, arg CreateScanPageParams) (ScanPage, error) {
	row := q.db.QueryRow(ctx, createScanPage,
		arg.SourceID,
		arg.BatchID,
		arg.AssessmentID,
		arg.PageIndex,
	)
	var i ScanPage
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.BatchID,
		&i.AssessmentID,
		&i.PageIndex,
		&i.ImageRef,
		&i.ImageSha256,
		&i.ImageWidth,
		&i.ImageHeight,
		&i.StudentIDCropRef,
		&i.NameCropRef,
		&i.ProblemCropRef,
		&i.OcrStudentID,
		&i.OcrName,
		&i.OcrProblem,
		&i.OcrStudentIDLegible,
		&i.OcrNameLegible,
		&i.OcrProblemLegible,
		&i.OcrEngine,
		&i.IdentifiedAt,
		&i.ProposedStudentID,
		&i.ProposedProblemID,
		&i.ProposalSource,
		&i.AssignedStudentID,
		&i.AssignedProblemID,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.ForcePromote,
		&i.ParkedReason,
		&i.ParkedAgainst,
		&i.DiscardedAt,
		&i.DiscardReason,
		&i.SubmissionID,
		&i.Error,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParkStudentID,
		&i.ParkProblemID,
		&i.TextLossRuns,
	)
	return i, err
}

const createScanSource = `-- name: CreateScanSource :one

INSERT INTO scan_sources (batch_id, original_filename, source_ref, source_sha256, source_kind)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (batch_id, source_sha256) DO NOTHING
RETURNING id, batch_id, original_filename, source_ref, source_sha256, source_kind, page_count, error, created_at
`

type CreateScanSourceParams struct {
	BatchID          int64  `json:"batch_id"`
	OriginalFilename string `json:"original_filename"`
	SourceRef        string `json:"source_ref"`
	SourceSha256     string `json:"source_sha256"`
	SourceKind       string `json:"source_kind"`
}

// ---- sources ----
// CreateScanSource is idempotent within a batch: UNIQUE(batch_id, source_sha256)
// collapses duplicate uploads; ON CONFLICT DO NOTHING returns no row for a
// duplicate (sqlc :one surfaces pgx.ErrNoRows) — caller treats as "skipped".
func (q *Queries) CreateScanSource(ctx context.Context, arg CreateScanSourceParams) (ScanSource, error) {
	row := q.db.QueryRow(ctx, createScanSource,
		arg.BatchID,
		arg.OriginalFilename,
		arg.SourceRef,
		arg.SourceSha256,
		arg.SourceKind,
	)
	var i ScanSource
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.OriginalFilename,
		&i.SourceRef,
		&i.SourceSha256,
		&i.SourceKind,
		&i.PageCount,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const deleteIDRegions = `-- name: DeleteIDRegions :exec
DELETE FROM id_regions WHERE assessment_id = $1
`

func (q *Queries) DeleteIDRegions(ctx context.Context, assessmentID int64) error {
	_, err := q.db.Exec(ctx, deleteIDRegions, assessmentID)
	return err
}

const discardScanPage = `-- name: DiscardScanPage :exec
UPDATE scan_pages
SET discarded_at = now(), discard_reason = $2, parked_reason = NULL,
    parked_against = NULL, park_student_id = NULL, park_problem_id = NULL,
    error = NULL, updated_at = now()
WHERE id = $1
`

type DiscardScanPageParams struct {
	ID            int64       `json:"id"`
	DiscardReason pgtype.Text `json:"discard_reason"`
}

func (q *Queries) DiscardScanPage(ctx context.Context, arg DiscardScanPageParams) error {
	_, err := q.db.Exec(ctx, discardScanPage, arg.ID, arg.DiscardReason)
	return err
}

const getScanBatch = `-- name: GetScanBatch :one
SELECT id, assessment_id, ocr_enabled, ocr_provider, ocr_model, source_ref, created_by, created_at FROM scan_batches WHERE id = $1
`

func (q *Queries) GetScanBatch(ctx context.Context, id int64) (ScanBatch, error) {
	row := q.db.QueryRow(ctx, getScanBatch, id)
	var i ScanBatch
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.OcrEnabled,
		&i.OcrProvider,
		&i.OcrModel,
		&i.SourceRef,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getScanPage = `-- name: GetScanPage :one
SELECT id, source_id, batch_id, assessment_id, page_index, image_ref, image_sha256, image_width, image_height, student_id_crop_ref, name_crop_ref, problem_crop_ref, ocr_student_id, ocr_name, ocr_problem, ocr_student_id_legible, ocr_name_legible, ocr_problem_legible, ocr_engine, identified_at, proposed_student_id, proposed_problem_id, proposal_source, assigned_student_id, assigned_problem_id, assigned_by, assigned_at, force_promote, parked_reason, parked_against, discarded_at, discard_reason, submission_id, error, attempts, created_at, updated_at, park_student_id, park_problem_id, text_loss_runs FROM scan_pages WHERE id = $1
`

func (q *Queries) GetScanPage(ctx context.Context, id int64) (ScanPage, error) {
	row := q.db.QueryRow(ctx, getScanPage, id)
	var i ScanPage
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.BatchID,
		&i.AssessmentID,
		&i.PageIndex,
		&i.ImageRef,
		&i.ImageSha256,
		&i.ImageWidth,
		&i.ImageHeight,
		&i.StudentIDCropRef,
		&i.NameCropRef,
		&i.ProblemCropRef,
		&i.OcrStudentID,
		&i.OcrName,
		&i.OcrProblem,
		&i.OcrStudentIDLegible,
		&i.OcrNameLegible,
		&i.OcrProblemLegible,
		&i.OcrEngine,
		&i.IdentifiedAt,
		&i.ProposedStudentID,
		&i.ProposedProblemID,
		&i.ProposalSource,
		&i.AssignedStudentID,
		&i.AssignedProblemID,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.ForcePromote,
		&i.ParkedReason,
		&i.ParkedAgainst,
		&i.DiscardedAt,
		&i.DiscardReason,
		&i.SubmissionID,
		&i.Error,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParkStudentID,
		&i.ParkProblemID,
		&i.TextLossRuns,
	)
	return i, err
}

const getScanPageForUpdate = `-- name: GetScanPageForUpdate :one
SELECT id, source_id, batch_id, assessment_id, page_index, image_ref, image_sha256, image_width, image_height, student_id_crop_ref, name_crop_ref, problem_crop_ref, ocr_student_id, ocr_name, ocr_problem, ocr_student_id_legible, ocr_name_legible, ocr_problem_legible, ocr_engine, identified_at, proposed_student_id, proposed_problem_id, proposal_source, assigned_student_id, assigned_problem_id, assigned_by, assigned_at, force_promote, parked_reason, parked_against, discarded_at, discard_reason, submission_id, error, attempts, created_at, updated_at, park_student_id, park_problem_id, text_loss_runs FROM scan_pages WHERE id = $1 FOR UPDATE
`

// GetScanPageForUpdate re-reads a page INSIDE a mutating transaction, locking
// the row: the manual mutations' promoted-guard runs first on a plain pre-tx
// snapshot, and an in-flight promote job can link a submission between that
// snapshot and the mutation's own writes. Re-checking on the locked row turns
// that race into a clean 409 instead of silently mutating a promoted page.
func (q *Queries) GetScanPageForUpdate(ctx context.Context, id int64) (ScanPage, error) {
	row := q.db.QueryRow(ctx, getScanPageForUpdate, id)
	var i ScanPage
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.BatchID,
		&i.AssessmentID,
		&i.PageIndex,
		&i.ImageRef,
		&i.ImageSha256,
		&i.ImageWidth,
		&i.ImageHeight,
		&i.StudentIDCropRef,
		&i.NameCropRef,
		&i.ProblemCropRef,
		&i.OcrStudentID,
		&i.OcrName,
		&i.OcrProblem,
		&i.OcrStudentIDLegible,
		&i.OcrNameLegible,
		&i.OcrProblemLegible,
		&i.OcrEngine,
		&i.IdentifiedAt,
		&i.ProposedStudentID,
		&i.ProposedProblemID,
		&i.ProposalSource,
		&i.AssignedStudentID,
		&i.AssignedProblemID,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.ForcePromote,
		&i.ParkedReason,
		&i.ParkedAgainst,
		&i.DiscardedAt,
		&i.DiscardReason,
		&i.SubmissionID,
		&i.Error,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParkStudentID,
		&i.ParkProblemID,
		&i.TextLossRuns,
	)
	return i, err
}

const getScanSource = `-- name: GetScanSource :one
SELECT id, batch_id, original_filename, source_ref, source_sha256, source_kind, page_count, error, created_at FROM scan_sources WHERE id = $1
`

func (q *Queries) GetScanSource(ctx context.Context, id int64) (ScanSource, error) {
	row := q.db.QueryRow(ctx, getScanSource, id)
	var i ScanSource
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.OriginalFilename,
		&i.SourceRef,
		&i.SourceSha256,
		&i.SourceKind,
		&i.PageCount,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const linkScanPagePromotion = `-- name: LinkScanPagePromotion :execrows
UPDATE scan_pages
SET submission_id = $2, updated_at = now()
WHERE id = $1 AND submission_id IS NULL AND discarded_at IS NULL
  AND assigned_student_id = $3 AND assigned_problem_id = $4
`

type LinkScanPagePromotionParams struct {
	ID                int64       `json:"id"`
	SubmissionID      pgtype.Int8 `json:"submission_id"`
	AssignedStudentID pgtype.Int8 `json:"assigned_student_id"`
	AssignedProblemID pgtype.Int8 `json:"assigned_problem_id"`
}

// LinkScanPagePromotion is the promote job's success-path link, run INSIDE the
// same transaction that creates the submission (ingest's LinkInTx seam). It
// links ONLY when the page still carries the exact assignment the promote job
// read and is still unpromoted and undiscarded: a concurrent reassign/
// unassign/discard makes this 0 rows, which aborts the whole promote
// transaction — the wrong-cell submission never becomes visible. Mirrors the
// error-path race guard on SetScanPagePromotionError.
func (q *Queries) LinkScanPagePromotion(ctx context.Context, arg LinkScanPagePromotionParams) (int64, error) {
	result, err := q.db.Exec(ctx, linkScanPagePromotion,
		arg.ID,
		arg.SubmissionID,
		arg.AssignedStudentID,
		arg.AssignedProblemID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActiveStudents = `-- name: ListActiveStudents :many

SELECT id, student_id, name, email, created_at, updated_at, withdrawn_at FROM students WHERE withdrawn_at IS NULL ORDER BY student_id
`

// ---- roster ----
// ListActiveStudents is the matching candidate set: withdrawn students are never
// proposed (D23).
func (q *Queries) ListActiveStudents(ctx context.Context) ([]Student, error) {
	rows, err := q.db.Query(ctx, listActiveStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WithdrawnAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignedUnpromotedPages = `-- name: ListAssignedUnpromotedPages :many

SELECT id, source_id, batch_id, assessment_id, page_index, image_ref, image_sha256, image_width, image_height, student_id_crop_ref, name_crop_ref, problem_crop_ref, ocr_student_id, ocr_name, ocr_problem, ocr_student_id_legible, ocr_name_legible, ocr_problem_legible, ocr_engine, identified_at, proposed_student_id, proposed_problem_id, proposal_source, assigned_student_id, assigned_problem_id, assigned_by, assigned_at, force_promote, parked_reason, parked_against, discarded_at, discard_reason, submission_id, error, attempts, created_at, updated_at, park_student_id, park_problem_id, text_loss_runs FROM scan_pages
WHERE assessment_id = $1 AND assigned_student_id IS NOT NULL
  AND discarded_at IS NULL AND submission_id IS NULL
ORDER BY id
`

// ---- finalize / promote ----
func (q *Queries) ListAssignedUnpromotedPages(ctx context.Context, assessmentID int64) ([]ScanPage, error) {
	rows, err := q.db.Query(ctx, listAssignedUnpromotedPages, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanPage
	for rows.Next() {
		var i ScanPage
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.BatchID,
			&i.AssessmentID,
			&i.PageIndex,
			&i.ImageRef,
			&i.ImageSha256,
			&i.ImageWidth,
			&i.ImageHeight,
			&i.StudentIDCropRef,
			&i.NameCropRef,
			&i.ProblemCropRef,
			&i.OcrStudentID,
			&i.OcrName,
			&i.OcrProblem,
			&i.OcrStudentIDLegible,
			&i.OcrNameLegible,
			&i.OcrProblemLegible,
			&i.OcrEngine,
			&i.IdentifiedAt,
			&i.ProposedStudentID,
			&i.ProposedProblemID,
			&i.ProposalSource,
			&i.AssignedStudentID,
			&i.AssignedProblemID,
			&i.AssignedBy,
			&i.AssignedAt,
			&i.ForcePromote,
			&i.ParkedReason,
			&i.ParkedAgainst,
			&i.DiscardedAt,
			&i.DiscardReason,
			&i.SubmissionID,
			&i.Error,
			&i.Attempts,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParkStudentID,
			&i.ParkProblemID,
			&i.TextLossRuns,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listErroredPagesForBatch = `-- name: ListErroredPagesForBatch :many
SELECT id, source_id, batch_id, assessment_id, page_index, image_ref, image_sha256, image_width, image_height, student_id_crop_ref, name_crop_ref, problem_crop_ref, ocr_student_id, ocr_name, ocr_problem, ocr_student_id_legible, ocr_name_legible, ocr_problem_legible, ocr_engine, identified_at, proposed_student_id, proposed_problem_id, proposal_source, assigned_student_id, assigned_problem_id, assigned_by, assigned_at, force_promote, parked_reason, parked_against, discarded_at, discard_reason, submission_id, error, attempts, created_at, updated_at, park_student_id, park_problem_id, text_loss_runs FROM scan_pages
WHERE batch_id = $1 AND error IS NOT NULL AND error <> ''
ORDER BY id
`

// ListErroredPagesForBatch feeds the batch-level bulk recovery actions
// (retry-errored / discard-errored): every page of the batch currently in
// derived state "error" (error is the highest-precedence state, D2).
func (q *Queries) ListErroredPagesForBatch(ctx context.Context, batchID int64) ([]ScanPage, error) {
	rows, err := q.db.Query(ctx, listErroredPagesForBatch, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanPage
	for rows.Next() {
		var i ScanPage
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.BatchID,
			&i.AssessmentID,
			&i.PageIndex,
			&i.ImageRef,
			&i.ImageSha256,
			&i.ImageWidth,
			&i.ImageHeight,
			&i.StudentIDCropRef,
			&i.NameCropRef,
			&i.ProblemCropRef,
			&i.OcrStudentID,
			&i.OcrName,
			&i.OcrProblem,
			&i.OcrStudentIDLegible,
			&i.OcrNameLegible,
			&i.OcrProblemLegible,
			&i.OcrEngine,
			&i.IdentifiedAt,
			&i.ProposedStudentID,
			&i.ProposedProblemID,
			&i.ProposalSource,
			&i.AssignedStudentID,
			&i.AssignedProblemID,
			&i.AssignedBy,
			&i.AssignedAt,
			&i.ForcePromote,
			&i.ParkedReason,
			&i.ParkedAgainst,
			&i.DiscardedAt,
			&i.DiscardReason,
			&i.SubmissionID,
			&i.Error,
			&i.Attempts,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParkStudentID,
			&i.ParkProblemID,
			&i.TextLossRuns,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIDRegions = `-- name: ListIDRegions :many

SELECT id, assessment_id, x, y, w, h, color, padding, created_at, kind FROM id_regions WHERE assessment_id = $1 ORDER BY id
`

// ---- id_regions (typed: one region per kind, applied to every page) ----
func (q *Queries) ListIDRegions(ctx context.Context, assessmentID int64) ([]IDRegion, error) {
	rows, err := q.db.Query(ctx, listIDRegions, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IDRegion
	for rows.Next() {
		var i IDRegion
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.X,
			&i.Y,
			&i.W,
			&i.H,
			&i.Color,
			&i.Padding,
			&i.CreatedAt,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveAssignedPagesForAssessment = `-- name: ListLiveAssignedPagesForAssessment :many
SELECT id, assigned_student_id, assigned_problem_id, assigned_by, submission_id
FROM scan_pages
WHERE assessment_id = $1 AND assigned_student_id IS NOT NULL AND discarded_at IS NULL
`

type ListLiveAssignedPagesForAssessmentRow struct {
	ID                int64       `json:"id"`
	AssignedStudentID pgtype.Int8 `json:"assigned_student_id"`
	AssignedProblemID pgtype.Int8 `json:"assigned_problem_id"`
	AssignedBy        pgtype.Int8 `json:"assigned_by"`
	SubmissionID      pgtype.Int8 `json:"submission_id"`
}

func (q *Queries) ListLiveAssignedPagesForAssessment(ctx context.Context, assessmentID int64) ([]ListLiveAssignedPagesForAssessmentRow, error) {
	rows, err := q.db.Query(ctx, listLiveAssignedPagesForAssessment, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiveAssignedPagesForAssessmentRow
	for rows.Next() {
		var i ListLiveAssignedPagesForAssessmentRow
		if err := rows.Scan(
			&i.ID,
			&i.AssignedStudentID,
			&i.AssignedProblemID,
			&i.AssignedBy,
			&i.SubmissionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveSubmissionsForAssessment = `-- name: ListLiveSubmissionsForAssessment :many
SELECT id, student_id, problem_id FROM submissions
WHERE assessment_id = $1 AND superseded_by IS NULL AND retracted_at IS NULL
`

type ListLiveSubmissionsForAssessmentRow struct {
	ID        int64       `json:"id"`
	StudentID int64       `json:"student_id"`
	ProblemID pgtype.Int8 `json:"problem_id"`
}

// Live submissions for the matrix's "covered by a submission" cells (whole-
// assessment rows cover every problem for that student).
func (q *Queries) ListLiveSubmissionsForAssessment(ctx context.Context, assessmentID int64) ([]ListLiveSubmissionsForAssessmentRow, error) {
	rows, err := q.db.Query(ctx, listLiveSubmissionsForAssessment, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiveSubmissionsForAssessmentRow
	for rows.Next() {
		var i ListLiveSubmissionsForAssessmentRow
		if err := rows.Scan(&i.ID, &i.StudentID, &i.ProblemID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMissingCells = `-- name: ListMissingCells :many
SELECT st.student_id, st.name, p.number AS problem_number
FROM students st
CROSS JOIN problems p
WHERE p.assessment_id = $1
  AND st.withdrawn_at IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM scan_pages sp
    WHERE sp.assessment_id = $1
      AND sp.assigned_student_id = st.id AND sp.assigned_problem_id = p.id
      AND sp.discarded_at IS NULL
  )
  AND NOT EXISTS (
    SELECT 1 FROM submissions s
    WHERE s.assessment_id = $1
      AND s.student_id = st.id
      AND s.superseded_by IS NULL AND s.retracted_at IS NULL
      AND (s.problem_id IS NULL OR s.problem_id = p.id)
  )
ORDER BY st.student_id, p.number
`

type ListMissingCellsRow struct {
	StudentID     string `json:"student_id"`
	Name          string `json:"name"`
	ProblemNumber int32  `json:"problem_number"`
}

func (q *Queries) ListMissingCells(ctx context.Context, assessmentID int64) ([]ListMissingCellsRow, error) {
	rows, err := q.db.Query(ctx, listMissingCells, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMissingCellsRow
	for rows.Next() {
		var i ListMissingCellsRow
		if err := rows.Scan(&i.StudentID, &i.Name, &i.ProblemNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScanBatches = `-- name: ListScanBatches :many
SELECT id, assessment_id, ocr_enabled, ocr_provider, ocr_model, source_ref, created_by, created_at FROM scan_batches WHERE assessment_id = $1 ORDER BY id DESC
`

func (q *Queries) ListScanBatches(ctx context.Context, assessmentID int64) ([]ScanBatch, error) {
	rows, err := q.db.Query(ctx, listScanBatches, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanBatch
	for rows.Next() {
		var i ScanBatch
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.OcrEnabled,
			&i.OcrProvider,
			&i.OcrModel,
			&i.SourceRef,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScanPagesForSource = `-- name: ListScanPagesForSource :many
SELECT id, source_id, batch_id, assessment_id, page_index, image_ref, image_sha256, image_width, image_height, student_id_crop_ref, name_crop_ref, problem_crop_ref, ocr_student_id, ocr_name, ocr_problem, ocr_student_id_legible, ocr_name_legible, ocr_problem_legible, ocr_engine, identified_at, proposed_student_id, proposed_problem_id, proposal_source, assigned_student_id, assigned_problem_id, assigned_by, assigned_at, force_promote, parked_reason, parked_against, discarded_at, discard_reason, submission_id, error, attempts, created_at, updated_at, park_student_id, park_problem_id, text_loss_runs FROM scan_pages WHERE source_id = $1 ORDER BY page_index
`

func (q *Queries) ListScanPagesForSource(ctx context.Context, sourceID int64) ([]ScanPage, error) {
	rows, err := q.db.Query(ctx, listScanPagesForSource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanPage
	for rows.Next() {
		var i ScanPage
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.BatchID,
			&i.AssessmentID,
			&i.PageIndex,
			&i.ImageRef,
			&i.ImageSha256,
			&i.ImageWidth,
			&i.ImageHeight,
			&i.StudentIDCropRef,
			&i.NameCropRef,
			&i.ProblemCropRef,
			&i.OcrStudentID,
			&i.OcrName,
			&i.OcrProblem,
			&i.OcrStudentIDLegible,
			&i.OcrNameLegible,
			&i.OcrProblemLegible,
			&i.OcrEngine,
			&i.IdentifiedAt,
			&i.ProposedStudentID,
			&i.ProposedProblemID,
			&i.ProposalSource,
			&i.AssignedStudentID,
			&i.AssignedProblemID,
			&i.AssignedBy,
			&i.AssignedAt,
			&i.ForcePromote,
			&i.ParkedReason,
			&i.ParkedAgainst,
			&i.DiscardedAt,
			&i.DiscardReason,
			&i.SubmissionID,
			&i.Error,
			&i.Attempts,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParkStudentID,
			&i.ParkProblemID,
			&i.TextLossRuns,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScanSourcesForBatch = `-- name: ListScanSourcesForBatch :many
SELECT id, batch_id, original_filename, source_ref, source_sha256, source_kind, page_count, error, created_at FROM scan_sources WHERE batch_id = $1 ORDER BY id
`

func (q *Queries) ListScanSourcesForBatch(ctx context.Context, batchID int64) ([]ScanSource, error) {
	rows, err := q.db.Query(ctx, listScanSourcesForBatch, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanSource
	for rows.Next() {
		var i ScanSource
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.OriginalFilename,
			&i.SourceRef,
			&i.SourceSha256,
			&i.SourceKind,
			&i.PageCount,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWithdrawnStudents = `-- name: ListWithdrawnStudents :many
SELECT id, student_id, name FROM students WHERE withdrawn_at IS NOT NULL ORDER BY student_id
`

type ListWithdrawnStudentsRow struct {
	ID        int64  `json:"id"`
	StudentID string `json:"student_id"`
	Name      string `json:"name"`
}

func (q *Queries) ListWithdrawnStudents(ctx context.Context) ([]ListWithdrawnStudentsRow, error) {
	rows, err := q.db.Query(ctx, listWithdrawnStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWithdrawnStudentsRow
	for rows.Next() {
		var i ListWithdrawnStudentsRow
		if err := rows.Scan(&i.ID, &i.StudentID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const livePageForCell = `-- name: LivePageForCell :one

SELECT id, source_id, batch_id, assessment_id, page_index, image_ref, image_sha256, image_width, image_height, student_id_crop_ref, name_crop_ref, problem_crop_ref, ocr_student_id, ocr_name, ocr_problem, ocr_student_id_legible, ocr_name_legible, ocr_problem_legible, ocr_engine, identified_at, proposed_student_id, proposed_problem_id, proposal_source, assigned_student_id, assigned_problem_id, assigned_by, assigned_at, force_promote, parked_reason, parked_against, discarded_at, discard_reason, submission_id, error, attempts, created_at, updated_at, park_student_id, park_problem_id, text_loss_runs FROM scan_pages
WHERE assessment_id = $1 AND assigned_student_id = $2 AND assigned_problem_id = $3
  AND discarded_at IS NULL AND id <> $4
ORDER BY id LIMIT 1
`

type LivePageForCellParams struct {
	AssessmentID      int64       `json:"assessment_id"`
	AssignedStudentID pgtype.Int8 `json:"assigned_student_id"`
	AssignedProblemID pgtype.Int8 `json:"assigned_problem_id"`
	ID                int64       `json:"id"`
}

// ---- cell occupancy ----
// LivePageForCell finds the live (non-discarded) page already assigned to this
// exact (student, problem) cell, excluding the page being placed. Promoted pages
// count — their assignment is what the submission came from.
func (q *Queries) LivePageForCell(ctx context.Context, arg LivePageForCellParams) (ScanPage, error) {
	row := q.db.QueryRow(ctx, livePageForCell,
		arg.AssessmentID,
		arg.AssignedStudentID,
		arg.AssignedProblemID,
		arg.ID,
	)
	var i ScanPage
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.BatchID,
		&i.AssessmentID,
		&i.PageIndex,
		&i.ImageRef,
		&i.ImageSha256,
		&i.ImageWidth,
		&i.ImageHeight,
		&i.StudentIDCropRef,
		&i.NameCropRef,
		&i.ProblemCropRef,
		&i.OcrStudentID,
		&i.OcrName,
		&i.OcrProblem,
		&i.OcrStudentIDLegible,
		&i.OcrNameLegible,
		&i.OcrProblemLegible,
		&i.OcrEngine,
		&i.IdentifiedAt,
		&i.ProposedStudentID,
		&i.ProposedProblemID,
		&i.ProposalSource,
		&i.AssignedStudentID,
		&i.AssignedProblemID,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.ForcePromote,
		&i.ParkedReason,
		&i.ParkedAgainst,
		&i.DiscardedAt,
		&i.DiscardReason,
		&i.SubmissionID,
		&i.Error,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParkStudentID,
		&i.ParkProblemID,
		&i.TextLossRuns,
	)
	return i, err
}

const parkScanPage = `-- name: ParkScanPage :exec
UPDATE scan_pages
SET parked_reason = $2, parked_against = $3,
    park_student_id = $4, park_problem_id = $5, updated_at = now()
WHERE id = $1
`

type ParkScanPageParams struct {
	ID            int64       `json:"id"`
	ParkedReason  pgtype.Text `json:"parked_reason"`
	ParkedAgainst pgtype.Int8 `json:"parked_against"`
	ParkStudentID pgtype.Int8 `json:"park_student_id"`
	ParkProblemID pgtype.Int8 `json:"park_problem_id"`
}

// ParkScanPage records the CONTESTED cell (park_student_id/park_problem_id)
// alongside the incumbent so ResolveConflict's replace can target the cell
// where the fight happened even after the incumbent moves (see 0031).
func (q *Queries) ParkScanPage(ctx context.Context, arg ParkScanPageParams) error {
	_, err := q.db.Exec(ctx, parkScanPage,
		arg.ID,
		arg.ParkedReason,
		arg.ParkedAgainst,
		arg.ParkStudentID,
		arg.ParkProblemID,
	)
	return err
}

const scanBatchPageProgress = `-- name: ScanBatchPageProgress :many
SELECT batch_id,
    count(*) AS total,
    count(*) FILTER (WHERE error IS NOT NULL AND error <> '') AS errored,
    count(*) FILTER (
        WHERE NOT (error IS NOT NULL AND error <> '')
          AND discarded_at IS NOT NULL
    ) AS discarded,
    count(*) FILTER (
        WHERE NOT (error IS NOT NULL AND error <> '')
          AND discarded_at IS NULL
          AND submission_id IS NOT NULL
    ) AS promoted,
    count(*) FILTER (
        WHERE NOT (error IS NOT NULL AND error <> '')
          AND discarded_at IS NULL
          AND submission_id IS NULL
          AND parked_reason IS NOT NULL
    ) AS parked,
    count(*) FILTER (
        WHERE NOT (error IS NOT NULL AND error <> '')
          AND discarded_at IS NULL
          AND submission_id IS NULL
          AND parked_reason IS NULL
          AND assigned_student_id IS NOT NULL
    ) AS assigned,
    count(*) FILTER (
        WHERE NOT (error IS NOT NULL AND error <> '')
          AND discarded_at IS NULL
          AND submission_id IS NULL
          AND parked_reason IS NULL
          AND assigned_student_id IS NULL
          AND identified_at IS NOT NULL
    ) AS orphaned,
    count(*) FILTER (
        WHERE NOT (error IS NOT NULL AND error <> '')
          AND discarded_at IS NULL
          AND submission_id IS NULL
          AND parked_reason IS NULL
          AND assigned_student_id IS NULL
          AND identified_at IS NULL
    ) AS processing
FROM scan_pages
WHERE batch_id = ANY ($1::bigint [])
GROUP BY batch_id
`

type ScanBatchPageProgressRow struct {
	BatchID    int64 `json:"batch_id"`
	Total      int64 `json:"total"`
	Errored    int64 `json:"errored"`
	Discarded  int64 `json:"discarded"`
	Promoted   int64 `json:"promoted"`
	Parked     int64 `json:"parked"`
	Assigned   int64 `json:"assigned"`
	Orphaned   int64 `json:"orphaned"`
	Processing int64 `json:"processing"`
}

// ScanBatchPageProgress mirrors the derived-state precedence exactly, each
// bucket excluding every higher-precedence condition (D2; F6: no PII columns).
func (q *Queries) ScanBatchPageProgress(ctx context.Context, batchIds []int64) ([]ScanBatchPageProgressRow, error) {
	rows, err := q.db.Query(ctx, scanBatchPageProgress, batchIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanBatchPageProgressRow
	for rows.Next() {
		var i ScanBatchPageProgressRow
		if err := rows.Scan(
			&i.BatchID,
			&i.Total,
			&i.Errored,
			&i.Discarded,
			&i.Promoted,
			&i.Parked,
			&i.Assigned,
			&i.Orphaned,
			&i.Processing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scanPageRows = `-- name: ScanPageRows :many

SELECT sp.id, sp.source_id, sp.batch_id, sp.assessment_id, sp.page_index, sp.image_ref, sp.image_sha256, sp.image_width, sp.image_height, sp.student_id_crop_ref, sp.name_crop_ref, sp.problem_crop_ref, sp.ocr_student_id, sp.ocr_name, sp.ocr_problem, sp.ocr_student_id_legible, sp.ocr_name_legible, sp.ocr_problem_legible, sp.ocr_engine, sp.identified_at, sp.proposed_student_id, sp.proposed_problem_id, sp.proposal_source, sp.assigned_student_id, sp.assigned_problem_id, sp.assigned_by, sp.assigned_at, sp.force_promote, sp.parked_reason, sp.parked_against, sp.discarded_at, sp.discard_reason, sp.submission_id, sp.error, sp.attempts, sp.created_at, sp.updated_at, sp.park_student_id, sp.park_problem_id, sp.text_loss_runs,
    ps.student_id AS proposed_external_id, ps.name AS proposed_name_roster,
    a.student_id AS assigned_external_id, a.name AS assigned_name
FROM scan_pages sp
LEFT JOIN students ps ON ps.id = sp.proposed_student_id
LEFT JOIN students a ON a.id = sp.assigned_student_id
WHERE sp.assessment_id = $1
ORDER BY sp.id
`

type ScanPageRowsRow struct {
	ID                  int64              `json:"id"`
	SourceID            int64              `json:"source_id"`
	BatchID             int64              `json:"batch_id"`
	AssessmentID        int64              `json:"assessment_id"`
	PageIndex           int32              `json:"page_index"`
	ImageRef            pgtype.Text        `json:"image_ref"`
	ImageSha256         pgtype.Text        `json:"image_sha256"`
	ImageWidth          pgtype.Int4        `json:"image_width"`
	ImageHeight         pgtype.Int4        `json:"image_height"`
	StudentIDCropRef    pgtype.Text        `json:"student_id_crop_ref"`
	NameCropRef         pgtype.Text        `json:"name_crop_ref"`
	ProblemCropRef      pgtype.Text        `json:"problem_crop_ref"`
	OcrStudentID        pgtype.Text        `json:"ocr_student_id"`
	OcrName             pgtype.Text        `json:"ocr_name"`
	OcrProblem          pgtype.Text        `json:"ocr_problem"`
	OcrStudentIDLegible pgtype.Bool        `json:"ocr_student_id_legible"`
	OcrNameLegible      pgtype.Bool        `json:"ocr_name_legible"`
	OcrProblemLegible   pgtype.Bool        `json:"ocr_problem_legible"`
	OcrEngine           pgtype.Text        `json:"ocr_engine"`
	IdentifiedAt        pgtype.Timestamptz `json:"identified_at"`
	ProposedStudentID   pgtype.Int8        `json:"proposed_student_id"`
	ProposedProblemID   pgtype.Int8        `json:"proposed_problem_id"`
	ProposalSource      pgtype.Text        `json:"proposal_source"`
	AssignedStudentID   pgtype.Int8        `json:"assigned_student_id"`
	AssignedProblemID   pgtype.Int8        `json:"assigned_problem_id"`
	AssignedBy          pgtype.Int8        `json:"assigned_by"`
	AssignedAt          pgtype.Timestamptz `json:"assigned_at"`
	ForcePromote        bool               `json:"force_promote"`
	ParkedReason        pgtype.Text        `json:"parked_reason"`
	ParkedAgainst       pgtype.Int8        `json:"parked_against"`
	DiscardedAt         pgtype.Timestamptz `json:"discarded_at"`
	DiscardReason       pgtype.Text        `json:"discard_reason"`
	SubmissionID        pgtype.Int8        `json:"submission_id"`
	Error               pgtype.Text        `json:"error"`
	Attempts            int32              `json:"attempts"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ParkStudentID       pgtype.Int8        `json:"park_student_id"`
	ParkProblemID       pgtype.Int8        `json:"park_problem_id"`
	TextLossRuns        int32              `json:"text_loss_runs"`
	ProposedExternalID  pgtype.Text        `json:"proposed_external_id"`
	ProposedNameRoster  pgtype.Text        `json:"proposed_name_roster"`
	AssignedExternalID  pgtype.Text        `json:"assigned_external_id"`
	AssignedName        pgtype.Text        `json:"assigned_name"`
}

// ---- listing / progress / matrix ----
// ScanPageRows joins proposed/assigned student externals for staff-facing JSON
// (PII to an authenticated TA+ session only).
func (q *Queries) ScanPageRows(ctx context.Context, assessmentID int64) ([]ScanPageRowsRow, error) {
	rows, err := q.db.Query(ctx, scanPageRows, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanPageRowsRow
	for rows.Next() {
		var i ScanPageRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.BatchID,
			&i.AssessmentID,
			&i.PageIndex,
			&i.ImageRef,
			&i.ImageSha256,
			&i.ImageWidth,
			&i.ImageHeight,
			&i.StudentIDCropRef,
			&i.NameCropRef,
			&i.ProblemCropRef,
			&i.OcrStudentID,
			&i.OcrName,
			&i.OcrProblem,
			&i.OcrStudentIDLegible,
			&i.OcrNameLegible,
			&i.OcrProblemLegible,
			&i.OcrEngine,
			&i.IdentifiedAt,
			&i.ProposedStudentID,
			&i.ProposedProblemID,
			&i.ProposalSource,
			&i.AssignedStudentID,
			&i.AssignedProblemID,
			&i.AssignedBy,
			&i.AssignedAt,
			&i.ForcePromote,
			&i.ParkedReason,
			&i.ParkedAgainst,
			&i.DiscardedAt,
			&i.DiscardReason,
			&i.SubmissionID,
			&i.Error,
			&i.Attempts,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParkStudentID,
			&i.ParkProblemID,
			&i.TextLossRuns,
			&i.ProposedExternalID,
			&i.ProposedNameRoster,
			&i.AssignedExternalID,
			&i.AssignedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBatchSourceRef = `-- name: SetBatchSourceRef :exec
UPDATE scan_batches SET source_ref = $2 WHERE id = $1
`

type SetBatchSourceRefParams struct {
	ID        int64       `json:"id"`
	SourceRef pgtype.Text `json:"source_ref"`
}

func (q *Queries) SetBatchSourceRef(ctx context.Context, arg SetBatchSourceRefParams) error {
	_, err := q.db.Exec(ctx, setBatchSourceRef, arg.ID, arg.SourceRef)
	return err
}

const setScanBatchOCR = `-- name: SetScanBatchOCR :exec
UPDATE scan_batches SET ocr_provider = $2, ocr_model = $3 WHERE id = $1
`

type SetScanBatchOCRParams struct {
	ID          int64       `json:"id"`
	OcrProvider pgtype.Text `json:"ocr_provider"`
	OcrModel    pgtype.Text `json:"ocr_model"`
}

// SetScanBatchOCR repoints a batch's cloud OCR provider/model — the recovery
// path for a batch created against a provider that is now gone/disabled
// (retry-errored); the batch's provider is otherwise immutable.
func (q *Queries) SetScanBatchOCR(ctx context.Context, arg SetScanBatchOCRParams) error {
	_, err := q.db.Exec(ctx, setScanBatchOCR, arg.ID, arg.OcrProvider, arg.OcrModel)
	return err
}

const setScanPageError = `-- name: SetScanPageError :exec
UPDATE scan_pages SET error = $2, updated_at = now() WHERE id = $1
`

type SetScanPageErrorParams struct {
	ID    int64       `json:"id"`
	Error pgtype.Text `json:"error"`
}

func (q *Queries) SetScanPageError(ctx context.Context, arg SetScanPageErrorParams) error {
	_, err := q.db.Exec(ctx, setScanPageError, arg.ID, arg.Error)
	return err
}

const setScanPageForcePromote = `-- name: SetScanPageForcePromote :exec
UPDATE scan_pages SET force_promote = $2, updated_at = now() WHERE id = $1
`

type SetScanPageForcePromoteParams struct {
	ID           int64 `json:"id"`
	ForcePromote bool  `json:"force_promote"`
}

func (q *Queries) SetScanPageForcePromote(ctx context.Context, arg SetScanPageForcePromoteParams) error {
	_, err := q.db.Exec(ctx, setScanPageForcePromote, arg.ID, arg.ForcePromote)
	return err
}

const setScanPageIdentified = `-- name: SetScanPageIdentified :exec
UPDATE scan_pages
SET ocr_student_id = $2, ocr_name = $3, ocr_problem = $4,
    ocr_student_id_legible = $5, ocr_name_legible = $6, ocr_problem_legible = $7,
    ocr_engine = $8,
    proposed_student_id = $9, proposed_problem_id = $10, proposal_source = $11,
    identified_at = now(), error = NULL, updated_at = now()
WHERE id = $1
`

type SetScanPageIdentifiedParams struct {
	ID                  int64       `json:"id"`
	OcrStudentID        pgtype.Text `json:"ocr_student_id"`
	OcrName             pgtype.Text `json:"ocr_name"`
	OcrProblem          pgtype.Text `json:"ocr_problem"`
	OcrStudentIDLegible pgtype.Bool `json:"ocr_student_id_legible"`
	OcrNameLegible      pgtype.Bool `json:"ocr_name_legible"`
	OcrProblemLegible   pgtype.Bool `json:"ocr_problem_legible"`
	OcrEngine           pgtype.Text `json:"ocr_engine"`
	ProposedStudentID   pgtype.Int8 `json:"proposed_student_id"`
	ProposedProblemID   pgtype.Int8 `json:"proposed_problem_id"`
	ProposalSource      pgtype.Text `json:"proposal_source"`
}

// SetScanPageIdentified records the OCR reads + proposal and stamps
// identified_at — the orphan/processing boundary for derived state.
func (q *Queries) SetScanPageIdentified(ctx context.Context, arg SetScanPageIdentifiedParams) error {
	_, err := q.db.Exec(ctx, setScanPageIdentified,
		arg.ID,
		arg.OcrStudentID,
		arg.OcrName,
		arg.OcrProblem,
		arg.OcrStudentIDLegible,
		arg.OcrNameLegible,
		arg.OcrProblemLegible,
		arg.OcrEngine,
		arg.ProposedStudentID,
		arg.ProposedProblemID,
		arg.ProposalSource,
	)
	return err
}

const setScanPagePromotionError = `-- name: SetScanPagePromotionError :exec
UPDATE scan_pages SET error = $2, updated_at = now() WHERE id = $1 AND submission_id IS NULL
`

type SetScanPagePromotionErrorParams struct {
	ID    int64       `json:"id"`
	Error pgtype.Text `json:"error"`
}

// SetScanPagePromotionError stamps a promote-job failure ONLY on a
// still-unpromoted row (same race guard as the old SetScanFilePromotionError):
// a losing duplicate promote job must not stamp an error onto a promoted row.
func (q *Queries) SetScanPagePromotionError(ctx context.Context, arg SetScanPagePromotionErrorParams) error {
	_, err := q.db.Exec(ctx, setScanPagePromotionError, arg.ID, arg.Error)
	return err
}

const setScanPageRendered = `-- name: SetScanPageRendered :exec
UPDATE scan_pages
SET image_ref = $2, image_sha256 = $3, image_width = $4, image_height = $5,
    student_id_crop_ref = $6, name_crop_ref = $7, problem_crop_ref = $8,
    text_loss_runs = $9,
    error = NULL, updated_at = now()
WHERE id = $1
`

type SetScanPageRenderedParams struct {
	ID               int64       `json:"id"`
	ImageRef         pgtype.Text `json:"image_ref"`
	ImageSha256      pgtype.Text `json:"image_sha256"`
	ImageWidth       pgtype.Int4 `json:"image_width"`
	ImageHeight      pgtype.Int4 `json:"image_height"`
	StudentIDCropRef pgtype.Text `json:"student_id_crop_ref"`
	NameCropRef      pgtype.Text `json:"name_crop_ref"`
	ProblemCropRef   pgtype.Text `json:"problem_crop_ref"`
	TextLossRuns     int32       `json:"text_loss_runs"`
}

func (q *Queries) SetScanPageRendered(ctx context.Context, arg SetScanPageRenderedParams) error {
	_, err := q.db.Exec(ctx, setScanPageRendered,
		arg.ID,
		arg.ImageRef,
		arg.ImageSha256,
		arg.ImageWidth,
		arg.ImageHeight,
		arg.StudentIDCropRef,
		arg.NameCropRef,
		arg.ProblemCropRef,
		arg.TextLossRuns,
	)
	return err
}

const setScanPageSubmission = `-- name: SetScanPageSubmission :exec
UPDATE scan_pages SET submission_id = $2, updated_at = now() WHERE id = $1
`

type SetScanPageSubmissionParams struct {
	ID           int64       `json:"id"`
	SubmissionID pgtype.Int8 `json:"submission_id"`
}

func (q *Queries) SetScanPageSubmission(ctx context.Context, arg SetScanPageSubmissionParams) error {
	_, err := q.db.Exec(ctx, setScanPageSubmission, arg.ID, arg.SubmissionID)
	return err
}

const setScanSourceError = `-- name: SetScanSourceError :exec
UPDATE scan_sources SET error = $2 WHERE id = $1
`

type SetScanSourceErrorParams struct {
	ID    int64       `json:"id"`
	Error pgtype.Text `json:"error"`
}

func (q *Queries) SetScanSourceError(ctx context.Context, arg SetScanSourceErrorParams) error {
	_, err := q.db.Exec(ctx, setScanSourceError, arg.ID, arg.Error)
	return err
}

const setScanSourcePageCount = `-- name: SetScanSourcePageCount :exec
UPDATE scan_sources SET page_count = $2, error = NULL WHERE id = $1
`

type SetScanSourcePageCountParams struct {
	ID        int64       `json:"id"`
	PageCount pgtype.Int4 `json:"page_count"`
}

func (q *Queries) SetScanSourcePageCount(ctx context.Context, arg SetScanSourcePageCountParams) error {
	_, err := q.db.Exec(ctx, setScanSourcePageCount, arg.ID, arg.PageCount)
	return err
}

const unassignScanPage = `-- name: UnassignScanPage :exec
UPDATE scan_pages
SET assigned_student_id = NULL, assigned_problem_id = NULL, assigned_by = NULL,
    assigned_at = NULL, force_promote = FALSE, updated_at = now()
WHERE id = $1
`

func (q *Queries) UnassignScanPage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, unassignScanPage, id)
	return err
}

const undiscardScanPage = `-- name: UndiscardScanPage :exec
UPDATE scan_pages
SET discarded_at = NULL, discard_reason = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) UndiscardScanPage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, undiscardScanPage, id)
	return err
}
