// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spotcheck.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSpotCheck = `-- name: GetSpotCheck :one
SELECT id, run_id, grading_record_id, verdict, note, checker_id, created_at, checked_at FROM spot_checks WHERE id = $1
`

func (q *Queries) GetSpotCheck(ctx context.Context, id int64) (SpotCheck, error) {
	row := q.db.QueryRow(ctx, getSpotCheck, id)
	var i SpotCheck
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.GradingRecordID,
		&i.Verdict,
		&i.Note,
		&i.CheckerID,
		&i.CreatedAt,
		&i.CheckedAt,
	)
	return i, err
}

const insertSpotCheck = `-- name: InsertSpotCheck :one

INSERT INTO spot_checks (run_id, grading_record_id)
VALUES ($1, $2)
ON CONFLICT (run_id, grading_record_id) DO NOTHING
RETURNING id, run_id, grading_record_id, verdict, note, checker_id, created_at, checked_at
`

type InsertSpotCheckParams struct {
	RunID           int64 `json:"run_id"`
	GradingRecordID int64 `json:"grading_record_id"`
}

// Spot-check gate (trust spec §4).
func (q *Queries) InsertSpotCheck(ctx context.Context, arg InsertSpotCheckParams) (SpotCheck, error) {
	row := q.db.QueryRow(ctx, insertSpotCheck, arg.RunID, arg.GradingRecordID)
	var i SpotCheck
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.GradingRecordID,
		&i.Verdict,
		&i.Note,
		&i.CheckerID,
		&i.CreatedAt,
		&i.CheckedAt,
	)
	return i, err
}

const isRunWaived = `-- name: IsRunWaived :one
SELECT EXISTS (SELECT 1 FROM waived_runs WHERE run_id = $1)
`

func (q *Queries) IsRunWaived(ctx context.Context, runID int64) (bool, error) {
	row := q.db.QueryRow(ctx, isRunWaived, runID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listSpotChecks = `-- name: ListSpotChecks :many
SELECT sc.id, sc.run_id, sc.grading_record_id, sc.verdict, sc.note, sc.checker_id, sc.created_at, sc.checked_at, gr.answer_id, gr.total, gr.criterion_scores, gr.confidence,
    p.number AS problem_number
FROM spot_checks sc
JOIN grading_records gr ON gr.id = sc.grading_record_id
JOIN answers a ON a.id = gr.answer_id
JOIN problems p ON p.id = a.problem_id
WHERE sc.run_id = $1
ORDER BY p.number, sc.id
`

type ListSpotChecksRow struct {
	ID              int64              `json:"id"`
	RunID           int64              `json:"run_id"`
	GradingRecordID int64              `json:"grading_record_id"`
	Verdict         pgtype.Text        `json:"verdict"`
	Note            string             `json:"note"`
	CheckerID       pgtype.Int8        `json:"checker_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CheckedAt       pgtype.Timestamptz `json:"checked_at"`
	AnswerID        int64              `json:"answer_id"`
	Total           pgtype.Numeric     `json:"total"`
	CriterionScores []byte             `json:"criterion_scores"`
	Confidence      pgtype.Text        `json:"confidence"`
	ProblemNumber   int32              `json:"problem_number"`
}

func (q *Queries) ListSpotChecks(ctx context.Context, runID int64) ([]ListSpotChecksRow, error) {
	rows, err := q.db.Query(ctx, listSpotChecks, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpotChecksRow
	for rows.Next() {
		var i ListSpotChecksRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.GradingRecordID,
			&i.Verdict,
			&i.Note,
			&i.CheckerID,
			&i.CreatedAt,
			&i.CheckedAt,
			&i.AnswerID,
			&i.Total,
			&i.CriterionScores,
			&i.Confidence,
			&i.ProblemNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSpotCheckVerdict = `-- name: SetSpotCheckVerdict :one
UPDATE spot_checks
SET verdict = $2, note = $3, checker_id = $4, checked_at = now()
WHERE id = $1
RETURNING id, run_id, grading_record_id, verdict, note, checker_id, created_at, checked_at
`

type SetSpotCheckVerdictParams struct {
	ID        int64       `json:"id"`
	Verdict   pgtype.Text `json:"verdict"`
	Note      string      `json:"note"`
	CheckerID pgtype.Int8 `json:"checker_id"`
}

func (q *Queries) SetSpotCheckVerdict(ctx context.Context, arg SetSpotCheckVerdictParams) (SpotCheck, error) {
	row := q.db.QueryRow(ctx, setSpotCheckVerdict,
		arg.ID,
		arg.Verdict,
		arg.Note,
		arg.CheckerID,
	)
	var i SpotCheck
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.GradingRecordID,
		&i.Verdict,
		&i.Note,
		&i.CheckerID,
		&i.CreatedAt,
		&i.CheckedAt,
	)
	return i, err
}

const spotCheckAgreementRate = `-- name: SpotCheckAgreementRate :one
SELECT count(*) FILTER (WHERE verdict = 'agree') AS agreed, count(*) AS total
FROM spot_checks
WHERE run_id = $1 AND verdict IS NOT NULL
`

type SpotCheckAgreementRateRow struct {
	Agreed int64 `json:"agreed"`
	Total  int64 `json:"total"`
}

func (q *Queries) SpotCheckAgreementRate(ctx context.Context, runID int64) (SpotCheckAgreementRateRow, error) {
	row := q.db.QueryRow(ctx, spotCheckAgreementRate, runID)
	var i SpotCheckAgreementRateRow
	err := row.Scan(&i.Agreed, &i.Total)
	return i, err
}

const spotCheckCounts = `-- name: SpotCheckCounts :one
SELECT count(*) AS total, count(*) FILTER (WHERE verdict IS NOT NULL) AS done
FROM spot_checks
WHERE run_id = $1
`

type SpotCheckCountsRow struct {
	Total int64 `json:"total"`
	Done  int64 `json:"done"`
}

func (q *Queries) SpotCheckCounts(ctx context.Context, runID int64) (SpotCheckCountsRow, error) {
	row := q.db.QueryRow(ctx, spotCheckCounts, runID)
	var i SpotCheckCountsRow
	err := row.Scan(&i.Total, &i.Done)
	return i, err
}

const waiveSpotCheck = `-- name: WaiveSpotCheck :exec
INSERT INTO waived_runs (run_id, reason, waived_by)
VALUES ($1, $2, $3)
ON CONFLICT (run_id) DO UPDATE SET reason = EXCLUDED.reason, waived_by = EXCLUDED.waived_by, waived_at = now()
`

type WaiveSpotCheckParams struct {
	RunID    int64       `json:"run_id"`
	Reason   string      `json:"reason"`
	WaivedBy pgtype.Int8 `json:"waived_by"`
}

func (q *Queries) WaiveSpotCheck(ctx context.Context, arg WaiveSpotCheckParams) error {
	_, err := q.db.Exec(ctx, waiveSpotCheck, arg.RunID, arg.Reason, arg.WaivedBy)
	return err
}
