// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: students.sql

package db

import (
	"context"
)

const countStudents = `-- name: CountStudents :one
SELECT count(*) FROM students
`

func (q *Queries) CountStudents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countStudents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBareAnswersForStudent = `-- name: DeleteBareAnswersForStudent :execrows
DELETE FROM answers a
WHERE a.student_id = $1
  AND NOT EXISTS (SELECT 1 FROM answer_pages ap WHERE ap.answer_id = a.id)
  AND NOT EXISTS (SELECT 1 FROM grading_records gr WHERE gr.answer_id = a.id)
`

// DeleteBareAnswersForStudent removes only bare (no page, no grading record)
// answer rows for a student — run immediately before DeleteStudent once
// GetStudentBlockingArtifacts has confirmed nothing real references the row.
// The NOT EXISTS guards are repeated here (not just trusted from the check
// query) so this statement can never destroy a real artifact even if a future
// caller invokes it without the guard query first.
func (q *Queries) DeleteBareAnswersForStudent(ctx context.Context, studentID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBareAnswersForStudent, studentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStudent = `-- name: DeleteStudent :execrows
DELETE FROM students WHERE id = $1
`

func (q *Queries) DeleteStudent(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStudent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getStudent = `-- name: GetStudent :one
SELECT id, student_id, name, email, created_at, updated_at, withdrawn_at FROM students WHERE id = $1
`

func (q *Queries) GetStudent(ctx context.Context, id int64) (Student, error) {
	row := q.db.QueryRow(ctx, getStudent, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WithdrawnAt,
	)
	return i, err
}

const getStudentBlockingArtifacts = `-- name: GetStudentBlockingArtifacts :one
SELECT
    EXISTS (
        SELECT 1 FROM submissions WHERE student_id = $1::bigint
    ) AS has_submissions,
    EXISTS (
        SELECT 1 FROM answers a
        WHERE a.student_id = $1::bigint
          AND (
              EXISTS (SELECT 1 FROM answer_pages ap WHERE ap.answer_id = a.id)
              OR EXISTS (SELECT 1 FROM grading_records gr WHERE gr.answer_id = a.id)
          )
    ) AS has_graded_answers,
    EXISTS (
        SELECT 1 FROM scan_pages sp
        WHERE sp.proposed_student_id = $1::bigint
           OR sp.assigned_student_id = $1::bigint
           OR sp.park_student_id = $1::bigint
    ) AS has_scan_pages,
    EXISTS (
        SELECT 1 FROM publish_items WHERE student_id = $1::bigint
    ) AS has_publish_items,
    EXISTS (
        SELECT 1 FROM regrade_requests WHERE student_id = $1::bigint
    ) AS has_regrade_requests,
    EXISTS (
        SELECT 1 FROM upload_quarantine WHERE resolved_student_id = $1::bigint
    ) AS has_quarantine_resolutions
`

type GetStudentBlockingArtifactsRow struct {
	HasSubmissions           bool `json:"has_submissions"`
	HasGradedAnswers         bool `json:"has_graded_answers"`
	HasScanPages             bool `json:"has_scan_pages"`
	HasPublishItems          bool `json:"has_publish_items"`
	HasRegradeRequests       bool `json:"has_regrade_requests"`
	HasQuarantineResolutions bool `json:"has_quarantine_resolutions"`
}

// GetStudentBlockingArtifacts enumerates every artifact kind that references a
// student row and must block a hard delete (roster-delete plan, B15: a typo'd
// import or smoke-test row can never be removed via Withdraw, and it haunts
// every assessment's publish coverage gate forever). This is the schema's full
// REFERENCES students (id) surface as of migration 0036:
//
//	submissions.student_id            (0003, NOT NULL)
//	answers.student_id                (0003, NOT NULL) -- see has_graded_answers below
//	scan_pages.proposed_student_id    (0029)
//	scan_pages.assigned_student_id    (0029)
//	scan_pages.park_student_id        (0031)
//	publish_items.student_id          (0016, NOT NULL)
//	regrade_requests.student_id       (0017)
//	upload_quarantine.resolved_student_id (0005)
//
// (scan_files/0010 also referenced students but was DROPped by 0029 — nothing
// to check there.)
//
// Bare answers — a MaterializeAnswers row (ingestion.sql EnsureAnswer) with no
// ingested page and no grading record — are NOT listed as a blocker: they are
// pre-created placeholder scaffolding for the whole roster, not evidence the
// student did anything. AnswerIDsForAssessment/AnswerIDsForProblem (runs.sql)
// only ever resolve a run's scope to answers that already have a page, so a
// truly bare answer can never carry a grading_run_item or grading_record
// either — has_graded_answers is a safe, sufficient proxy for "this student's
// answers are real artifacts, not scaffolding."
func (q *Queries) GetStudentBlockingArtifacts(ctx context.Context, studentID int64) (GetStudentBlockingArtifactsRow, error) {
	row := q.db.QueryRow(ctx, getStudentBlockingArtifacts, studentID)
	var i GetStudentBlockingArtifactsRow
	err := row.Scan(
		&i.HasSubmissions,
		&i.HasGradedAnswers,
		&i.HasScanPages,
		&i.HasPublishItems,
		&i.HasRegradeRequests,
		&i.HasQuarantineResolutions,
	)
	return i, err
}

const getStudentByExternalID = `-- name: GetStudentByExternalID :one
SELECT id, student_id, name, email, created_at, updated_at, withdrawn_at FROM students WHERE student_id = $1
`

func (q *Queries) GetStudentByExternalID(ctx context.Context, studentID string) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByExternalID, studentID)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WithdrawnAt,
	)
	return i, err
}

const listActiveStudentIDs = `-- name: ListActiveStudentIDs :many
SELECT student_id FROM students WHERE withdrawn_at IS NULL ORDER BY student_id
`

// ListActiveStudentIDs / ListWithdrawnStudentIDs feed the roster import diff
// (external ids only — no PII columns): actives absent from the CSV are the
// add/drop candidates, withdrawn ids present in the CSV are the retaker trap.
func (q *Queries) ListActiveStudentIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listActiveStudentIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var student_id string
		if err := rows.Scan(&student_id); err != nil {
			return nil, err
		}
		items = append(items, student_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudents = `-- name: ListStudents :many
SELECT id, student_id, name, email, created_at, updated_at, withdrawn_at FROM students ORDER BY student_id
`

func (q *Queries) ListStudents(ctx context.Context) ([]Student, error) {
	rows, err := q.db.Query(ctx, listStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WithdrawnAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWithdrawnStudentIDs = `-- name: ListWithdrawnStudentIDs :many
SELECT student_id FROM students WHERE withdrawn_at IS NOT NULL ORDER BY student_id
`

func (q *Queries) ListWithdrawnStudentIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listWithdrawnStudentIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var student_id string
		if err := rows.Scan(&student_id); err != nil {
			return nil, err
		}
		items = append(items, student_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStudentWithdrawn = `-- name: SetStudentWithdrawn :one
UPDATE students
SET withdrawn_at = CASE WHEN $2::bool THEN now() ELSE NULL END,
    updated_at = now()
WHERE id = $1
RETURNING id, student_id, name, email, created_at, updated_at, withdrawn_at
`

type SetStudentWithdrawnParams struct {
	ID        int64 `json:"id"`
	Withdrawn bool  `json:"withdrawn"`
}

func (q *Queries) SetStudentWithdrawn(ctx context.Context, arg SetStudentWithdrawnParams) (Student, error) {
	row := q.db.QueryRow(ctx, setStudentWithdrawn, arg.ID, arg.Withdrawn)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WithdrawnAt,
	)
	return i, err
}

const setStudentsWithdrawnBulk = `-- name: SetStudentsWithdrawnBulk :execrows
UPDATE students
SET withdrawn_at = CASE WHEN $1::bool THEN now() ELSE NULL END,
    updated_at = now()
WHERE student_id = ANY ($2::text [])
`

type SetStudentsWithdrawnBulkParams struct {
	Withdrawn  bool     `json:"withdrawn"`
	StudentIds []string `json:"student_ids"`
}

// SetStudentsWithdrawnBulk is the import-diff sync action (roster-lifecycle
// plan 2026-07-10): one UPDATE for "Withdraw all N" / "Reinstate all N",
// keyed by EXTERNAL student_id (the ids the bulk endpoints receive). Returns
// the affected-row count; the handler validates unknown ids to a 400 BEFORE
// calling this, so updated == len(ids) on success.
func (q *Queries) SetStudentsWithdrawnBulk(ctx context.Context, arg SetStudentsWithdrawnBulkParams) (int64, error) {
	result, err := q.db.Exec(ctx, setStudentsWithdrawnBulk, arg.Withdrawn, arg.StudentIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertStudent = `-- name: UpsertStudent :one
INSERT INTO students (student_id, name, email)
VALUES ($1, $2, $3)
ON CONFLICT (student_id) DO UPDATE
    SET name = EXCLUDED.name, email = EXCLUDED.email, updated_at = now()
RETURNING id, student_id, name, email, created_at, updated_at, withdrawn_at
`

type UpsertStudentParams struct {
	StudentID string `json:"student_id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
}

func (q *Queries) UpsertStudent(ctx context.Context, arg UpsertStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, upsertStudent, arg.StudentID, arg.Name, arg.Email)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WithdrawnAt,
	)
	return i, err
}
