// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transcriptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAssessmentAnswerCoverage = `-- name: CountAssessmentAnswerCoverage :one
SELECT
    (SELECT count(*) FROM students)::bigint AS students_total,
    (SELECT count(DISTINCT a.student_id) FROM answers a
      WHERE a.assessment_id = $1)::bigint AS students_with_work
`

type CountAssessmentAnswerCoverageRow struct {
	StudentsTotal    int64 `json:"students_total"`
	StudentsWithWork int64 `json:"students_with_work"`
}

// The roster half of the export ladder's prerequisite gates.
//
// students_total is the WHOLE roster, withdrawn rows included — the same count
// CountStudents (students.sql) reports, and the same population the Students page
// lists (D23: withdrawing hides nothing, it only labels). The gate is answering
// "has a roster been loaded at all?", and a withdrawn student is still a loaded
// roster row.
//
// students_with_work counts DISTINCT students holding at least one answers row in
// this assessment. answers rows are materialized per (assessment, student,
// problem), so a plain count would multiply by the problem count.
func (q *Queries) CountAssessmentAnswerCoverage(ctx context.Context, assessmentID int64) (CountAssessmentAnswerCoverageRow, error) {
	row := q.db.QueryRow(ctx, countAssessmentAnswerCoverage, assessmentID)
	var i CountAssessmentAnswerCoverageRow
	err := row.Scan(&i.StudentsTotal, &i.StudentsWithWork)
	return i, err
}

const countProblemTranscriptionStatus = `-- name: CountProblemTranscriptionStatus :many
SELECT
    p.number AS problem_number,
    p.title  AS problem_title,
    COUNT(a.id) AS answers,
    COUNT(t.id) AS cached,
    coalesce((
        SELECT count(*)
        FROM answer_pages ap
        JOIN answers a2 ON a2.id = ap.answer_id
        WHERE a2.problem_id = p.id AND a2.assessment_id = p.assessment_id
    ), 0)::bigint AS pages,
    coalesce((
        SELECT count(DISTINCT ap.answer_id)
        FROM answer_pages ap
        JOIN answers a2 ON a2.id = ap.answer_id
        WHERE a2.problem_id = p.id AND a2.assessment_id = p.assessment_id
    ), 0)::bigint AS answers_with_pages,
    coalesce((
        SELECT count(*)
        FROM answer_pages ap
        JOIN answers a2 ON a2.id = ap.answer_id
        WHERE a2.problem_id = p.id AND a2.assessment_id = p.assessment_id
          AND ap.mask_review_status = 'accepted'
    ), 0)::bigint AS pages_mask_accepted
FROM problems p
LEFT JOIN answers a ON a.problem_id = p.id AND a.assessment_id = p.assessment_id
LEFT JOIN answer_transcriptions t
       ON t.answer_id = a.id
      AND t.model_id = $2
      AND t.prompt_version = $3
      AND t.params_hash = $4
WHERE p.assessment_id = $1
GROUP BY p.id
ORDER BY p.number
`

type CountProblemTranscriptionStatusParams struct {
	AssessmentID  int64  `json:"assessment_id"`
	ModelID       string `json:"model_id"`
	PromptVersion string `json:"prompt_version"`
	ParamsHash    string `json:"params_hash"`
}

type CountProblemTranscriptionStatusRow struct {
	ProblemNumber     int32  `json:"problem_number"`
	ProblemTitle      string `json:"problem_title"`
	Answers           int64  `json:"answers"`
	Cached            int64  `json:"cached"`
	Pages             int64  `json:"pages"`
	AnswersWithPages  int64  `json:"answers_with_pages"`
	PagesMaskAccepted int64  `json:"pages_mask_accepted"`
}

// Per-problem coverage for the export status panel: how many answers exist, how
// many already have a cached transcription under the given contract, and how far
// through mask review the problem's pages are.
//
// The two page counts are what make the export's D10 mask gate a PRE-flight check
// instead of a per-answer degradation discovered mid-bundle: a problem is
// exportable only when every one of its answer_pages rows is human-accepted
// (masks.sql, the same line grading's run gate holds). They are scalar subqueries
// rather than another LEFT JOIN because joining answer_pages here would multiply
// the answers/cached counts by the page count.
//
// Whole-assessment page totals are the SUM of these columns: every answer_pages
// row of an assessment hangs off an answer, and every answer hangs off exactly one
// of this assessment's problems. The status handler derives gates.pages_total /
// gates.pages_mask_accepted that way rather than paying for a second round trip.
//
// GROUP BY p.id (not number/title) so the scalar subqueries may reference p.id:
// grouping by the primary key makes every other problems column functionally
// dependent, and it is also the honest grouping — one row per problem.
func (q *Queries) CountProblemTranscriptionStatus(ctx context.Context, arg CountProblemTranscriptionStatusParams) ([]CountProblemTranscriptionStatusRow, error) {
	rows, err := q.db.Query(ctx, countProblemTranscriptionStatus,
		arg.AssessmentID,
		arg.ModelID,
		arg.PromptVersion,
		arg.ParamsHash,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountProblemTranscriptionStatusRow
	for rows.Next() {
		var i CountProblemTranscriptionStatusRow
		if err := rows.Scan(
			&i.ProblemNumber,
			&i.ProblemTitle,
			&i.Answers,
			&i.Cached,
			&i.Pages,
			&i.AnswersWithPages,
			&i.PagesMaskAccepted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnswerTranscription = `-- name: GetAnswerTranscription :one
SELECT id, answer_id, image_shas, model_id, prompt_version, params_hash, blocks, confidence, redaction_counts, input_tokens, output_tokens, cost_usd, created_at
FROM answer_transcriptions
WHERE answer_id = $1
  AND image_shas = $2
  AND model_id = $3
  AND prompt_version = $4
  AND params_hash = $5
`

type GetAnswerTranscriptionParams struct {
	AnswerID      int64    `json:"answer_id"`
	ImageShas     []string `json:"image_shas"`
	ModelID       string   `json:"model_id"`
	PromptVersion string   `json:"prompt_version"`
	ParamsHash    string   `json:"params_hash"`
}

// Content-addressed cache lookup: same pages, same model, same prompt, same
// params => the transcription was already paid for.
func (q *Queries) GetAnswerTranscription(ctx context.Context, arg GetAnswerTranscriptionParams) (AnswerTranscription, error) {
	row := q.db.QueryRow(ctx, getAnswerTranscription,
		arg.AnswerID,
		arg.ImageShas,
		arg.ModelID,
		arg.PromptVersion,
		arg.ParamsHash,
	)
	var i AnswerTranscription
	err := row.Scan(
		&i.ID,
		&i.AnswerID,
		&i.ImageShas,
		&i.ModelID,
		&i.PromptVersion,
		&i.ParamsHash,
		&i.Blocks,
		&i.Confidence,
		&i.RedactionCounts,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CostUsd,
		&i.CreatedAt,
	)
	return i, err
}

const listAnswerPagesForExport = `-- name: ListAnswerPagesForExport :many
SELECT
    ap.answer_id       AS answer_id,
    ap.page_index      AS page_index,
    ap.masked_image_ref AS masked_image_ref,
    ap.image_sha256    AS image_sha256,
    ap.mask_review_status AS mask_review_status
FROM answer_pages ap
JOIN answers a ON a.id = ap.answer_id
JOIN problems p ON p.id = a.problem_id
WHERE a.assessment_id = $1 AND p.number = $2
ORDER BY ap.answer_id, ap.page_index
`

type ListAnswerPagesForExportParams struct {
	AssessmentID int64 `json:"assessment_id"`
	Number       int32 `json:"number"`
}

type ListAnswerPagesForExportRow struct {
	AnswerID         int64       `json:"answer_id"`
	PageIndex        int32       `json:"page_index"`
	MaskedImageRef   pgtype.Text `json:"masked_image_ref"`
	ImageSha256      string      `json:"image_sha256"`
	MaskReviewStatus string      `json:"mask_review_status"`
}

// Masked page refs in page order. masked_image_ref is the ONLY image that may
// leave the box (D10/D19), and mask_review_status rides along because the
// export must hold grading's own line: a run is blocked while any page is
// unmasked OR not human-accepted (masks.sql, the D10 gate), so the export may
// not ship a pending-review mask to a provider either — pending means nobody
// has confirmed the rectangle actually covers the identity.
func (q *Queries) ListAnswerPagesForExport(ctx context.Context, arg ListAnswerPagesForExportParams) ([]ListAnswerPagesForExportRow, error) {
	rows, err := q.db.Query(ctx, listAnswerPagesForExport, arg.AssessmentID, arg.Number)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnswerPagesForExportRow
	for rows.Next() {
		var i ListAnswerPagesForExportRow
		if err := rows.Scan(
			&i.AnswerID,
			&i.PageIndex,
			&i.MaskedImageRef,
			&i.ImageSha256,
			&i.MaskReviewStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProblemAnswersForExport = `-- name: ListProblemAnswersForExport :many
SELECT
    a.id            AS answer_id,
    s.student_id    AS student_id,
    s.name          AS student_name,
    s.email         AS student_email,
    a.flags         AS flags
FROM answers a
JOIN students s ON s.id = a.student_id
JOIN problems p ON p.id = a.problem_id
WHERE a.assessment_id = $1 AND p.number = $2
ORDER BY s.student_id
`

type ListProblemAnswersForExportParams struct {
	AssessmentID int64 `json:"assessment_id"`
	Number       int32 `json:"number"`
}

type ListProblemAnswersForExportRow struct {
	AnswerID     int64    `json:"answer_id"`
	StudentID    string   `json:"student_id"`
	StudentName  string   `json:"student_name"`
	StudentEmail string   `json:"student_email"`
	Flags        []string `json:"flags"`
}

// Everything the export bundle needs for one (assessment, problem), ordered by
// student id so the archive is deterministic. Students with no answer row are
// absent by construction; the caller reconciles against the roster to tell
// "wrote nothing" from "never scanned".
func (q *Queries) ListProblemAnswersForExport(ctx context.Context, arg ListProblemAnswersForExportParams) ([]ListProblemAnswersForExportRow, error) {
	rows, err := q.db.Query(ctx, listProblemAnswersForExport, arg.AssessmentID, arg.Number)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProblemAnswersForExportRow
	for rows.Next() {
		var i ListProblemAnswersForExportRow
		if err := rows.Scan(
			&i.AnswerID,
			&i.StudentID,
			&i.StudentName,
			&i.StudentEmail,
			&i.Flags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAnswerTranscription = `-- name: UpsertAnswerTranscription :one
INSERT INTO answer_transcriptions (
    answer_id, image_shas, model_id, prompt_version, params_hash,
    blocks, confidence, redaction_counts, input_tokens, output_tokens, cost_usd
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (answer_id, image_shas, model_id, prompt_version, params_hash)
DO UPDATE SET blocks = EXCLUDED.blocks
RETURNING id, answer_id, image_shas, model_id, prompt_version, params_hash, blocks, confidence, redaction_counts, input_tokens, output_tokens, cost_usd, created_at
`

type UpsertAnswerTranscriptionParams struct {
	AnswerID        int64          `json:"answer_id"`
	ImageShas       []string       `json:"image_shas"`
	ModelID         string         `json:"model_id"`
	PromptVersion   string         `json:"prompt_version"`
	ParamsHash      string         `json:"params_hash"`
	Blocks          []byte         `json:"blocks"`
	Confidence      string         `json:"confidence"`
	RedactionCounts []byte         `json:"redaction_counts"`
	InputTokens     pgtype.Int4    `json:"input_tokens"`
	OutputTokens    pgtype.Int4    `json:"output_tokens"`
	CostUsd         pgtype.Numeric `json:"cost_usd"`
}

// ON CONFLICT DO UPDATE rather than DO NOTHING so a concurrent duplicate call
// still returns the row (DO NOTHING returns no rows, which callers would have
// to special-case).
func (q *Queries) UpsertAnswerTranscription(ctx context.Context, arg UpsertAnswerTranscriptionParams) (AnswerTranscription, error) {
	row := q.db.QueryRow(ctx, upsertAnswerTranscription,
		arg.AnswerID,
		arg.ImageShas,
		arg.ModelID,
		arg.PromptVersion,
		arg.ParamsHash,
		arg.Blocks,
		arg.Confidence,
		arg.RedactionCounts,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostUsd,
	)
	var i AnswerTranscription
	err := row.Scan(
		&i.ID,
		&i.AnswerID,
		&i.ImageShas,
		&i.ModelID,
		&i.PromptVersion,
		&i.ParamsHash,
		&i.Blocks,
		&i.Confidence,
		&i.RedactionCounts,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CostUsd,
		&i.CreatedAt,
	)
	return i, err
}
