// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uploads.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDirectUpload = `-- name: CreateDirectUpload :one

INSERT INTO direct_uploads (assessment_id, original_filename, source_ref, source_sha256, source_kind, force, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, assessment_id, original_filename, source_ref, source_sha256, source_kind, force, uploaded_by, created_at, started_at, finished_at, status, reason, submission_id, error
`

type CreateDirectUploadParams struct {
	AssessmentID     int64       `json:"assessment_id"`
	OriginalFilename string      `json:"original_filename"`
	SourceRef        string      `json:"source_ref"`
	SourceSha256     string      `json:"source_sha256"`
	SourceKind       string      `json:"source_kind"`
	Force            bool        `json:"force"`
	UploadedBy       pgtype.Int8 `json:"uploaded_by"`
}

// Direct-upload staging (D27; audit finding F1). A bulk direct upload stages one
// row per file synchronously (size/emptiness checked, blob stored) and enqueues an
// ingest job; the worker runs the ingest pipeline off-request and records the
// FileResult back onto the row. status/reason/submission_id mirror
// ingest.FileResult (never logged — reason/filename can carry PII context, D14).
func (q *Queries) CreateDirectUpload(ctx context.Context, arg CreateDirectUploadParams) (DirectUpload, error) {
	row := q.db.QueryRow(ctx, createDirectUpload,
		arg.AssessmentID,
		arg.OriginalFilename,
		arg.SourceRef,
		arg.SourceSha256,
		arg.SourceKind,
		arg.Force,
		arg.UploadedBy,
	)
	var i DirectUpload
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.OriginalFilename,
		&i.SourceRef,
		&i.SourceSha256,
		&i.SourceKind,
		&i.Force,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Reason,
		&i.SubmissionID,
		&i.Error,
	)
	return i, err
}

const getDirectUpload = `-- name: GetDirectUpload :one
SELECT id, assessment_id, original_filename, source_ref, source_sha256, source_kind, force, uploaded_by, created_at, started_at, finished_at, status, reason, submission_id, error FROM direct_uploads WHERE id = $1
`

func (q *Queries) GetDirectUpload(ctx context.Context, id int64) (DirectUpload, error) {
	row := q.db.QueryRow(ctx, getDirectUpload, id)
	var i DirectUpload
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.OriginalFilename,
		&i.SourceRef,
		&i.SourceSha256,
		&i.SourceKind,
		&i.Force,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Reason,
		&i.SubmissionID,
		&i.Error,
	)
	return i, err
}

const listDirectUploadsForAssessment = `-- name: ListDirectUploadsForAssessment :many
SELECT id, assessment_id, original_filename, source_ref, source_sha256, source_kind, force, uploaded_by, created_at, started_at, finished_at, status, reason, submission_id, error FROM direct_uploads WHERE assessment_id = $1 ORDER BY id DESC LIMIT $2
`

type ListDirectUploadsForAssessmentParams struct {
	AssessmentID int64 `json:"assessment_id"`
	Limit        int32 `json:"limit"`
}

func (q *Queries) ListDirectUploadsForAssessment(ctx context.Context, arg ListDirectUploadsForAssessmentParams) ([]DirectUpload, error) {
	rows, err := q.db.Query(ctx, listDirectUploadsForAssessment, arg.AssessmentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DirectUpload
	for rows.Next() {
		var i DirectUpload
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.OriginalFilename,
			&i.SourceRef,
			&i.SourceSha256,
			&i.SourceKind,
			&i.Force,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.Reason,
			&i.SubmissionID,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDirectUploadResult = `-- name: SetDirectUploadResult :exec
UPDATE direct_uploads
SET status = $2, reason = $3, submission_id = $4, error = $5, finished_at = now()
WHERE id = $1
`

type SetDirectUploadResultParams struct {
	ID           int64       `json:"id"`
	Status       pgtype.Text `json:"status"`
	Reason       pgtype.Text `json:"reason"`
	SubmissionID pgtype.Int8 `json:"submission_id"`
	Error        pgtype.Text `json:"error"`
}

// SetDirectUploadResult records the terminal FileResult (status/reason/submission_id
// for a completed ingest, or error for a transient failure that exhausted retries)
// and stamps finished_at, which flips the row out of the pending set.
func (q *Queries) SetDirectUploadResult(ctx context.Context, arg SetDirectUploadResultParams) error {
	_, err := q.db.Exec(ctx, setDirectUploadResult,
		arg.ID,
		arg.Status,
		arg.Reason,
		arg.SubmissionID,
		arg.Error,
	)
	return err
}

const setDirectUploadStarted = `-- name: SetDirectUploadStarted :exec
UPDATE direct_uploads SET started_at = now() WHERE id = $1
`

// SetDirectUploadStarted stamps started_at so the reconciliation view can show the
// job as in-flight. Idempotent under redelivery: re-stamping is harmless.
func (q *Queries) SetDirectUploadStarted(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, setDirectUploadStarted, id)
	return err
}
