// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT count(*) FROM users WHERE role = 'admin' AND active
`

func (q *Queries) CountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, display_name, role, active)
VALUES ($1, $2, $3, $4)
RETURNING id, email, display_name, role, active, created_at, updated_at
`

type CreateUserParams struct {
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
	Role        string `json:"role"`
	Active      bool   `json:"active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.DisplayName,
		arg.Role,
		arg.Active,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, role, active, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, role, active, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssignableGraders = `-- name: ListAssignableGraders :many
SELECT id, display_name, role FROM users
WHERE active AND role IN ('ta', 'lecturer', 'admin')
ORDER BY display_name, email
`

type ListAssignableGradersRow struct {
	ID          int64  `json:"id"`
	DisplayName string `json:"display_name"`
	Role        string `json:"role"`
}

// Assignable graders for the TA-assignment picker (regrade v2 spec §6/§8 gap 2):
// active users holding TA-or-higher role (ta|lecturer|admin). Deliberately excludes
// inactive users (can't be logged-in assignees) and any lower role. This backs a
// lecturer+ endpoint distinct from admin-only ListUsers, so the SELECT is scoped to
// exactly the minimal fields the handler re-exposes (id, name, role) -- no email.
func (q *Queries) ListAssignableGraders(ctx context.Context) ([]ListAssignableGradersRow, error) {
	rows, err := q.db.Query(ctx, listAssignableGraders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssignableGradersRow
	for rows.Next() {
		var i ListAssignableGradersRow
		if err := rows.Scan(&i.ID, &i.DisplayName, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, display_name, role, active, created_at, updated_at FROM users ORDER BY email
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET role = $2, active = $3, display_name = $4, updated_at = now()
WHERE id = $1
RETURNING id, email, display_name, role, active, created_at, updated_at
`

type UpdateUserParams struct {
	ID          int64  `json:"id"`
	Role        string `json:"role"`
	Active      bool   `json:"active"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Role,
		arg.Active,
		arg.DisplayName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertActiveAdmin = `-- name: UpsertActiveAdmin :one
INSERT INTO users (email, display_name, role, active)
VALUES ($1, '', 'admin', TRUE)
ON CONFLICT (email) DO UPDATE SET role = 'admin', active = TRUE, updated_at = now()
RETURNING id, email, display_name, role, active, created_at, updated_at
`

func (q *Queries) UpsertActiveAdmin(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, upsertActiveAdmin, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
