// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: warnings.sql

package db

import (
	"context"
)

const countActiveRunsForAssessment = `-- name: CountActiveRunsForAssessment :one
SELECT count(*) FROM grading_runs
WHERE assessment_id = $1 AND status IN ('pending', 'running')
`

// CountActiveRunsForAssessment: pending/running grading runs — backs both the
// run_in_progress standing warning and the launch dialog's active_run_overlap.
func (q *Queries) CountActiveRunsForAssessment(ctx context.Context, assessmentID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveRunsForAssessment, assessmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdjustedSpotChecksStillOfficial = `-- name: CountAdjustedSpotChecksStillOfficial :one
SELECT count(*)
FROM spot_checks sc
JOIN grading_records gr ON gr.id = sc.grading_record_id
JOIN answers a ON a.id = gr.answer_id
WHERE a.assessment_id = $1
  AND sc.verdict = 'adjusted'
  AND a.official_record_id = sc.grading_record_id
`

// CountAdjustedSpotChecksStillOfficial: spot-check verdicts recorded as
// "adjusted" whose checked record is STILL the answer's official record — the
// checker disagreed with the grade but the promised correction never landed
// (runs.go handleSetSpotCheckVerdict records the verdict only; the grade edit
// happens elsewhere, or not at all).
func (q *Queries) CountAdjustedSpotChecksStillOfficial(ctx context.Context, assessmentID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAdjustedSpotChecksStillOfficial, assessmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDuplicateActiveEmails = `-- name: CountDuplicateActiveEmails :one
SELECT count(*) FROM (
    SELECT lower(email)
    FROM students
    WHERE withdrawn_at IS NULL AND email <> ''
    GROUP BY lower(email)
    HAVING count(*) > 1
) dup
`

// CountDuplicateActiveEmails: distinct emails shared by more than one ACTIVE
// student (case-insensitive — email routing is), backing the duplicate_emails
// danger warning (roster-lifecycle plan 2026-07-10): two students sharing an
// address means grade emails land in the same mailbox. Blank emails are not
// duplicates of each other. Count of EMAILS, not students, per the code's
// vocabulary; no email values ever leave the query.
func (q *Queries) CountDuplicateActiveEmails(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDuplicateActiveEmails)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMaskErrorPages = `-- name: CountMaskErrorPages :one
SELECT count(*)
FROM answer_pages ap
JOIN answers a ON a.id = ap.answer_id
WHERE a.assessment_id = $1 AND ap.mask_error IS NOT NULL
`

// CountMaskErrorPages: pages whose MaskPage job failed terminally (mask_error,
// migration 0015) — they may still carry an OLD accepted masked image, so a run
// would send a stale/unmasked view to the provider.
func (q *Queries) CountMaskErrorPages(ctx context.Context, assessmentID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countMaskErrorPages, assessmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenQuarantine = `-- name: CountOpenQuarantine :one
SELECT count(*) FROM upload_quarantine
WHERE assessment_id = $1 AND resolved_at IS NULL
`

func (q *Queries) CountOpenQuarantine(ctx context.Context, assessmentID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenQuarantine, assessmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProblemsWithoutRubric = `-- name: CountProblemsWithoutRubric :one
SELECT count(*)
FROM problems p
WHERE p.assessment_id = $1
  AND NOT EXISTS (SELECT 1 FROM rubric_versions rv WHERE rv.problem_id = p.id)
`

func (q *Queries) CountProblemsWithoutRubric(ctx context.Context, assessmentID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countProblemsWithoutRubric, assessmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProblemsWithoutRubricByIDs = `-- name: CountProblemsWithoutRubricByIDs :one
SELECT count(*)
FROM problems p
WHERE p.id = ANY ($1::bigint [])
  AND NOT EXISTS (SELECT 1 FROM rubric_versions rv WHERE rv.problem_id = p.id)
`

// CountProblemsWithoutRubricByIDs is the launch-preflight variant scoped to the
// run's problems (Task B2 resolves the scope to problem ids in Go).
func (q *Queries) CountProblemsWithoutRubricByIDs(ctx context.Context, problemIds []int64) (int64, error) {
	row := q.db.QueryRow(ctx, countProblemsWithoutRubricByIDs, problemIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStudentsWithDuplicateNames = `-- name: CountStudentsWithDuplicateNames :one
SELECT count(*)
FROM students st
WHERE st.withdrawn_at IS NULL
  AND EXISTS (
      SELECT 1 FROM students st2
      WHERE st2.withdrawn_at IS NULL AND st2.id <> st.id AND st2.name = st.name
  )
`

// CountStudentsWithDuplicateNames: ACTIVE students sharing an exact name with
// another active student — the duplicate_student_names info warning (their
// pages can never auto-assign by name, see scan matchOCRName, so Identify
// always needs manual confirmation for them). Count of STUDENTS (both/all
// sharers), matching the code's "count = students sharing a name" contract.
func (q *Queries) CountStudentsWithDuplicateNames(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countStudentsWithDuplicateNames)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSupersededGradedAnswers = `-- name: CountSupersededGradedAnswers :one
SELECT count(*)
FROM answers a
WHERE a.assessment_id = $1
  AND 'image_superseded' = ANY (a.flags)
  AND EXISTS (SELECT 1 FROM grading_records gr WHERE gr.answer_id = a.id)
`

// CountSupersededGradedAnswers: answers whose images were force-replaced after
// grading (ingest stamps the image_superseded flag, ingest.go) and that have at
// least one grading record — those grades scored the OLD images.
func (q *Queries) CountSupersededGradedAnswers(ctx context.Context, assessmentID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countSupersededGradedAnswers, assessmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTextRenderLossPages = `-- name: CountTextRenderLossPages :one
SELECT
    (SELECT count(*)
     FROM answer_pages ap
     JOIN answers a ON a.id = ap.answer_id
     WHERE a.assessment_id = $1 AND ap.text_loss_runs > 0)
  + (SELECT count(*)
     FROM scan_pages sp
     WHERE sp.assessment_id = $1 AND sp.discarded_at IS NULL AND sp.text_loss_runs > 0)
  AS pages
`

// CountTextRenderLossPages: pages whose PDF text layer contained runs that
// rendered as nothing (render.ProbeTextLoss; pdfium drops non-embedded
// CID/CJK glyphs silently). Counts live answer pages plus non-discarded scan
// pages — a flagged scan page keeps warning even after promotion (the
// promoted answer page is re-rasterized from the stored JPEG, which has no
// text layer to probe).
func (q *Queries) CountTextRenderLossPages(ctx context.Context, assessmentID int64) (int32, error) {
	row := q.db.QueryRow(ctx, countTextRenderLossPages, assessmentID)
	var pages int32
	err := row.Scan(&pages)
	return pages, err
}

const countUnmaterializedStudents = `-- name: CountUnmaterializedStudents :one
SELECT count(*)
FROM students st
WHERE st.withdrawn_at IS NULL
  AND EXISTS (SELECT 1 FROM answers any_a WHERE any_a.assessment_id = $1)
  AND NOT EXISTS (SELECT 1 FROM answers a WHERE a.assessment_id = $1 AND a.student_id = st.id)
`

// CountUnmaterializedStudents: ACTIVE students with zero answers rows for this
// assessment while the assessment already has at least one answers row (the
// late-add dead end, roster-lifecycle plan 2026-07-10 — fix is the materialize
// action). The ≥1-answers guard keeps the warning silent on a brand-new
// assessment where NOBODY has been ingested yet.
func (q *Queries) CountUnmaterializedStudents(ctx context.Context, assessmentID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUnmaterializedStudents, assessmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const finalSourceModelRecordStats = `-- name: FinalSourceModelRecordStats :one
SELECT
    COALESCE(ass.final_source_kind = 'method', FALSE)::bool AS final_is_method,
    (
        SELECT count(*)
        FROM grading_records gr
        JOIN answers a ON a.id = gr.answer_id
        WHERE a.assessment_id = ass.id
          AND gr.source = 'model'
          AND gr.run_id = ass.final_run_id
    )::bigint AS model_records
FROM assessments ass
WHERE ass.id = $1
`

type FinalSourceModelRecordStatsRow struct {
	FinalIsMethod bool  `json:"final_is_method"`
	ModelRecords  int64 `json:"model_records"`
}

// FinalSourceModelRecordStats: backs the final_source_no_records danger code
// (analysis redesign plan, Task B1). final_is_method says whether the exam's
// chosen final source is a method at all (FALSE for consensus or undecided);
// model_records counts the pinned run's source='model' records on this
// assessment. Zero with final_is_method means deriving officials from
// the source yields nothing, so publish would send holes.
func (q *Queries) FinalSourceModelRecordStats(ctx context.Context, id int64) (FinalSourceModelRecordStatsRow, error) {
	row := q.db.QueryRow(ctx, finalSourceModelRecordStats, id)
	var i FinalSourceModelRecordStatsRow
	err := row.Scan(&i.FinalIsMethod, &i.ModelRecords)
	return i, err
}

const mixedMethodVersionStats = `-- name: MixedMethodVersionStats :one
WITH officials AS (
    SELECT gr.method_version_id, gmv.version
    FROM answers a
    JOIN assessments ass ON ass.id = a.assessment_id
    JOIN grading_records gr ON gr.id = a.official_record_id
    JOIN grading_method_versions gmv ON gmv.id = gr.method_version_id
    WHERE a.assessment_id = $1
      AND ass.final_source_kind = 'method'
      AND gr.run_id = ass.final_run_id
)

SELECT
    (SELECT count(DISTINCT o.method_version_id) FROM officials o)::bigint AS distinct_versions,
    (
        SELECT count(*) FROM officials o
        WHERE o.version < (SELECT max(o2.version) FROM officials o2)
    )::bigint AS stale_answers
`

type MixedMethodVersionStatsRow struct {
	DistinctVersions int64 `json:"distinct_versions"`
	StaleAnswers     int64 `json:"stale_answers"`
}

// MixedMethodVersionStats is now a corruption/legacy defense: a pinned run owns
// exactly one method version, so healthy final officials can never span versions.
func (q *Queries) MixedMethodVersionStats(ctx context.Context, assessmentID int64) (MixedMethodVersionStatsRow, error) {
	row := q.db.QueryRow(ctx, mixedMethodVersionStats, assessmentID)
	var i MixedMethodVersionStatsRow
	err := row.Scan(&i.DistinctVersions, &i.StaleAnswers)
	return i, err
}

const scanPageStateCounts = `-- name: ScanPageStateCounts :one

SELECT
    count(*) FILTER (
        WHERE NOT (error IS NOT NULL AND error <> '')
          AND discarded_at IS NULL
          AND submission_id IS NULL
          AND parked_reason IS NULL
          AND assigned_student_id IS NOT NULL
    ) AS assigned_unpromoted,
    count(*) FILTER (
        WHERE NOT (error IS NOT NULL AND error <> '')
          AND discarded_at IS NULL
          AND submission_id IS NULL
          AND parked_reason IS NULL
          AND assigned_student_id IS NULL
          AND identified_at IS NULL
    ) AS processing
FROM scan_pages
WHERE assessment_id = $1
`

type ScanPageStateCountsRow struct {
	AssignedUnpromoted int64 `json:"assigned_unpromoted"`
	Processing         int64 `json:"processing"`
}

// Workflow-warning counts (hazard audit 2026-07-10): cheap, assessment-scoped
// COUNT queries backing GET /api/assessments/{id}/workflow-warnings and the
// launch/publish preflight warnings. Counts only — no PII columns ever leave
// these queries.
// ScanPageStateCounts buckets an assessment's scan pages by the SAME derived-
// state precedence as ScanBatchPageProgress (scan.sql — D2: status is derived,
// never stored), collapsed to the buckets the warnings still read directly:
// assigned-but-unpromoted (Finalize not clicked) and still-processing. The
// stranded kinds (errored/parked/orphaned) moved to StrandedScanPageStats,
// which also classifies them by cell coverage.
func (q *Queries) ScanPageStateCounts(ctx context.Context, assessmentID int64) (ScanPageStateCountsRow, error) {
	row := q.db.QueryRow(ctx, scanPageStateCounts, assessmentID)
	var i ScanPageStateCountsRow
	err := row.Scan(&i.AssignedUnpromoted, &i.Processing)
	return i, err
}

const strandedScanPageStats = `-- name: StrandedScanPageStats :one
WITH stranded AS (
    SELECT
        CASE
            WHEN sp.error IS NOT NULL AND sp.error <> '' THEN 'errored'
            WHEN sp.parked_reason IS NOT NULL THEN 'parked'
            ELSE 'orphaned'
        END AS kind,
        CASE
            WHEN sp.assigned_student_id IS NOT NULL THEN sp.assigned_student_id
            WHEN sp.proposed_student_id IS NOT NULL AND sp.proposed_problem_id IS NOT NULL
                THEN sp.proposed_student_id
        END AS cell_student_id,
        CASE
            WHEN sp.assigned_student_id IS NOT NULL THEN sp.assigned_problem_id
            WHEN sp.proposed_student_id IS NOT NULL AND sp.proposed_problem_id IS NOT NULL
                THEN sp.proposed_problem_id
        END AS cell_problem_id
    FROM scan_pages sp
    WHERE sp.assessment_id = $1
      AND (
          (sp.error IS NOT NULL AND sp.error <> '')
          OR (
              sp.discarded_at IS NULL AND sp.submission_id IS NULL
              AND (
                  sp.parked_reason IS NOT NULL
                  OR (sp.assigned_student_id IS NULL AND sp.identified_at IS NOT NULL)
              )
          )
      )
),

classified AS (
    SELECT
        st.kind,
        st.cell_student_id,
        st.cell_problem_id,
        (st.cell_student_id IS NOT NULL AND EXISTS (
            SELECT 1 FROM submissions s
            WHERE s.assessment_id = $1
              AND s.student_id = st.cell_student_id
              AND s.superseded_by IS NULL AND s.retracted_at IS NULL
              AND (s.problem_id IS NULL OR s.problem_id = st.cell_problem_id)
        )) AS covered
    FROM stranded st
)

SELECT
    count(*) FILTER (WHERE c.cell_student_id IS NOT NULL AND NOT c.covered) AS uncovered,
    count(*) FILTER (WHERE c.cell_student_id IS NOT NULL AND NOT c.covered AND c.kind = 'orphaned') AS uncovered_orphaned,
    count(*) FILTER (WHERE c.cell_student_id IS NOT NULL AND NOT c.covered AND c.kind = 'parked') AS uncovered_parked,
    count(*) FILTER (WHERE c.cell_student_id IS NOT NULL AND NOT c.covered AND c.kind = 'errored') AS uncovered_errored,
    (
        SELECT count(DISTINCT (c2.cell_student_id, c2.cell_problem_id))
        FROM classified c2
        WHERE c2.cell_student_id IS NOT NULL AND NOT c2.covered
    )::bigint AS uncovered_cells,
    count(*) FILTER (WHERE c.cell_student_id IS NULL) AS unidentified,
    count(*) FILTER (WHERE c.covered) AS covered_pages
FROM classified c
`

type StrandedScanPageStatsRow struct {
	Uncovered         int64 `json:"uncovered"`
	UncoveredOrphaned int64 `json:"uncovered_orphaned"`
	UncoveredParked   int64 `json:"uncovered_parked"`
	UncoveredErrored  int64 `json:"uncovered_errored"`
	UncoveredCells    int64 `json:"uncovered_cells"`
	Unidentified      int64 `json:"unidentified"`
	CoveredPages      int64 `json:"covered_pages"`
}

// StrandedScanPageStats classifies an assessment's stranded scan pages —
// errored, parked, orphaned, same derived-state precedence as
// ScanBatchPageProgress (D2) — by whether the (student, problem) cell they
// claim is already covered by a live submission (false-alarm fix 2026-07-11):
// a failed batch superseded by a successful re-upload leaves dead pages behind,
// and those must not warn "answers grade incomplete" when every cell is covered.
//
//   - uncovered_*: pages with a known cell (the assigned pair when assigned,
//     else the OCR-proposed pair when both halves exist) that NO live submission
//     covers — the real hazard: those answers grade incomplete or not at all.
//     uncovered_cells is the distinct (student, problem) count behind them.
//   - unidentified: stranded pages with no assigned or proposed identity — they
//     cannot be checked against coverage, so they stay worth flagging, but with
//     wording that never claims incompleteness.
//   - covered_pages: pages whose cell IS covered by a live submission — dead
//     leftovers (e.g. a superseded batch), informational only.
//
// Coverage mirrors CountMissingCells (scan.sql): a live (non-superseded,
// non-retracted) submission for the student, whole-assessment or per-problem.
// Counts only — no PII columns ever leave this query.
func (q *Queries) StrandedScanPageStats(ctx context.Context, assessmentID int64) (StrandedScanPageStatsRow, error) {
	row := q.db.QueryRow(ctx, strandedScanPageStats, assessmentID)
	var i StrandedScanPageStatsRow
	err := row.Scan(
		&i.Uncovered,
		&i.UncoveredOrphaned,
		&i.UncoveredParked,
		&i.UncoveredErrored,
		&i.UncoveredCells,
		&i.Unidentified,
		&i.CoveredPages,
	)
	return i, err
}
